// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lead_credits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeadCredit = `-- name: GetLeadCredit :one
SELECT tenant_id, balance, version, created_at, updated_at
FROM   platform.lead_credits
WHERE  tenant_id = $1
`

func (q *Queries) GetLeadCredit(ctx context.Context, tenantID pgtype.UUID) (PlatformLeadCredit, error) {
	row := q.db.QueryRow(ctx, getLeadCredit, tenantID)
	var i PlatformLeadCredit
	err := row.Scan(
		&i.TenantID,
		&i.Balance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLeadCredit = `-- name: InsertLeadCredit :exec

INSERT INTO platform.lead_credits (
    tenant_id, balance, version, created_at, updated_at
) VALUES (
    $1, $2, 1, $3, $4
)
`

type InsertLeadCreditParams struct {
	TenantID  pgtype.UUID
	Balance   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Platform module lead-credits queries (ADR 0059). Optimistic-version
// balance ledger; see internal/platform/adapters/lead_credit_repository_pg.go.
// Inserts a fresh row with version=1 so post-INSERT reads return
// Version=1. The repository's optimistic-version UPDATE path can
// then unambiguously detect "fresh aggregate, no DB row" by checking
// in-memory Version==0 (only NewForTenant emits 0; every loaded
// aggregate carries >=1).
func (q *Queries) InsertLeadCredit(ctx context.Context, arg InsertLeadCreditParams) error {
	_, err := q.db.Exec(ctx, insertLeadCredit,
		arg.TenantID,
		arg.Balance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateLeadCreditWithVersion = `-- name: UpdateLeadCreditWithVersion :execrows
UPDATE platform.lead_credits
SET    balance    = $1::bigint,
       version    = $2::bigint + 1,
       updated_at = $3::timestamptz
WHERE  tenant_id = $4::uuid
  AND  version   = $2::bigint
`

type UpdateLeadCreditWithVersionParams struct {
	NewBalance      int64
	ExpectedVersion int64
	UpdatedAt       pgtype.Timestamptz
	TenantID        pgtype.UUID
}

// Optimistic-version UPDATE per ADR 0059. Returns rows-affected;
// caller treats 0 as ErrConflict + retries.
func (q *Queries) UpdateLeadCreditWithVersion(ctx context.Context, arg UpdateLeadCreditWithVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeadCreditWithVersion,
		arg.NewBalance,
		arg.ExpectedVersion,
		arg.UpdatedAt,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
