// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lead_purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeadTier = `-- name: GetLeadTier :one
SELECT code, default_sale_limit, base_price_paisa
FROM   platform.lead_tiers
WHERE  code = $1
`

type GetLeadTierRow struct {
	Code             string
	DefaultSaleLimit int32
	BasePricePaisa   int64
}

// Per-tier config: default sale limit + base price.
func (q *Queries) GetLeadTier(ctx context.Context, code string) (GetLeadTierRow, error) {
	row := q.db.QueryRow(ctx, getLeadTier, code)
	var i GetLeadTierRow
	err := row.Scan(&i.Code, &i.DefaultSaleLimit, &i.BasePricePaisa)
	return i, err
}

const insertLeadPurchase = `-- name: InsertLeadPurchase :exec

INSERT INTO platform.lead_purchases (
    id, lead_id, tenant_id, created_by_membership_id, amount_paisa, purchased_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertLeadPurchaseParams struct {
	ID                    pgtype.UUID
	LeadID                pgtype.UUID
	TenantID              pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	AmountPaisa           int64
	PurchasedAt           pgtype.Timestamptz
}

// Platform module — marketplace purchase + tier queries. Per ADR 0065.
// One buyer row. UNIQUE(lead_id, tenant_id) makes a double-buy a 23505 that
// the adapter translates to ErrAlreadyPurchased.
func (q *Queries) InsertLeadPurchase(ctx context.Context, arg InsertLeadPurchaseParams) error {
	_, err := q.db.Exec(ctx, insertLeadPurchase,
		arg.ID,
		arg.LeadID,
		arg.TenantID,
		arg.CreatedByMembershipID,
		arg.AmountPaisa,
		arg.PurchasedAt,
	)
	return err
}

const listLeadPurchaseTenantIDs = `-- name: ListLeadPurchaseTenantIDs :many
SELECT tenant_id
FROM   platform.lead_purchases
WHERE  lead_id = $1
ORDER  BY purchased_at ASC, id ASC
`

// Buyer tenant IDs for a lead — hydrates the aggregate's buyer set so
// RecordPurchase can enforce no-double-buy + the sale-limit count. Read
// inside the purchase tx after the lead row is locked (GetPlatformLeadByID
// ForUpdate) so the count is race-free.
func (q *Queries) ListLeadPurchaseTenantIDs(ctx context.Context, leadID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listLeadPurchaseTenantIDs, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
