// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeadCredit = `-- name: GetLeadCredit :one
SELECT tenant_id, balance, version, created_at, updated_at
FROM   platform.lead_credits
WHERE  tenant_id = $1
`

func (q *Queries) GetLeadCredit(ctx context.Context, tenantID pgtype.UUID) (PlatformLeadCredit, error) {
	row := q.db.QueryRow(ctx, getLeadCredit, tenantID)
	var i PlatformLeadCredit
	err := row.Scan(
		&i.TenantID,
		&i.Balance,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLeadCredit = `-- name: InsertLeadCredit :exec
INSERT INTO platform.lead_credits (
    tenant_id, balance, version, created_at, updated_at
) VALUES (
    $1, $2, 1, $3, $4
)
`

type InsertLeadCreditParams struct {
	TenantID  pgtype.UUID
	Balance   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Inserts a fresh row with version=1 so post-INSERT reads return
// Version=1. The repository's optimistic-version UPDATE path can
// then unambiguously detect "fresh aggregate, no DB row" by checking
// in-memory Version==0 (only NewForTenant emits 0; every loaded
// aggregate carries >=1).
func (q *Queries) InsertLeadCredit(ctx context.Context, arg InsertLeadCreditParams) error {
	_, err := q.db.Exec(ctx, insertLeadCredit,
		arg.TenantID,
		arg.Balance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPlatformOutboxEvent = `-- name: InsertPlatformOutboxEvent :exec

INSERT INTO platform.outbox (
    id, tenant_id, topic, payload, occurred_at,
    act_operator_id, act_session_id, act_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPlatformOutboxEventParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Platform module outbox queries. Same shape as identity.outbox per
// ADR 0008 + 0027 + ADR 0059.
func (q *Queries) InsertPlatformOutboxEvent(ctx context.Context, arg InsertPlatformOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertPlatformOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.Topic,
		arg.Payload,
		arg.OccurredAt,
		arg.ActOperatorID,
		arg.ActSessionID,
		arg.ActReason,
	)
	return err
}

const listUnforwardedPlatformOutboxEvents = `-- name: ListUnforwardedPlatformOutboxEvents :many
SELECT id, tenant_id, topic, payload, occurred_at, created_at,
       forwarded, forwarded_at,
       act_operator_id, act_session_id, act_reason
FROM   platform.outbox
WHERE  forwarded = false
ORDER  BY created_at, id
LIMIT  $1
FOR    UPDATE SKIP LOCKED
`

// Forwarder polls this under platform-bypass. FOR UPDATE SKIP LOCKED
// lets multiple forwarder replicas drain concurrently without
// double-publishing (same canonical shape as identity's forwarder).
func (q *Queries) ListUnforwardedPlatformOutboxEvents(ctx context.Context, limit int32) ([]PlatformOutbox, error) {
	rows, err := q.db.Query(ctx, listUnforwardedPlatformOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformOutbox
	for rows.Next() {
		var i PlatformOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Forwarded,
			&i.ForwardedAt,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlatformOutboxEventForwarded = `-- name: MarkPlatformOutboxEventForwarded :exec
UPDATE platform.outbox
SET    forwarded    = true,
       forwarded_at = $2
WHERE  id = $1
`

type MarkPlatformOutboxEventForwardedParams struct {
	ID          pgtype.UUID
	ForwardedAt pgtype.Timestamptz
}

func (q *Queries) MarkPlatformOutboxEventForwarded(ctx context.Context, arg MarkPlatformOutboxEventForwardedParams) error {
	_, err := q.db.Exec(ctx, markPlatformOutboxEventForwarded, arg.ID, arg.ForwardedAt)
	return err
}

const updateLeadCreditWithVersion = `-- name: UpdateLeadCreditWithVersion :execrows
UPDATE platform.lead_credits
SET    balance    = $1::bigint,
       version    = $2::bigint + 1,
       updated_at = $3::timestamptz
WHERE  tenant_id = $4::uuid
  AND  version   = $2::bigint
`

type UpdateLeadCreditWithVersionParams struct {
	NewBalance      int64
	ExpectedVersion int64
	UpdatedAt       pgtype.Timestamptz
	TenantID        pgtype.UUID
}

// Optimistic-version UPDATE per ADR 0059. Returns rows-affected;
// caller treats 0 as ErrConflict + retries.
func (q *Queries) UpdateLeadCreditWithVersion(ctx context.Context, arg UpdateLeadCreditWithVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeadCreditWithVersion,
		arg.NewBalance,
		arg.ExpectedVersion,
		arg.UpdatedAt,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
