// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_leads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformLeadByID = `-- name: GetPlatformLeadByID :one
SELECT id, source_contact_id,
       sold_to_tenant_id, sold_at, sold_to_membership_id, amount_paisa,
       contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
       has_drug_licence, has_gst, gst_number, gst_verified, has_pan, pan_number,
       business_type, medicine_system, product_ranges, dosage_forms,
       order_value, buy_timeline,
       verified_at, verified_by_membership_id, created_at
FROM   platform.platform_leads
WHERE  id = $1
`

func (q *Queries) GetPlatformLeadByID(ctx context.Context, id pgtype.UUID) (PlatformPlatformLead, error) {
	row := q.db.QueryRow(ctx, getPlatformLeadByID, id)
	var i PlatformPlatformLead
	err := row.Scan(
		&i.ID,
		&i.SourceContactID,
		&i.SoldToTenantID,
		&i.SoldAt,
		&i.SoldToMembershipID,
		&i.AmountPaisa,
		&i.ContactName,
		&i.MobileE164,
		&i.Email,
		&i.Pincode,
		&i.City,
		&i.District,
		&i.StateGeo,
		&i.Street,
		&i.HasDrugLicence,
		&i.HasGst,
		&i.GstNumber,
		&i.GstVerified,
		&i.HasPan,
		&i.PanNumber,
		&i.BusinessType,
		&i.MedicineSystem,
		&i.ProductRanges,
		&i.DosageForms,
		&i.OrderValue,
		&i.BuyTimeline,
		&i.VerifiedAt,
		&i.VerifiedByMembershipID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlatformLead = `-- name: InsertPlatformLead :exec

INSERT INTO platform.platform_leads (
    id, source_contact_id,
    sold_to_tenant_id, sold_at, sold_to_membership_id, amount_paisa,
    contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
    has_drug_licence, has_gst, gst_number, gst_verified, has_pan, pan_number,
    business_type, medicine_system, product_ranges, dosage_forms,
    order_value, buy_timeline,
    verified_at, verified_by_membership_id, created_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26,
    $27, $28, $29
)
`

type InsertPlatformLeadParams struct {
	ID                     pgtype.UUID
	SourceContactID        pgtype.UUID
	SoldToTenantID         pgtype.UUID
	SoldAt                 pgtype.Timestamptz
	SoldToMembershipID     pgtype.UUID
	AmountPaisa            int64
	ContactName            string
	MobileE164             string
	Email                  string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	Street                 string
	HasDrugLicence         bool
	HasGst                 bool
	GstNumber              string
	GstVerified            bool
	HasPan                 bool
	PanNumber              string
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

// Platform module — PlatformLead queries. Per ADR 0059.
func (q *Queries) InsertPlatformLead(ctx context.Context, arg InsertPlatformLeadParams) error {
	_, err := q.db.Exec(ctx, insertPlatformLead,
		arg.ID,
		arg.SourceContactID,
		arg.SoldToTenantID,
		arg.SoldAt,
		arg.SoldToMembershipID,
		arg.AmountPaisa,
		arg.ContactName,
		arg.MobileE164,
		arg.Email,
		arg.Pincode,
		arg.City,
		arg.District,
		arg.StateGeo,
		arg.Street,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstNumber,
		arg.GstVerified,
		arg.HasPan,
		arg.PanNumber,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.ProductRanges,
		arg.DosageForms,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.VerifiedAt,
		arg.VerifiedByMembershipID,
		arg.CreatedAt,
	)
	return err
}

const marketplaceBrowse = `-- name: MarketplaceBrowse :many
SELECT id, source_contact_id,
       sold_to_tenant_id, sold_at, sold_to_membership_id, amount_paisa,
       contact_name, pincode, city, district, state_geo,
       has_drug_licence, has_gst, gst_verified, has_pan,
       business_type, medicine_system, product_ranges, dosage_forms,
       order_value, buy_timeline,
       verified_at, verified_by_membership_id, created_at
FROM   platform.platform_leads
WHERE  sold_to_tenant_id IS NULL
AND    ($1::text IS NULL          OR state_geo = $1)
AND    ($2::text IS NULL           OR city = $2)
AND    ($3::text IS NULL       OR district = $3)
AND    ($4::text IS NULL        OR pincode = $4)
AND    ($5::text IS NULL  OR business_type = $5)
AND    ($6::text IS NULL OR medicine_system = $6)
AND    ($7::text IS NULL    OR order_value = $7)
AND    ($8::text IS NULL   OR buy_timeline = $8)
AND    ($9::boolean IS NULL OR has_drug_licence = $9)
AND    ($10::boolean IS NULL     OR has_gst = $10)
AND    ($11::boolean IS NULL OR gst_verified = $11)
AND    ($12::text[] IS NULL OR product_ranges && $12::text[])
AND    ($13::text[] IS NULL OR dosage_forms && $13::text[])
AND    ($14::timestamptz IS NULL
        OR (verified_at, id) < ($14::timestamptz, $15::uuid))
ORDER  BY verified_at DESC, id DESC
LIMIT  $16
`

type MarketplaceBrowseParams struct {
	State            *string
	City             *string
	District         *string
	Pincode          *string
	BusinessType     *string
	MedicineSystem   *string
	OrderValue       *string
	BuyTimeline      *string
	HasDrugLicence   *bool
	HasGst           *bool
	GstVerified      *bool
	ProductRanges    []string
	DosageForms      []string
	CursorVerifiedAt pgtype.Timestamptz
	CursorID         pgtype.UUID
	Lim              int32
}

type MarketplaceBrowseRow struct {
	ID                     pgtype.UUID
	SourceContactID        pgtype.UUID
	SoldToTenantID         pgtype.UUID
	SoldAt                 pgtype.Timestamptz
	SoldToMembershipID     pgtype.UUID
	AmountPaisa            int64
	ContactName            string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	HasDrugLicence         bool
	HasGst                 bool
	GstVerified            bool
	HasPan                 bool
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

// BRD §4.3 marketplace browse. Null-guarded optional filters: a NULL
// arg means "don't filter on this column". Array filters use GIN `&&`
// overlap; keyset cursor on (verified_at, id) DESC.
//
// H12 SECURITY: the SELECT list DELIBERATELY OMITS PII columns
// (email, mobile_e164, gst_number, pan_number, street). This is a
// hard projection boundary per ADR 0059 — never add those columns.
// Because the list is a strict subset, sqlc emits a custom
// MarketplaceBrowseRow type (not the full PlatformPlatformLead model);
// that's intentional and correct here.
func (q *Queries) MarketplaceBrowse(ctx context.Context, arg MarketplaceBrowseParams) ([]MarketplaceBrowseRow, error) {
	rows, err := q.db.Query(ctx, marketplaceBrowse,
		arg.State,
		arg.City,
		arg.District,
		arg.Pincode,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstVerified,
		arg.ProductRanges,
		arg.DosageForms,
		arg.CursorVerifiedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceBrowseRow
	for rows.Next() {
		var i MarketplaceBrowseRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceContactID,
			&i.SoldToTenantID,
			&i.SoldAt,
			&i.SoldToMembershipID,
			&i.AmountPaisa,
			&i.ContactName,
			&i.Pincode,
			&i.City,
			&i.District,
			&i.StateGeo,
			&i.HasDrugLicence,
			&i.HasGst,
			&i.GstVerified,
			&i.HasPan,
			&i.BusinessType,
			&i.MedicineSystem,
			&i.ProductRanges,
			&i.DosageForms,
			&i.OrderValue,
			&i.BuyTimeline,
			&i.VerifiedAt,
			&i.VerifiedByMembershipID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlatformLead = `-- name: UpdatePlatformLead :exec
UPDATE platform.platform_leads SET
    sold_to_tenant_id     = $2,
    sold_at               = $3,
    sold_to_membership_id = $4,
    amount_paisa          = $5,
    gst_verified          = $6
WHERE id = $1
`

type UpdatePlatformLeadParams struct {
	ID                 pgtype.UUID
	SoldToTenantID     pgtype.UUID
	SoldAt             pgtype.Timestamptz
	SoldToMembershipID pgtype.UUID
	AmountPaisa        int64
	GstVerified        bool
}

func (q *Queries) UpdatePlatformLead(ctx context.Context, arg UpdatePlatformLeadParams) error {
	_, err := q.db.Exec(ctx, updatePlatformLead,
		arg.ID,
		arg.SoldToTenantID,
		arg.SoldAt,
		arg.SoldToMembershipID,
		arg.AmountPaisa,
		arg.GstVerified,
	)
	return err
}
