// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_leads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformLeadByID = `-- name: GetPlatformLeadByID :one
SELECT id, source_contact_id,
       sold_to_tenant_id, sold_at, sold_to_membership_id, amount_paisa,
       contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
       has_drug_licence, has_gst, gst_number, gst_verified, has_pan, pan_number,
       business_type, medicine_system, product_ranges, dosage_forms,
       order_value, buy_timeline,
       verified_at, verified_by_membership_id, created_at
FROM   platform.platform_leads
WHERE  id = $1
`

func (q *Queries) GetPlatformLeadByID(ctx context.Context, id pgtype.UUID) (PlatformPlatformLead, error) {
	row := q.db.QueryRow(ctx, getPlatformLeadByID, id)
	var i PlatformPlatformLead
	err := row.Scan(
		&i.ID,
		&i.SourceContactID,
		&i.SoldToTenantID,
		&i.SoldAt,
		&i.SoldToMembershipID,
		&i.AmountPaisa,
		&i.ContactName,
		&i.MobileE164,
		&i.Email,
		&i.Pincode,
		&i.City,
		&i.District,
		&i.StateGeo,
		&i.Street,
		&i.HasDrugLicence,
		&i.HasGst,
		&i.GstNumber,
		&i.GstVerified,
		&i.HasPan,
		&i.PanNumber,
		&i.BusinessType,
		&i.MedicineSystem,
		&i.ProductRanges,
		&i.DosageForms,
		&i.OrderValue,
		&i.BuyTimeline,
		&i.VerifiedAt,
		&i.VerifiedByMembershipID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlatformLead = `-- name: InsertPlatformLead :exec

INSERT INTO platform.platform_leads (
    id, source_contact_id,
    sold_to_tenant_id, sold_at, sold_to_membership_id, amount_paisa,
    contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
    has_drug_licence, has_gst, gst_number, gst_verified, has_pan, pan_number,
    business_type, medicine_system, product_ranges, dosage_forms,
    order_value, buy_timeline,
    verified_at, verified_by_membership_id, created_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26,
    $27, $28, $29
)
`

type InsertPlatformLeadParams struct {
	ID                     pgtype.UUID
	SourceContactID        pgtype.UUID
	SoldToTenantID         pgtype.UUID
	SoldAt                 pgtype.Timestamptz
	SoldToMembershipID     pgtype.UUID
	AmountPaisa            int64
	ContactName            string
	MobileE164             string
	Email                  string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	Street                 string
	HasDrugLicence         bool
	HasGst                 bool
	GstNumber              string
	GstVerified            bool
	HasPan                 bool
	PanNumber              string
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

// Platform module — PlatformLead queries. Per ADR 0059.
//
// Static reads only — the marketplace browse with dynamic filters is
// assembled via squirrel directly in the adapter (sqlc can't express
// the optional WHERE clauses on text[] GIN columns cleanly).
func (q *Queries) InsertPlatformLead(ctx context.Context, arg InsertPlatformLeadParams) error {
	_, err := q.db.Exec(ctx, insertPlatformLead,
		arg.ID,
		arg.SourceContactID,
		arg.SoldToTenantID,
		arg.SoldAt,
		arg.SoldToMembershipID,
		arg.AmountPaisa,
		arg.ContactName,
		arg.MobileE164,
		arg.Email,
		arg.Pincode,
		arg.City,
		arg.District,
		arg.StateGeo,
		arg.Street,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstNumber,
		arg.GstVerified,
		arg.HasPan,
		arg.PanNumber,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.ProductRanges,
		arg.DosageForms,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.VerifiedAt,
		arg.VerifiedByMembershipID,
		arg.CreatedAt,
	)
	return err
}

const updatePlatformLead = `-- name: UpdatePlatformLead :exec
UPDATE platform.platform_leads SET
    sold_to_tenant_id     = $2,
    sold_at               = $3,
    sold_to_membership_id = $4,
    amount_paisa          = $5,
    gst_verified          = $6
WHERE id = $1
`

type UpdatePlatformLeadParams struct {
	ID                 pgtype.UUID
	SoldToTenantID     pgtype.UUID
	SoldAt             pgtype.Timestamptz
	SoldToMembershipID pgtype.UUID
	AmountPaisa        int64
	GstVerified        bool
}

func (q *Queries) UpdatePlatformLead(ctx context.Context, arg UpdatePlatformLeadParams) error {
	_, err := q.db.Exec(ctx, updatePlatformLead,
		arg.ID,
		arg.SoldToTenantID,
		arg.SoldAt,
		arg.SoldToMembershipID,
		arg.AmountPaisa,
		arg.GstVerified,
	)
	return err
}
