// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unverified_contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnverifiedContactByID = `-- name: GetUnverifiedContactByID :one
SELECT id, state, rejection_reason,
       busy_callback_at, busy_callback_end_at, platform_lead_id,
       contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
       has_drug_licence, has_gst, gst_number, has_pan, pan_number,
       business_type, medicine_system, product_ranges, dosage_forms,
       order_value, buy_timeline,
       created_at, created_by_membership_id,
       verified_at, verified_by_membership_id,
       rejected_at, rejected_by_membership_id
FROM   platform.unverified_contacts
WHERE  id = $1
`

func (q *Queries) GetUnverifiedContactByID(ctx context.Context, id pgtype.UUID) (PlatformUnverifiedContact, error) {
	row := q.db.QueryRow(ctx, getUnverifiedContactByID, id)
	var i PlatformUnverifiedContact
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.RejectionReason,
		&i.BusyCallbackAt,
		&i.BusyCallbackEndAt,
		&i.PlatformLeadID,
		&i.ContactName,
		&i.MobileE164,
		&i.Email,
		&i.Pincode,
		&i.City,
		&i.District,
		&i.StateGeo,
		&i.Street,
		&i.HasDrugLicence,
		&i.HasGst,
		&i.GstNumber,
		&i.HasPan,
		&i.PanNumber,
		&i.BusinessType,
		&i.MedicineSystem,
		&i.ProductRanges,
		&i.DosageForms,
		&i.OrderValue,
		&i.BuyTimeline,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
		&i.VerifiedAt,
		&i.VerifiedByMembershipID,
		&i.RejectedAt,
		&i.RejectedByMembershipID,
	)
	return i, err
}

const insertUnverifiedContact = `-- name: InsertUnverifiedContact :exec

INSERT INTO platform.unverified_contacts (
    id, state, rejection_reason,
    busy_callback_at, busy_callback_end_at, platform_lead_id,
    contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
    has_drug_licence, has_gst, gst_number, has_pan, pan_number,
    business_type, medicine_system, product_ranges, dosage_forms,
    order_value, buy_timeline,
    created_at, created_by_membership_id,
    verified_at, verified_by_membership_id,
    rejected_at, rejected_by_membership_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19,
    $20, $21, $22, $23,
    $24, $25,
    $26, $27,
    $28, $29,
    $30, $31
)
`

type InsertUnverifiedContactParams struct {
	ID                     pgtype.UUID
	State                  string
	RejectionReason        string
	BusyCallbackAt         pgtype.Timestamptz
	BusyCallbackEndAt      pgtype.Timestamptz
	PlatformLeadID         pgtype.UUID
	ContactName            string
	MobileE164             string
	Email                  string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	Street                 string
	HasDrugLicence         bool
	HasGst                 bool
	GstNumber              string
	HasPan                 bool
	PanNumber              string
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	RejectedAt             pgtype.Timestamptz
	RejectedByMembershipID pgtype.UUID
}

// Platform module — UnverifiedContact queries. Per ADR 0059.
func (q *Queries) InsertUnverifiedContact(ctx context.Context, arg InsertUnverifiedContactParams) error {
	_, err := q.db.Exec(ctx, insertUnverifiedContact,
		arg.ID,
		arg.State,
		arg.RejectionReason,
		arg.BusyCallbackAt,
		arg.BusyCallbackEndAt,
		arg.PlatformLeadID,
		arg.ContactName,
		arg.MobileE164,
		arg.Email,
		arg.Pincode,
		arg.City,
		arg.District,
		arg.StateGeo,
		arg.Street,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstNumber,
		arg.HasPan,
		arg.PanNumber,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.ProductRanges,
		arg.DosageForms,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
		arg.VerifiedAt,
		arg.VerifiedByMembershipID,
		arg.RejectedAt,
		arg.RejectedByMembershipID,
	)
	return err
}

const listUnverifiedContactsPage = `-- name: ListUnverifiedContactsPage :many
SELECT id, state, rejection_reason,
       busy_callback_at, busy_callback_end_at, platform_lead_id,
       contact_name, mobile_e164, email, pincode, city, district, state_geo, street,
       has_drug_licence, has_gst, gst_number, has_pan, pan_number,
       business_type, medicine_system, product_ranges, dosage_forms,
       order_value, buy_timeline,
       created_at, created_by_membership_id,
       verified_at, verified_by_membership_id,
       rejected_at, rejected_by_membership_id
FROM   platform.unverified_contacts
WHERE  ($1::text = '' OR state = $1::text)
  AND  ($2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER  BY created_at DESC, id DESC
LIMIT  $4
`

type ListUnverifiedContactsPageParams struct {
	StateFilter string
	CursorAt    pgtype.Timestamptz
	CursorID    pgtype.UUID
	PageSize    int32
}

// Keyset pagination on (created_at, id) DESC. State filter optional:
// caller passes empty string to skip the state predicate.
//
// Caller passes pageSize+1 to detect "has next page" per ADR 0038.
// The cursor predicate is gated by `cursor_at` non-NULL so the first
// page (cursor zero) skips the (created_at,id) < (...) comparison.
func (q *Queries) ListUnverifiedContactsPage(ctx context.Context, arg ListUnverifiedContactsPageParams) ([]PlatformUnverifiedContact, error) {
	rows, err := q.db.Query(ctx, listUnverifiedContactsPage,
		arg.StateFilter,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformUnverifiedContact
	for rows.Next() {
		var i PlatformUnverifiedContact
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.RejectionReason,
			&i.BusyCallbackAt,
			&i.BusyCallbackEndAt,
			&i.PlatformLeadID,
			&i.ContactName,
			&i.MobileE164,
			&i.Email,
			&i.Pincode,
			&i.City,
			&i.District,
			&i.StateGeo,
			&i.Street,
			&i.HasDrugLicence,
			&i.HasGst,
			&i.GstNumber,
			&i.HasPan,
			&i.PanNumber,
			&i.BusinessType,
			&i.MedicineSystem,
			&i.ProductRanges,
			&i.DosageForms,
			&i.OrderValue,
			&i.BuyTimeline,
			&i.CreatedAt,
			&i.CreatedByMembershipID,
			&i.VerifiedAt,
			&i.VerifiedByMembershipID,
			&i.RejectedAt,
			&i.RejectedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnverifiedContact = `-- name: UpdateUnverifiedContact :exec
UPDATE platform.unverified_contacts SET
    state                     = $2,
    rejection_reason          = $3,
    busy_callback_at          = $4,
    busy_callback_end_at      = $5,
    platform_lead_id          = $6,
    verified_at               = $7,
    verified_by_membership_id = $8,
    rejected_at               = $9,
    rejected_by_membership_id = $10
WHERE id = $1
`

type UpdateUnverifiedContactParams struct {
	ID                     pgtype.UUID
	State                  string
	RejectionReason        string
	BusyCallbackAt         pgtype.Timestamptz
	BusyCallbackEndAt      pgtype.Timestamptz
	PlatformLeadID         pgtype.UUID
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	RejectedAt             pgtype.Timestamptz
	RejectedByMembershipID pgtype.UUID
}

func (q *Queries) UpdateUnverifiedContact(ctx context.Context, arg UpdateUnverifiedContactParams) error {
	_, err := q.db.Exec(ctx, updateUnverifiedContact,
		arg.ID,
		arg.State,
		arg.RejectionReason,
		arg.BusyCallbackAt,
		arg.BusyCallbackEndAt,
		arg.PlatformLeadID,
		arg.VerifiedAt,
		arg.VerifiedByMembershipID,
		arg.RejectedAt,
		arg.RejectedByMembershipID,
	)
	return err
}
