// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_calls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertVerificationCall = `-- name: InsertVerificationCall :exec

INSERT INTO platform.verification_calls (
    id, contact_id, outcome_code, notes,
    callback_window_start_at, callback_window_end_at,
    logged_at, logged_by_membership_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8
)
`

type InsertVerificationCallParams struct {
	ID                    pgtype.UUID
	ContactID             pgtype.UUID
	OutcomeCode           string
	Notes                 string
	CallbackWindowStartAt pgtype.Timestamptz
	CallbackWindowEndAt   pgtype.Timestamptz
	LoggedAt              pgtype.Timestamptz
	LoggedByMembershipID  pgtype.UUID
}

// Platform module — VerificationCall queries. Per ADR 0059.
func (q *Queries) InsertVerificationCall(ctx context.Context, arg InsertVerificationCallParams) error {
	_, err := q.db.Exec(ctx, insertVerificationCall,
		arg.ID,
		arg.ContactID,
		arg.OutcomeCode,
		arg.Notes,
		arg.CallbackWindowStartAt,
		arg.CallbackWindowEndAt,
		arg.LoggedAt,
		arg.LoggedByMembershipID,
	)
	return err
}

const listVerificationCallsByContact = `-- name: ListVerificationCallsByContact :many
SELECT id, contact_id, outcome_code, notes,
       callback_window_start_at, callback_window_end_at,
       logged_at, logged_by_membership_id
FROM   platform.verification_calls
WHERE  contact_id = $1
ORDER  BY logged_at DESC
`

func (q *Queries) ListVerificationCallsByContact(ctx context.Context, contactID pgtype.UUID) ([]PlatformVerificationCall, error) {
	rows, err := q.db.Query(ctx, listVerificationCallsByContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformVerificationCall
	for rows.Next() {
		var i PlatformVerificationCall
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.OutcomeCode,
			&i.Notes,
			&i.CallbackWindowStartAt,
			&i.CallbackWindowEndAt,
			&i.LoggedAt,
			&i.LoggedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
