// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consignment_notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsignmentNoteByID = `-- name: GetConsignmentNoteByID :one
SELECT id, tenant_id, order_id, status, carrier_name, docket_number,
       box_count, weight_grams, expected_delivery_at,
       dispatched_at, in_transit_at, delivered_at, failed_at, failure_reason,
       created_at, created_by_membership_id
FROM   dispatch.consignment_notes
WHERE  id = $1
`

func (q *Queries) GetConsignmentNoteByID(ctx context.Context, id pgtype.UUID) (DispatchConsignmentNote, error) {
	row := q.db.QueryRow(ctx, getConsignmentNoteByID, id)
	var i DispatchConsignmentNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Status,
		&i.CarrierName,
		&i.DocketNumber,
		&i.BoxCount,
		&i.WeightGrams,
		&i.ExpectedDeliveryAt,
		&i.DispatchedAt,
		&i.InTransitAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getConsignmentNoteByIDForUpdate = `-- name: GetConsignmentNoteByIDForUpdate :one
SELECT id, tenant_id, order_id, status, carrier_name, docket_number,
       box_count, weight_grams, expected_delivery_at,
       dispatched_at, in_transit_at, delivered_at, failed_at, failure_reason,
       created_at, created_by_membership_id
FROM   dispatch.consignment_notes
WHERE  id = $1
FOR UPDATE
`

// Row-locks the note for the UpdateFn transaction so concurrent status
// transitions serialise.
func (q *Queries) GetConsignmentNoteByIDForUpdate(ctx context.Context, id pgtype.UUID) (DispatchConsignmentNote, error) {
	row := q.db.QueryRow(ctx, getConsignmentNoteByIDForUpdate, id)
	var i DispatchConsignmentNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Status,
		&i.CarrierName,
		&i.DocketNumber,
		&i.BoxCount,
		&i.WeightGrams,
		&i.ExpectedDeliveryAt,
		&i.DispatchedAt,
		&i.InTransitAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getConsignmentNoteByOrderID = `-- name: GetConsignmentNoteByOrderID :one
SELECT id, tenant_id, order_id, status, carrier_name, docket_number,
       box_count, weight_grams, expected_delivery_at,
       dispatched_at, in_transit_at, delivered_at, failed_at, failure_reason,
       created_at, created_by_membership_id
FROM   dispatch.consignment_notes
WHERE  order_id = $1
`

func (q *Queries) GetConsignmentNoteByOrderID(ctx context.Context, orderID pgtype.UUID) (DispatchConsignmentNote, error) {
	row := q.db.QueryRow(ctx, getConsignmentNoteByOrderID, orderID)
	var i DispatchConsignmentNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Status,
		&i.CarrierName,
		&i.DocketNumber,
		&i.BoxCount,
		&i.WeightGrams,
		&i.ExpectedDeliveryAt,
		&i.DispatchedAt,
		&i.InTransitAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertConsignmentNote = `-- name: InsertConsignmentNote :exec

INSERT INTO dispatch.consignment_notes (
    id, tenant_id, order_id, status, carrier_name, docket_number,
    box_count, weight_grams, expected_delivery_at,
    dispatched_at, in_transit_at, delivered_at, failed_at, failure_reason,
    created_at, created_by_membership_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16
)
`

type InsertConsignmentNoteParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	OrderID               pgtype.UUID
	Status                string
	CarrierName           string
	DocketNumber          string
	BoxCount              int32
	WeightGrams           int64
	ExpectedDeliveryAt    pgtype.Timestamptz
	DispatchedAt          pgtype.Timestamptz
	InTransitAt           pgtype.Timestamptz
	DeliveredAt           pgtype.Timestamptz
	FailedAt              pgtype.Timestamptz
	FailureReason         string
	CreatedAt             pgtype.Timestamptz
	CreatedByMembershipID pgtype.UUID
}

// Dispatch module — ConsignmentNote queries. Per ADR 0063.
// Tenant scoping is enforced by RLS (the adapter binds app.tenant_id via the
// transactor); WHERE clauses key on id / order_id only.
func (q *Queries) InsertConsignmentNote(ctx context.Context, arg InsertConsignmentNoteParams) error {
	_, err := q.db.Exec(ctx, insertConsignmentNote,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.Status,
		arg.CarrierName,
		arg.DocketNumber,
		arg.BoxCount,
		arg.WeightGrams,
		arg.ExpectedDeliveryAt,
		arg.DispatchedAt,
		arg.InTransitAt,
		arg.DeliveredAt,
		arg.FailedAt,
		arg.FailureReason,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const updateConsignmentNoteState = `-- name: UpdateConsignmentNoteState :exec
UPDATE dispatch.consignment_notes SET
    status         = $2,
    docket_number  = $3,
    dispatched_at  = $4,
    in_transit_at  = $5,
    delivered_at   = $6,
    failed_at      = $7,
    failure_reason = $8
WHERE id = $1
`

type UpdateConsignmentNoteStateParams struct {
	ID            pgtype.UUID
	Status        string
	DocketNumber  string
	DispatchedAt  pgtype.Timestamptz
	InTransitAt   pgtype.Timestamptz
	DeliveredAt   pgtype.Timestamptz
	FailedAt      pgtype.Timestamptz
	FailureReason string
}

// Persists the mutable lifecycle columns. The immutable shipment facts
// (carrier, box_count, weight, expected_delivery, created_*) never change.
func (q *Queries) UpdateConsignmentNoteState(ctx context.Context, arg UpdateConsignmentNoteStateParams) error {
	_, err := q.db.Exec(ctx, updateConsignmentNoteState,
		arg.ID,
		arg.Status,
		arg.DocketNumber,
		arg.DispatchedAt,
		arg.InTransitAt,
		arg.DeliveredAt,
		arg.FailedAt,
		arg.FailureReason,
	)
	return err
}
