// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_emissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlertEmission = `-- name: InsertAlertEmission :execrows

INSERT INTO inventory.alert_emissions (
    tenant_id, kind, subject_id, emitted_date
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (tenant_id, kind, subject_id, emitted_date) DO NOTHING
`

type InsertAlertEmissionParams struct {
	TenantID    pgtype.UUID
	Kind        string
	SubjectID   pgtype.UUID
	EmittedDate pgtype.Date
}

// Alert-emission dedup queries — feed the ExpiryScanJob +
// ReorderScanJob workers. PK on (tenant_id, kind, subject_id,
// emitted_date) makes second-run-same-day a no-op via INSERT ON
// CONFLICT DO NOTHING.
// Returns rows-affected — 0 when the row already existed (deduped);
// 1 when freshly inserted (caller publishes the integration event).
func (q *Queries) InsertAlertEmission(ctx context.Context, arg InsertAlertEmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAlertEmission,
		arg.TenantID,
		arg.Kind,
		arg.SubjectID,
		arg.EmittedDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTenantsWithProducts = `-- name: ListTenantsWithProducts :many
SELECT DISTINCT tenant_id
FROM   inventory.products
WHERE  NOT is_deleted
ORDER  BY tenant_id ASC
`

// Distinct tenant_ids carrying at least one LIVE product. Drives the
// per-tenant scan loop in ExpiryScanJob + ReorderScanJob — runs
// under platform-scope (no GUC binding) so the worker sees all
// tenants. Result set bounded by tenant count (low-thousands at
// v0.2 scale).
func (q *Queries) ListTenantsWithProducts(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantsWithProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
