// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBatch = `-- name: InsertBatch :exec
INSERT INTO inventory.batches (
    id, product_id, tenant_id, batch_number,
    manufacture_date, expiry_date,
    manufacturer_name, manufacturing_licence_number,
    mrp_paise, purchase_price_paise,
    quantity_on_hand, version,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10,
    $11, $12,
    $13, $14
)`

type InsertBatchParams struct {
	ID                         pgtype.UUID
	ProductID                  pgtype.UUID
	TenantID                   pgtype.UUID
	BatchNumber                string
	ManufactureDate            pgtype.Date
	ExpiryDate                 pgtype.Date
	ManufacturerName           string
	ManufacturingLicenceNumber string
	MrpPaise                   int64
	PurchasePricePaise         int64
	QuantityOnHand             int64
	Version                    int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) error {
	_, err := q.db.Exec(ctx, insertBatch,
		arg.ID, arg.ProductID, arg.TenantID, arg.BatchNumber,
		arg.ManufactureDate, arg.ExpiryDate,
		arg.ManufacturerName, arg.ManufacturingLicenceNumber,
		arg.MrpPaise, arg.PurchasePricePaise,
		arg.QuantityOnHand, arg.Version,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, product_id, tenant_id, batch_number,
       manufacture_date, expiry_date,
       manufacturer_name, manufacturing_licence_number,
       mrp_paise, purchase_price_paise,
       quantity_on_hand, version,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by
FROM   inventory.batches
WHERE  id = $1
AND    NOT is_deleted`

func (q *Queries) GetBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatchByID, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID, &i.ProductID, &i.TenantID, &i.BatchNumber,
		&i.ManufactureDate, &i.ExpiryDate,
		&i.ManufacturerName, &i.ManufacturingLicenceNumber,
		&i.MrpPaise, &i.PurchasePricePaise,
		&i.QuantityOnHand, &i.Version,
		&i.CreatedAt, &i.UpdatedAt,
		&i.IsDeleted, &i.DeletedAt, &i.DeletedBy,
	)
	return i, err
}

const updateBatchWithVersionCheck = `-- name: UpdateBatchWithVersionCheck :execrows
UPDATE inventory.batches
SET    quantity_on_hand = $2,
       version          = $3,
       updated_at       = $4,
       is_deleted       = $5,
       deleted_at       = $6,
       deleted_by       = $7,
       batch_number     = $8,
       manufacturer_name = $9,
       manufacturing_licence_number = $10
WHERE  id = $1
AND    version = $11`

type UpdateBatchWithVersionCheckParams struct {
	ID                         pgtype.UUID
	QuantityOnHand             int64
	Version                    int64
	UpdatedAt                  pgtype.Timestamptz
	IsDeleted                  bool
	DeletedAt                  pgtype.Timestamptz
	DeletedBy                  *string
	BatchNumber                string
	ManufacturerName           string
	ManufacturingLicenceNumber string
	VersionExpected            int64
}

// UpdateBatchWithVersionCheck returns rows-affected so the adapter can
// branch on 0 → ErrConcurrencyConflict per Vernon IDDD ch.10.
func (q *Queries) UpdateBatchWithVersionCheck(ctx context.Context, arg UpdateBatchWithVersionCheckParams) (int64, error) {
	tag, err := q.db.Exec(ctx, updateBatchWithVersionCheck,
		arg.ID, arg.QuantityOnHand, arg.Version, arg.UpdatedAt,
		arg.IsDeleted, arg.DeletedAt, arg.DeletedBy,
		arg.BatchNumber, arg.ManufacturerName, arg.ManufacturingLicenceNumber,
		arg.VersionExpected,
	)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

const listBatchesByProductPage = `-- name: ListBatchesByProductPage :many
SELECT id, product_id, tenant_id, batch_number,
       manufacture_date, expiry_date,
       manufacturer_name, manufacturing_licence_number,
       mrp_paise, purchase_price_paise,
       quantity_on_hand, version,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by
FROM   inventory.batches
WHERE  product_id = $1
AND    NOT is_deleted
AND    ($4::boolean OR expiry_date > now())
AND    (expiry_date, id) < ($2, $3)
ORDER  BY expiry_date DESC, id DESC
LIMIT  $5`

type ListBatchesByProductPageParams struct {
	ProductID          pgtype.UUID
	CursorExpiryDate   pgtype.Date
	CursorID           pgtype.UUID
	IncludeExpired     bool
	Limit              int32
}

func (q *Queries) ListBatchesByProductPage(ctx context.Context, arg ListBatchesByProductPageParams) ([]InventoryBatch, error) {
	rows, err := q.db.Query(ctx, listBatchesByProductPage,
		arg.ProductID, arg.CursorExpiryDate, arg.CursorID, arg.IncludeExpired, arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryBatch
	for rows.Next() {
		var i InventoryBatch
		if err := rows.Scan(
			&i.ID, &i.ProductID, &i.TenantID, &i.BatchNumber,
			&i.ManufactureDate, &i.ExpiryDate,
			&i.ManufacturerName, &i.ManufacturingLicenceNumber,
			&i.MrpPaise, &i.PurchasePricePaise,
			&i.QuantityOnHand, &i.Version,
			&i.CreatedAt, &i.UpdatedAt,
			&i.IsDeleted, &i.DeletedAt, &i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const anyLiveBatchWithStockForProduct = `-- name: AnyLiveBatchWithStockForProduct :one
SELECT EXISTS (
    SELECT 1
    FROM   inventory.batches
    WHERE  product_id = $1
    AND    NOT is_deleted
    AND    quantity_on_hand > 0
)`

func (q *Queries) AnyLiveBatchWithStockForProduct(ctx context.Context, productID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, anyLiveBatchWithStockForProduct, productID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
