// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anyLiveBatchWithStockForProduct = `-- name: AnyLiveBatchWithStockForProduct :one
SELECT EXISTS (
    SELECT 1
    FROM   inventory.batches
    WHERE  product_id = $1
    AND    NOT is_deleted
    AND    quantity_on_hand > 0
)
`

func (q *Queries) AnyLiveBatchWithStockForProduct(ctx context.Context, productID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, anyLiveBatchWithStockForProduct, productID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, product_id, tenant_id, batch_number,
       manufacture_date, expiry_date,
       manufacturer_name, manufacturing_licence_number,
       mrp_paise, purchase_price_paise,
       quantity_on_hand, version,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by, created_by_membership_id
FROM   inventory.batches
WHERE  id = $1
AND    NOT is_deleted
`

func (q *Queries) GetBatchByID(ctx context.Context, id pgtype.UUID) (InventoryBatch, error) {
	row := q.db.QueryRow(ctx, getBatchByID, id)
	var i InventoryBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TenantID,
		&i.BatchNumber,
		&i.ManufactureDate,
		&i.ExpiryDate,
		&i.ManufacturerName,
		&i.ManufacturingLicenceNumber,
		&i.MrpPaise,
		&i.PurchasePricePaise,
		&i.QuantityOnHand,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertBatch = `-- name: InsertBatch :exec

INSERT INTO inventory.batches (
    id, product_id, tenant_id, batch_number,
    manufacture_date, expiry_date,
    manufacturer_name, manufacturing_licence_number,
    mrp_paise, purchase_price_paise,
    quantity_on_hand, version,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10,
    $11, $12,
    $13, $14
)
`

type InsertBatchParams struct {
	ID                         pgtype.UUID
	ProductID                  pgtype.UUID
	TenantID                   pgtype.UUID
	BatchNumber                string
	ManufactureDate            pgtype.Date
	ExpiryDate                 pgtype.Date
	ManufacturerName           string
	ManufacturingLicenceNumber string
	MrpPaise                   int64
	PurchasePricePaise         int64
	QuantityOnHand             int64
	Version                    int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

// Batch queries — inventory.batches is tenant-scoped + RLS-FORCE.
// Composite-FK on (product_id, tenant_id) → products(id, tenant_id)
// guarantees same-tenant linkage at the DB.
func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) error {
	_, err := q.db.Exec(ctx, insertBatch,
		arg.ID,
		arg.ProductID,
		arg.TenantID,
		arg.BatchNumber,
		arg.ManufactureDate,
		arg.ExpiryDate,
		arg.ManufacturerName,
		arg.ManufacturingLicenceNumber,
		arg.MrpPaise,
		arg.PurchasePricePaise,
		arg.QuantityOnHand,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listBatchesByProductPage = `-- name: ListBatchesByProductPage :many
SELECT id, product_id, tenant_id, batch_number,
       manufacture_date, expiry_date,
       manufacturer_name, manufacturing_licence_number,
       mrp_paise, purchase_price_paise,
       quantity_on_hand, version,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by, created_by_membership_id
FROM   inventory.batches
WHERE  product_id = $1
AND    NOT is_deleted
AND    ($2::boolean OR expiry_date > now())
AND    (expiry_date, id) < ($3::date, $4::uuid)
ORDER  BY expiry_date DESC, id DESC
LIMIT  $5
`

type ListBatchesByProductPageParams struct {
	ProductID        pgtype.UUID
	IncludeExpired   bool
	CursorExpiryDate pgtype.Date
	CursorID         pgtype.UUID
	Limit            int32
}

// Cursor-paginated list per ADR 0038. Keyset on (expiry_date, id) DESC
// because FEFO ordering = expiry-first per BRD §6.5. Note: ASC for FEFO
// would be natural, but to keep the canonical "(sort_value, id) <"
// predicate consistent with the rest of the platform, we order DESC
// on (expiry_date, id) — the frontend can reverse for FEFO display.
func (q *Queries) ListBatchesByProductPage(ctx context.Context, arg ListBatchesByProductPageParams) ([]InventoryBatch, error) {
	rows, err := q.db.Query(ctx, listBatchesByProductPage,
		arg.ProductID,
		arg.IncludeExpired,
		arg.CursorExpiryDate,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryBatch
	for rows.Next() {
		var i InventoryBatch
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TenantID,
			&i.BatchNumber,
			&i.ManufactureDate,
			&i.ExpiryDate,
			&i.ManufacturerName,
			&i.ManufacturingLicenceNumber,
			&i.MrpPaise,
			&i.PurchasePricePaise,
			&i.QuantityOnHand,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBatchForUpdate = `-- name: LockBatchForUpdate :one
SELECT id
FROM   inventory.batches
WHERE  id = $1
AND    NOT is_deleted
FOR UPDATE
`

// Pessimistic row-level lock for the UpdateByID path. Concurrent
// callers block here until the holding tx commits/rolls back. Returns
// ErrNoRows (→ batch.ErrNotFound) on missing or soft-deleted rows —
// same visibility filter as GetBatchByID.
func (q *Queries) LockBatchForUpdate(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBatchForUpdate, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateBatchWithVersionCheck = `-- name: UpdateBatchWithVersionCheck :execrows
UPDATE inventory.batches
SET    quantity_on_hand = $2,
       version          = $3,
       updated_at       = $4,
       is_deleted       = $5,
       deleted_at       = $6,
       deleted_by       = $7,
       batch_number     = $8,
       manufacturer_name = $9,
       manufacturing_licence_number = $10
WHERE  id = $1
AND    version = $11
`

type UpdateBatchWithVersionCheckParams struct {
	ID                         pgtype.UUID
	QuantityOnHand             int64
	Version                    int64
	UpdatedAt                  pgtype.Timestamptz
	IsDeleted                  bool
	DeletedAt                  pgtype.Timestamptz
	DeletedBy                  *string
	BatchNumber                string
	ManufacturerName           string
	ManufacturingLicenceNumber string
	VersionExpected            int64
}

// Optimistic-concurrency UPDATE. Returns rows-affected so the adapter
// can branch on 0 → ErrConcurrencyConflict. The `version = $11`
// predicate is the load-bearing concurrency token; `version + 1` ships
// the bumped value back.
func (q *Queries) UpdateBatchWithVersionCheck(ctx context.Context, arg UpdateBatchWithVersionCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBatchWithVersionCheck,
		arg.ID,
		arg.QuantityOnHand,
		arg.Version,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.DeletedBy,
		arg.BatchNumber,
		arg.ManufacturerName,
		arg.ManufacturingLicenceNumber,
		arg.VersionExpected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
