// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryProduct struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Sku          string
	Name         string
	DosageForm   string
	PackSize     string
	HsnCode      string
	GstRateBps   int32
	Manufacturer string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsDeleted    bool
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *string
}

type InventoryBatch struct {
	ID                         pgtype.UUID
	ProductID                  pgtype.UUID
	TenantID                   pgtype.UUID
	BatchNumber                string
	ManufactureDate            pgtype.Date
	ExpiryDate                 pgtype.Date
	ManufacturerName           string
	ManufacturingLicenceNumber string
	MrpPaise                   int64
	PurchasePricePaise         int64
	QuantityOnHand             int64
	Version                    int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	IsDeleted                  bool
	DeletedAt                  pgtype.Timestamptz
	DeletedBy                  *string
}

type InventoryStockMovement struct {
	ID                  pgtype.UUID
	BatchID             pgtype.UUID
	ProductID           pgtype.UUID
	TenantID            pgtype.UUID
	Type                string
	Quantity            int64
	QuantityOnHandAfter int64
	Reason              string
	ActorMembershipID   pgtype.UUID
	SourceReference     *string
	OccurredAt          pgtype.Timestamptz
}

type InventoryOutbox struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	Forwarded     bool
	ForwardedAt   pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}
