// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO inventory.outbox (
    id, tenant_id, topic, payload, occurred_at,
    act_operator_id, act_session_id, act_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Outbox queries — inventory.outbox is RLS+FORCE per ADR 0027 ("outbox
// table doubles as audit log"). Insert happens inside the same tx as
// aggregate state. Forwarder runs under platform-bypass to drain.
// act_operator_id / act_session_id / act_reason carry impersonation
// context (RFC 8693 act claim) per ADR 0056. NULL for non-impersonation
// events; populated when the emitting handler ran under a scoped JWT.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.Topic,
		arg.Payload,
		arg.OccurredAt,
		arg.ActOperatorID,
		arg.ActSessionID,
		arg.ActReason,
	)
	return err
}

const listUnforwardedOutboxEvents = `-- name: ListUnforwardedOutboxEvents :many
SELECT id, tenant_id, topic, payload, occurred_at, created_at,
       forwarded, forwarded_at,
       act_operator_id, act_session_id, act_reason
FROM   inventory.outbox
WHERE  forwarded = false
ORDER  BY created_at, id
LIMIT  $1
FOR    UPDATE SKIP LOCKED
`

// Forwarder polls this. Caller MUST run under app.is_platform=true so
// RLS policy inventory_outbox_select returns rows from every tenant.
//
// FOR UPDATE SKIP LOCKED (Postgres 9.5+) lets multiple forwarder
// replicas drain the outbox concurrently without double-publishing.
// Mirror of identity's outbox.sql shape (Brandur Leach "Transactionally
// staged job drains in Postgres" + river-queue canon).
func (q *Queries) ListUnforwardedOutboxEvents(ctx context.Context, limit int32) ([]InventoryOutbox, error) {
	rows, err := q.db.Query(ctx, listUnforwardedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryOutbox
	for rows.Next() {
		var i InventoryOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Forwarded,
			&i.ForwardedAt,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventForwarded = `-- name: MarkOutboxEventForwarded :exec
UPDATE inventory.outbox
SET    forwarded    = true,
       forwarded_at = $2
WHERE  id = $1
`

type MarkOutboxEventForwardedParams struct {
	ID          pgtype.UUID
	ForwardedAt pgtype.Timestamptz
}

// Forwarder writes this AFTER successful publish to the broker. Policy
// inventory_outbox_modify requires app.is_platform=true.
func (q *Queries) MarkOutboxEventForwarded(ctx context.Context, arg MarkOutboxEventForwardedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventForwarded, arg.ID, arg.ForwardedAt)
	return err
}
