// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO inventory.outbox (
    id, tenant_id, topic, payload, occurred_at,
    act_operator_id, act_session_id, act_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID, arg.TenantID, arg.Topic, arg.Payload, arg.OccurredAt,
		arg.ActOperatorID, arg.ActSessionID, arg.ActReason,
	)
	return err
}
