// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
       gst_rate_bps, manufacturer, is_active,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by, created_by_membership_id
FROM   inventory.products
WHERE  id = $1
AND    NOT is_deleted
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (InventoryProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i InventoryProduct
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sku,
		&i.Name,
		&i.DosageForm,
		&i.PackSize,
		&i.HsnCode,
		&i.GstRateBps,
		&i.Manufacturer,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :exec

INSERT INTO inventory.products (
    id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
    gst_rate_bps, manufacturer, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12
)
`

type InsertProductParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Sku          string
	Name         string
	DosageForm   string
	PackSize     string
	HsnCode      string
	GstRateBps   int32
	Manufacturer string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Product queries — inventory.products is tenant-scoped + RLS-FORCE.
// All reads/writes run under TxScopeTenant — the `app.tenant_id` GUC
// is bound by pgxpool's AfterAcquire, then Postgres RLS does the
// filter. Cross-tenant access surfaces as "row missing" (ErrNotFound).
func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.Exec(ctx, insertProduct,
		arg.ID,
		arg.TenantID,
		arg.Sku,
		arg.Name,
		arg.DosageForm,
		arg.PackSize,
		arg.HsnCode,
		arg.GstRateBps,
		arg.Manufacturer,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listProductsByTenantPage = `-- name: ListProductsByTenantPage :many
SELECT id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
       gst_rate_bps, manufacturer, is_active,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by, created_by_membership_id
FROM   inventory.products
WHERE  tenant_id = $1
AND    NOT is_deleted
AND    (NOT $2::boolean OR is_active = true)
AND    (
        $3::text = ''
        OR (lower(sku) || ' ' || lower(name)) ILIKE '%' || lower($3) || '%'
       )
AND    (created_at, id) < ($4::timestamptz, $5::uuid)
ORDER  BY created_at DESC, id DESC
LIMIT  $6
`

type ListProductsByTenantPageParams struct {
	TenantID        pgtype.UUID
	ActiveOnly      bool
	Search          string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	Limit           int32
}

// Cursor-paginated list per ADR 0038. Keyset on (created_at, id) DESC.
// The cursor's `$2` = sort_value (created_at), `$3` = id; first page
// supplies (clock-max-future, max-uuid) so the predicate matches everything.
// $4 = active_only flag. $5 = search predicate (empty = no filter).
// $6 = page_size + 1 (peek-one-extra per pagination.BuildPage).
func (q *Queries) ListProductsByTenantPage(ctx context.Context, arg ListProductsByTenantPageParams) ([]InventoryProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByTenantPage,
		arg.TenantID,
		arg.ActiveOnly,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryProduct
	for rows.Next() {
		var i InventoryProduct
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sku,
			&i.Name,
			&i.DosageForm,
			&i.PackSize,
			&i.HsnCode,
			&i.GstRateBps,
			&i.Manufacturer,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE inventory.products
SET    is_deleted = true,
       deleted_at = $2,
       deleted_by = $3,
       updated_at = $4
WHERE  id = $1
AND    NOT is_deleted
`

type SoftDeleteProductParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct,
		arg.ID,
		arg.DeletedAt,
		arg.DeletedBy,
		arg.UpdatedAt,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE inventory.products
SET    name         = $2,
       gst_rate_bps = $3,
       manufacturer = $4,
       is_active    = $5,
       updated_at   = $6
WHERE  id = $1
AND    NOT is_deleted
`

type UpdateProductParams struct {
	ID           pgtype.UUID
	Name         string
	GstRateBps   int32
	Manufacturer string
	IsActive     bool
	UpdatedAt    pgtype.Timestamptz
}

// General-purpose update covering Product.Update mutator + SoftDelete.
// The aggregate persists ALL its current state on every write; the
// repo doesn't try to compute a partial UPDATE.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.GstRateBps,
		arg.Manufacturer,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
