// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO inventory.products (
    id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
    gst_rate_bps, manufacturer, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12
)`

type InsertProductParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Sku          string
	Name         string
	DosageForm   string
	PackSize     string
	HsnCode      string
	GstRateBps   int32
	Manufacturer string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.Exec(ctx, insertProduct,
		arg.ID,
		arg.TenantID,
		arg.Sku,
		arg.Name,
		arg.DosageForm,
		arg.PackSize,
		arg.HsnCode,
		arg.GstRateBps,
		arg.Manufacturer,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
       gst_rate_bps, manufacturer, is_active,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by
FROM   inventory.products
WHERE  id = $1
AND    NOT is_deleted`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (InventoryProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i InventoryProduct
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Sku, &i.Name, &i.DosageForm, &i.PackSize, &i.HsnCode,
		&i.GstRateBps, &i.Manufacturer, &i.IsActive,
		&i.CreatedAt, &i.UpdatedAt,
		&i.IsDeleted, &i.DeletedAt, &i.DeletedBy,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE inventory.products
SET    name         = $2,
       gst_rate_bps = $3,
       manufacturer = $4,
       is_active    = $5,
       updated_at   = $6
WHERE  id = $1
AND    NOT is_deleted`

type UpdateProductParams struct {
	ID           pgtype.UUID
	Name         string
	GstRateBps   int32
	Manufacturer string
	IsActive     bool
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID, arg.Name, arg.GstRateBps, arg.Manufacturer, arg.IsActive, arg.UpdatedAt,
	)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE inventory.products
SET    is_deleted = true,
       deleted_at = $2,
       deleted_by = $3,
       updated_at = $4
WHERE  id = $1
AND    NOT is_deleted`

type SoftDeleteProductParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.DeletedAt, arg.DeletedBy, arg.UpdatedAt)
	return err
}

const listProductsByTenantPage = `-- name: ListProductsByTenantPage :many
SELECT id, tenant_id, sku, name, dosage_form, pack_size, hsn_code,
       gst_rate_bps, manufacturer, is_active,
       created_at, updated_at,
       is_deleted, deleted_at, deleted_by
FROM   inventory.products
WHERE  tenant_id = $1
AND    NOT is_deleted
AND    (NOT $4::boolean OR is_active = true)
AND    (
        $5::text = ''
        OR (lower(sku) || ' ' || lower(name)) ILIKE '%' || lower($5) || '%'
       )
AND    (created_at, id) < ($2, $3)
ORDER  BY created_at DESC, id DESC
LIMIT  $6`

type ListProductsByTenantPageParams struct {
	TenantID         pgtype.UUID
	CursorCreatedAt  pgtype.Timestamptz
	CursorID         pgtype.UUID
	ActiveOnly       bool
	Search           string
	Limit            int32
}

func (q *Queries) ListProductsByTenantPage(ctx context.Context, arg ListProductsByTenantPageParams) ([]InventoryProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByTenantPage,
		arg.TenantID, arg.CursorCreatedAt, arg.CursorID, arg.ActiveOnly, arg.Search, arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryProduct
	for rows.Next() {
		var i InventoryProduct
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.Sku, &i.Name, &i.DosageForm, &i.PackSize, &i.HsnCode,
			&i.GstRateBps, &i.Manufacturer, &i.IsActive,
			&i.CreatedAt, &i.UpdatedAt,
			&i.IsDeleted, &i.DeletedAt, &i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
