// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_movements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStockMovementByID = `-- name: GetStockMovementByID :one
SELECT id, batch_id, product_id, tenant_id,
       type, quantity, quantity_on_hand_after,
       reason, actor_membership_id, source_reference,
       occurred_at
FROM   inventory.stock_movements
WHERE  id = $1
`

func (q *Queries) GetStockMovementByID(ctx context.Context, id pgtype.UUID) (InventoryStockMovement, error) {
	row := q.db.QueryRow(ctx, getStockMovementByID, id)
	var i InventoryStockMovement
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProductID,
		&i.TenantID,
		&i.Type,
		&i.Quantity,
		&i.QuantityOnHandAfter,
		&i.Reason,
		&i.ActorMembershipID,
		&i.SourceReference,
		&i.OccurredAt,
	)
	return i, err
}

const insertStockMovement = `-- name: InsertStockMovement :exec

INSERT INTO inventory.stock_movements (
    id, batch_id, product_id, tenant_id,
    type, quantity, quantity_on_hand_after,
    reason, actor_membership_id, source_reference,
    occurred_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11
)
`

type InsertStockMovementParams struct {
	ID                  pgtype.UUID
	BatchID             pgtype.UUID
	ProductID           pgtype.UUID
	TenantID            pgtype.UUID
	Type                string
	Quantity            int64
	QuantityOnHandAfter int64
	Reason              string
	ActorMembershipID   pgtype.UUID
	SourceReference     *string
	OccurredAt          pgtype.Timestamptz
}

// StockMovement queries — inventory.stock_movements is tenant-scoped +
// RLS-FORCE. Append-only ledger: NO UPDATE, NO DELETE queries.
func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ID,
		arg.BatchID,
		arg.ProductID,
		arg.TenantID,
		arg.Type,
		arg.Quantity,
		arg.QuantityOnHandAfter,
		arg.Reason,
		arg.ActorMembershipID,
		arg.SourceReference,
		arg.OccurredAt,
	)
	return err
}

const listMovementsByBatchPage = `-- name: ListMovementsByBatchPage :many
SELECT id, batch_id, product_id, tenant_id,
       type, quantity, quantity_on_hand_after,
       reason, actor_membership_id, source_reference,
       occurred_at
FROM   inventory.stock_movements
WHERE  batch_id = $1
AND    ($2::text = '' OR type = $2)
AND    (occurred_at, id) < ($3::timestamptz, $4::uuid)
ORDER  BY occurred_at DESC, id DESC
LIMIT  $5
`

type ListMovementsByBatchPageParams struct {
	BatchID          pgtype.UUID
	Type             string
	CursorOccurredAt pgtype.Timestamptz
	CursorID         pgtype.UUID
	Limit            int32
}

// Cursor-paginated ledger read per ADR 0038. Keyset on (occurred_at, id) DESC.
// $4 = type filter (empty = no filter).
// $5 = page_size + 1 (peek-one-extra).
func (q *Queries) ListMovementsByBatchPage(ctx context.Context, arg ListMovementsByBatchPageParams) ([]InventoryStockMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByBatchPage,
		arg.BatchID,
		arg.Type,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryStockMovement
	for rows.Next() {
		var i InventoryStockMovement
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ProductID,
			&i.TenantID,
			&i.Type,
			&i.Quantity,
			&i.QuantityOnHandAfter,
			&i.Reason,
			&i.ActorMembershipID,
			&i.SourceReference,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
