// sqlc_arch_test.go — Principle A: sqlc + pgx discipline.
//
// ADR 0004 (sqlc + pgx/v5 + squirrel + goose) pins the data-layer
// canon. These tests mechanically enforce the canon at PR time:
//
//   - every `-- name: X :Y` query uses one of sqlc's canonical
//     annotations (no typos that silently regenerate as zero-method
//     queries);
//   - no `SELECT *` (Brandur / sqlc README anti-pattern; column-add
//     migrations would silently break callers);
//   - generated files are not hand-edited (sqlc header marker check);
//   - every named query has a Go caller (drift gate);
//   - every sqlc target declares `sql_package: pgx/v5`;
//   - raw `pgx.Conn.Exec/Query` outside the substrate package is
//     banned (must go through sqlc-generated or `pg.UnitOfWork`);
//   - Squirrel builders use $-placeholders (not ?);
//   - no `fmt.Sprintf` building SQL fragments outside test code.
//
// Cited canon:
//   - Brandur Leach — "sqlc + pgx production at scale" (Crunchy Bridge).
//   - sqlc README — canonical annotation set (one/many/exec/...).
//   - river-queue / Crunchy Bridge — generated code in dedicated `db` pkg.
//   - ADR 0004 — locked stack choice.

package architecture_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// ----------------------------------------------------------------------------
// A1: TestArch_SqlcQueryAnnotationsCanonical
// ----------------------------------------------------------------------------
//
// Every `-- name: X :Y` declaration in .sql files under any
// `<module>/adapters/sql/` directory must use a canonical sqlc
// annotation. Typos (`:onee`, `:execute`) silently regenerate as
// zero-method queries — they pass the build then explode at runtime.
//
// Closes a drift-class bug rather than a security gap.
func TestArch_SqlcQueryAnnotationsCanonical(t *testing.T) {
	t.Parallel()

	canonical := map[string]struct{}{
		"one": {}, "many": {}, "exec": {}, "execrows": {},
		"batchone": {}, "batchmany": {}, "execresult": {},
		"copyfrom": {},
	}
	nameRE := regexp.MustCompile(`(?m)^--\s*name:\s+\w+\s+:(\w+)\s*$`)

	root := internalDir(t)
	var bad []string

	for _, mod := range modulesUnderInternal(t) {
		sqlDir := filepath.Join(root, mod, "adapters", "sql")
		if _, err := os.Stat(sqlDir); err != nil {
			continue
		}
		walkFilesByExt(t, sqlDir, ".sql", func(path string, src []byte) {
			for _, m := range nameRE.FindAllStringSubmatch(string(src), -1) {
				ann := strings.ToLower(m[1])
				if _, ok := canonical[ann]; !ok {
					bad = append(bad, path+": :"+ann)
				}
			}
		})
	}

	if len(bad) > 0 {
		t.Fatalf("sqlc query uses non-canonical annotation (sqlc README §Query annotations):\n  %s",
			strings.Join(bad, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A2: TestArch_NoSelectStarInSqlc
// ----------------------------------------------------------------------------
//
// `SELECT *` in sqlc queries is an anti-pattern: column-add migrations
// silently change the row type, breaking the generated Go struct in
// unpredictable ways. Brandur / sqlc README canon: list columns
// explicitly.
//
// Allow-list: queries that wrap with COUNT(*) / EXISTS(SELECT *) /
// SELECT 1 are NOT flagged — the asterisk there is the aggregate's
// abstract row, not a column-list shortcut.
func TestArch_NoSelectStarInSqlc(t *testing.T) {
	t.Parallel()

	// Match `SELECT *` (case-insensitive, possibly preceded by whitespace
	// at column 1 or after newline). Explicitly do NOT match COUNT(*) /
	// EXISTS(SELECT *) which are legitimate aggregate constructs.
	starRE := regexp.MustCompile(`(?i)(?:^|\n)\s*SELECT\s+\*`)

	root := internalDir(t)
	var bad []string

	for _, mod := range modulesUnderInternal(t) {
		sqlDir := filepath.Join(root, mod, "adapters", "sql")
		if _, err := os.Stat(sqlDir); err != nil {
			continue
		}
		walkFilesByExt(t, sqlDir, ".sql", func(path string, src []byte) {
			body := stripSQLComments(string(src))
			if starRE.MatchString(body) {
				bad = append(bad, pathToSlash(path))
			}
		})
	}

	if len(bad) > 0 {
		t.Fatalf("sqlc query uses SELECT * — list columns explicitly (Brandur / sqlc README):\n  %s",
			strings.Join(bad, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A3: TestArch_SqlcGeneratedCodeUnchanged
// ----------------------------------------------------------------------------
//
// Files under `<module>/adapters/db/*.sql.go` are sqlc output. They
// must carry the canonical header `// Code generated by sqlc. DO NOT
// EDIT.` Heuristic check; the helper walker also skips these files
// from most other tests via the "Code generated" sentinel.
func TestArch_SqlcGeneratedCodeUnchanged(t *testing.T) {
	t.Parallel()

	root := internalDir(t)
	var missing []string

	for _, mod := range modulesUnderInternal(t) {
		dbDir := filepath.Join(root, mod, "adapters", "db")
		if _, err := os.Stat(dbDir); err != nil {
			continue
		}
		entries, err := os.ReadDir(dbDir)
		if err != nil {
			t.Fatalf("read %s: %v", dbDir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
				continue
			}
			path := filepath.Join(dbDir, e.Name())
			src, rerr := os.ReadFile(path)
			if rerr != nil {
				t.Fatalf("read %s: %v", path, rerr)
			}
			head := string(src)
			if len(head) > 512 {
				head = head[:512]
			}
			if !strings.Contains(head, "Code generated by sqlc") ||
				!strings.Contains(head, "DO NOT EDIT") {
				missing = append(missing, pathToSlash(path))
			}
		}
	}

	if len(missing) > 0 {
		t.Fatalf("sqlc-generated file missing canonical `Code generated by sqlc. DO NOT EDIT.` header (manual edits forbidden — regen via task sqlc):\n  %s",
			strings.Join(missing, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A4: TestArch_EveryNamedQueryHasGoCaller
// ----------------------------------------------------------------------------
//
// Every `-- name: Foo :one` declaration must have at least one
// `q.Foo(` (or `queries.Foo(`) call in the corresponding adapter
// package. Dead queries accumulate as untested DB code; closing the
// gap forces removal or use.
//
// Heuristic: greps adapter package (.go files in
// `<module>/adapters/`) for `.<Name>(`. False-positives are rare
// (sqlc names are PascalCase + business-domain-specific).
// Scope: production — applies to non-test files; test-side discipline lives under Principle TD/TP.
func TestArch_EveryNamedQueryHasGoCaller(t *testing.T) {
	t.Parallel()

	// Allow-list: queries kept in the catalog ahead of their consumer
	// landing. Each entry must be removed once the consumer ships.
	allow := map[string]struct{}{
		// Identity: predates the SecurityStamp-aware login path; called
		// only by an upcoming session-renewal handler. Tracked in
		// KNOWN_VIOLATIONS.md "queries-without-callers" section.
		"GetActiveMembershipByPersonAndTenant": {},
		// Outbox: backs the planned admin "raw audit-log" inspector
		// endpoint (currently AuditReader serves the JSON-projected
		// shape). Tracked in KNOWN_VIOLATIONS.md.
		"ListAuditEventsForTenant": {},
	}

	nameRE := regexp.MustCompile(`(?m)^--\s*name:\s+(\w+)\s+:\w+\s*$`)
	root := internalDir(t)

	type queryRef struct {
		name string
		mod  string
		path string
	}

	var queries []queryRef
	for _, mod := range modulesUnderInternal(t) {
		sqlDir := filepath.Join(root, mod, "adapters", "sql")
		if _, err := os.Stat(sqlDir); err != nil {
			continue
		}
		walkFilesByExt(t, sqlDir, ".sql", func(path string, src []byte) {
			for _, m := range nameRE.FindAllStringSubmatch(string(src), -1) {
				queries = append(queries, queryRef{name: m[1], mod: mod, path: path})
			}
		})
	}

	// Index adapter source per module (the whole adapters/ tree,
	// excluding the generated db/ subdir).
	adapterSrcByMod := map[string]string{}
	for _, mod := range modulesUnderInternal(t) {
		adapterDir := filepath.Join(root, mod, "adapters")
		if _, err := os.Stat(adapterDir); err != nil {
			continue
		}
		var b strings.Builder
		walkGoFiles(t, adapterDir, false, func(path string, src []byte) {
			// Skip the generated db/ subdirectory; we want to verify
			// that hand-written adapters CALL the generated wrappers.
			if strings.Contains(pathToSlash(path), "/adapters/db/") {
				return
			}
			b.Write(src)
			b.WriteString("\n")
		})
		adapterSrcByMod[mod] = b.String()
	}

	var dead []string
	for _, q := range queries {
		if _, ok := allow[q.name]; ok {
			continue
		}
		src := adapterSrcByMod[q.mod]
		if !strings.Contains(src, "."+q.name+"(") {
			dead = append(dead, q.mod+"/"+q.name+" (in "+filepath.Base(q.path)+")")
		}
	}

	if len(dead) > 0 {
		t.Fatalf("sqlc query has no Go caller — delete or wire it up (ADR 0004 dead-query gate):\n  %s",
			strings.Join(dead, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A5: TestArch_SqlcConfigUsesPgxV5
// ----------------------------------------------------------------------------
//
// Every target in sqlc.yaml must declare `sql_package: pgx/v5`. ADR
// 0004 locks pgx/v5 as the DB driver; allowing pgx/v4 or database/sql
// targets would split the connection-pool world.
func TestArch_SqlcConfigUsesPgxV5(t *testing.T) {
	t.Parallel()

	path := filepath.Join(repoRoot(t), "sqlc.yaml")
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read sqlc.yaml: %v", err)
	}
	body := string(src)

	// Count targets via the `out:` directive (one per target).
	outCount := strings.Count(body, "\n        out:") + strings.Count(body, "\n    out:")
	if outCount == 0 {
		t.Fatal("sqlc.yaml has no `out:` directives — config malformed")
	}
	pgxCount := strings.Count(body, "sql_package: pgx/v5")
	if pgxCount < outCount {
		t.Fatalf("sqlc.yaml: %d target(s) but only %d sql_package: pgx/v5 declarations (ADR 0004 locks pgx/v5)",
			outCount, pgxCount)
	}
}

// ----------------------------------------------------------------------------
// A6: TestArch_NoRawPgxConnExec
// ----------------------------------------------------------------------------
//
// Direct `pgx.Conn` use (vs `pgxpool.Pool` + the sqlc/UoW substrate)
// is banned outside `internal/common/pg/`. Callers must go through
// the pool + the canonical Transactor.
//
// Detects literal `pgx.Conn` identifier usage in non-substrate
// production code.
// Scope: production — applies to non-test files; test-side discipline lives under Principle TD/TP.
func TestArch_NoRawPgxConnExec(t *testing.T) {
	t.Parallel()

	root := internalDir(t)
	var bad []string

	for _, mod := range append(modulesUnderInternal(t), "common") {
		modDir := filepath.Join(root, mod)
		walkGoFiles(t, modDir, false, func(path string, src []byte) {
			slash := pathToSlash(path)
			// Substrate package is allowed.
			if strings.Contains(slash, "/common/pg/") {
				return
			}
			// Generated sqlc code is allowed (it uses pgx types internally
			// via DBTX interface; the walker already skips generated
			// files, but the db/ dir is explicit here too).
			if strings.Contains(slash, "/adapters/db/") {
				return
			}
			body := stripGoComments(string(src))
			if strings.Contains(body, "pgx.Conn") {
				bad = append(bad, slash)
			}
		})
	}

	if len(bad) > 0 {
		t.Fatalf("direct pgx.Conn use outside common/pg/ — go through pgxpool.Pool + Transactor (ADR 0004):\n  %s",
			strings.Join(bad, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A7: TestArch_SquirrelUsesDollarPlaceholder
// ----------------------------------------------------------------------------
//
// Postgres uses $-placeholders ($1, $2). Squirrel defaults to ?, so
// every StatementBuilder construction MUST chain
// `.PlaceholderFormat(sq.Dollar)`. Missing this turns into a runtime
// "syntax error at or near $1" 50ms before the query runs.
//
// Heuristic: any file importing squirrel must mention `sq.Dollar`
// somewhere.
// Scope: production — applies to non-test files; test-side discipline lives under Principle TD/TP.
func TestArch_SquirrelUsesDollarPlaceholder(t *testing.T) {
	t.Parallel()

	root := internalDir(t)
	var bad []string

	for _, mod := range append(modulesUnderInternal(t), "common") {
		modDir := filepath.Join(root, mod)
		walkGoFiles(t, modDir, false, func(path string, src []byte) {
			imports := parseImports(t, path, src)
			usesSquirrel := false
			for _, im := range imports {
				if strings.Contains(im, "squirrel") {
					usesSquirrel = true
					break
				}
			}
			if !usesSquirrel {
				return
			}
			body := stripGoComments(string(src))
			if !strings.Contains(body, "sq.Dollar") &&
				!strings.Contains(body, "squirrel.Dollar") {
				bad = append(bad, pathToSlash(path))
			}
		})
	}

	if len(bad) > 0 {
		t.Fatalf("file imports squirrel but doesn't configure PlaceholderFormat(sq.Dollar) — Postgres expects $1 not ?:\n  %s",
			strings.Join(bad, "\n  "))
	}
}

// ----------------------------------------------------------------------------
// A8: TestArch_NoStringInterpInSQLConstruction
// ----------------------------------------------------------------------------
//
// No `fmt.Sprintf("... SELECT %s ...", ...)` building SQL fragments
// outside test files. SQL composition must go through Squirrel
// builders (parameterised) or sqlc (compile-time-typed). Even when
// the inputs are "safe" (column names from constants), Sprintf'd SQL
// is an OWASP A03 (Injection) bug-magnet pattern.
//
// Heuristic: looks for `fmt.Sprintf(` calls whose first arg contains
// SQL-keyword literal patterns in non-test files under adapters/.
// Scope: production — applies to non-test files; test-side discipline lives under Principle TD/TP.
func TestArch_NoStringInterpInSQLConstruction(t *testing.T) {
	t.Parallel()

	sqlKw := regexp.MustCompile(`(?i)\b(SELECT|INSERT|UPDATE|DELETE|WHERE|FROM|JOIN|UNION)\b`)
	// Strict: only `fmt.Sprintf(\"...SQL keyword..."`. We rely on the
	// arg being a string literal on the same line as Sprintf (canonical
	// gofmt layout).
	sprintfLine := regexp.MustCompile(`(?i)fmt\.Sprintf\(\s*"([^"]*)"`)

	root := internalDir(t)
	var bad []string

	for _, mod := range append(modulesUnderInternal(t), "common") {
		modDir := filepath.Join(root, mod)
		walkGoFiles(t, modDir, false, func(path string, src []byte) {
			slash := pathToSlash(path)
			// Allow the generated db/ subdir and any code that
			// explicitly opts out (e.g. EXPLAIN ANALYZE harness).
			if strings.Contains(slash, "/adapters/db/") {
				return
			}
			body := stripGoComments(string(src))
			for _, m := range sprintfLine.FindAllStringSubmatch(body, -1) {
				fmtStr := m[1]
				if sqlKw.MatchString(fmtStr) {
					bad = append(bad, slash+": Sprintf with SQL fragment "+truncate(fmtStr, 60))
				}
			}
		})
	}

	if len(bad) > 0 {
		t.Fatalf("fmt.Sprintf building SQL fragments — use Squirrel builders or sqlc (OWASP A03 + ADR 0004):\n  %s",
			strings.Join(bad, "\n  "))
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
