// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditEventsByTenantPage = `-- name: ListAuditEventsByTenantPage :many

SELECT id, action, user_id, tenant_id, correlation_id,
       occurred_at_utc, duration_ms, succeeded, failure_reason, payload,
       act_operator_id, act_session_id, act_reason
FROM   buildingblocks.audit_log_entry
WHERE  tenant_id = $1
AND    (occurred_at_utc, id) < ($2::timestamptz, $3::uuid)
ORDER  BY occurred_at_utc DESC, id DESC
LIMIT  $4
`

type ListAuditEventsByTenantPageParams struct {
	TenantID       pgtype.UUID
	BeforeOccurred pgtype.Timestamptz
	BeforeID       pgtype.UUID
	Limit          int32
}

// Audit-log read queries — buildingblocks.audit_log_entry.
//
// The table is auto-written per command by the Watermill
// AuditLoggingMiddleware (per ADR 0027 outbox-doubles-as-audit + the
// additive buildingblocks audit table from migration
// 20260507000001). Reads here are operator-facing — keyset paginated
// per ADR 0038 + filtered by tenant_id / user_id / action.
//
// Cross-tenant queries run under TxScopePlatform (the table has no
// RLS); per-tenant queries also run under platform scope so the
// handler explicitly authorises before dispatching.
// Keyset-paginated tenant-scoped events. Backed by
// idx_audit_log_entry_tenant_occurred (tenant_id, occurred_at_utc DESC)
// WHERE tenant_id IS NOT NULL.
//
// Cursor predicate: (occurred_at_utc, id) < ($2, $3) for tuple tie-
// break. First page sentinel: future timestamp + max UUID.
func (q *Queries) ListAuditEventsByTenantPage(ctx context.Context, arg ListAuditEventsByTenantPageParams) ([]BuildingblocksAuditLogEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTenantPage,
		arg.TenantID,
		arg.BeforeOccurred,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildingblocksAuditLogEntry
	for rows.Next() {
		var i BuildingblocksAuditLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.UserID,
			&i.TenantID,
			&i.CorrelationID,
			&i.OccurredAtUtc,
			&i.DurationMs,
			&i.Succeeded,
			&i.FailureReason,
			&i.Payload,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByUserPage = `-- name: ListAuditEventsByUserPage :many
SELECT id, action, user_id, tenant_id, correlation_id,
       occurred_at_utc, duration_ms, succeeded, failure_reason, payload,
       act_operator_id, act_session_id, act_reason
FROM   buildingblocks.audit_log_entry
WHERE  user_id = $1
AND    (occurred_at_utc, id) < ($2::timestamptz, $3::uuid)
ORDER  BY occurred_at_utc DESC, id DESC
LIMIT  $4
`

type ListAuditEventsByUserPageParams struct {
	UserID         pgtype.UUID
	BeforeOccurred pgtype.Timestamptz
	BeforeID       pgtype.UUID
	Limit          int32
}

// Keyset-paginated user-scoped events. Backed by
// idx_audit_log_entry_user_occurred (user_id, occurred_at_utc DESC)
// WHERE user_id IS NOT NULL.
func (q *Queries) ListAuditEventsByUserPage(ctx context.Context, arg ListAuditEventsByUserPageParams) ([]BuildingblocksAuditLogEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByUserPage,
		arg.UserID,
		arg.BeforeOccurred,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildingblocksAuditLogEntry
	for rows.Next() {
		var i BuildingblocksAuditLogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.UserID,
			&i.TenantID,
			&i.CorrelationID,
			&i.OccurredAtUtc,
			&i.DurationMs,
			&i.Succeeded,
			&i.FailureReason,
			&i.Payload,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
