// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePermissionOverridesByMembership = `-- name: DeletePermissionOverridesByMembership :exec
DELETE FROM identity.membership_permission_overrides
WHERE  membership_id = $1
`

func (q *Queries) DeletePermissionOverridesByMembership(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissionOverridesByMembership, membershipID)
	return err
}

const deleteRoleAssignmentsByMembership = `-- name: DeleteRoleAssignmentsByMembership :exec
DELETE FROM identity.role_assignments
WHERE  membership_id = $1
`

// Full clear. UpdateByID's persist step uses this + per-role InsertRoleAssignment
// to project the aggregate's current RoleAssignments slice (replace-all
// semantics â€” simpler than per-row diff tracking, idempotent).
func (q *Queries) DeleteRoleAssignmentsByMembership(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoleAssignmentsByMembership, membershipID)
	return err
}

const getActiveMembershipByPersonAndTenant = `-- name: GetActiveMembershipByPersonAndTenant :one
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to,
       created_by_membership_id
FROM   identity.tenant_memberships
WHERE  person_id = $1
  AND  tenant_id = $2
  AND  status    = 'active'
`

type GetActiveMembershipByPersonAndTenantParams struct {
	PersonID pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) GetActiveMembershipByPersonAndTenant(ctx context.Context, arg GetActiveMembershipByPersonAndTenantParams) (IdentityTenantMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByPersonAndTenant, arg.PersonID, arg.TenantID)
	var i IdentityTenantMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Designation,
		&i.Department,
		&i.StatusMessage,
		&i.ReportsTo,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to,
       created_by_membership_id
FROM   identity.tenant_memberships
WHERE  id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id pgtype.UUID) (IdentityTenantMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i IdentityTenantMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Designation,
		&i.Department,
		&i.StatusMessage,
		&i.ReportsTo,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :exec

INSERT INTO identity.tenant_memberships (
    id, person_id, tenant_id, status, joined_at, created_by_membership_id
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMembershipParams struct {
	ID                    pgtype.UUID
	PersonID              pgtype.UUID
	TenantID              pgtype.UUID
	Status                string
	JoinedAt              pgtype.Timestamptz
	CreatedByMembershipID pgtype.UUID
}

// Membership queries â€” identity.tenant_memberships is RLS+FORCE.
// Reads through this query path see only the current tenant's rows
// unless app.is_platform=true. Cross-tenant login resolution goes
// through GetPersonAndActiveMembershipByEmail (in persons.sql) under
// TxScopePlatform â€” single-roundtrip JOIN against the partial-unique
// index uq_memberships_person_active.
// created_by_membership_id is the audit chain â€” who invited this
// user. NULL for self-bootstrapped paths (RegisterTenant first
// admin, SuperAdmin via cmd/bootstrap). Composite FK to
// (id, tenant_id) prevents cross-tenant audit-chain spoofing per
// migration 20260507000008.
func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership,
		arg.ID,
		arg.PersonID,
		arg.TenantID,
		arg.Status,
		arg.JoinedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const insertPermissionOverride = `-- name: InsertPermissionOverride :exec
INSERT INTO identity.membership_permission_overrides (
    membership_id, permission_name, kind, tenant_id, updated_at
) VALUES ($1, $2, $3, $4, $5)
`

type InsertPermissionOverrideParams struct {
	MembershipID   pgtype.UUID
	PermissionName string
	Kind           string
	TenantID       pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

// Per-Membership permission overlay. kind âˆˆ {'granted', 'revoked'} â€”
// the domain layer guarantees a permission_name appears at most once
// per Membership (see Membership.GrantPermission / RevokePermission
// auto-suppression).
func (q *Queries) InsertPermissionOverride(ctx context.Context, arg InsertPermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, insertPermissionOverride,
		arg.MembershipID,
		arg.PermissionName,
		arg.Kind,
		arg.TenantID,
		arg.UpdatedAt,
	)
	return err
}

const insertRoleAssignment = `-- name: InsertRoleAssignment :exec
INSERT INTO identity.role_assignments (
    membership_id, role_id, tenant_id, assigned_at
) VALUES ($1, $2, $3, $4)
`

type InsertRoleAssignmentParams struct {
	MembershipID pgtype.UUID
	RoleID       pgtype.UUID
	TenantID     pgtype.UUID
	AssignedAt   pgtype.Timestamptz
}

// Junction row. Caller MUST guarantee role.tenant_id == membership.tenant_id;
// the composite FK on (membership_id, tenant_id) â†’ tenant_memberships(id, tenant_id)
// enforces this at the schema level.
func (q *Queries) InsertRoleAssignment(ctx context.Context, arg InsertRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertRoleAssignment,
		arg.MembershipID,
		arg.RoleID,
		arg.TenantID,
		arg.AssignedAt,
	)
	return err
}

const listMembershipsForPerson = `-- name: ListMembershipsForPerson :many
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to,
       created_by_membership_id
FROM   identity.tenant_memberships
WHERE  person_id = $1
ORDER  BY joined_at
`

// Cross-tenant list of a Person's memberships. RLS filters to current
// tenant unless platform-bypass is set; cross-tenant enumeration runs
// under platform context (anonymise / global-suspend cascade flows).
func (q *Queries) ListMembershipsForPerson(ctx context.Context, personID pgtype.UUID) ([]IdentityTenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityTenantMembership
	for rows.Next() {
		var i IdentityTenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Designation,
			&i.Department,
			&i.StatusMessage,
			&i.ReportsTo,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsInCurrentTenant = `-- name: ListMembershipsInCurrentTenant :many
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to,
       created_by_membership_id
FROM   identity.tenant_memberships
ORDER  BY joined_at
`

// Cross-membership query under tenant scope â€” RLS filters to the
// current tenant via SET LOCAL app.tenant_id. Used by tenant-admin
// "manage users" UIs.
func (q *Queries) ListMembershipsInCurrentTenant(ctx context.Context) ([]IdentityTenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsInCurrentTenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityTenantMembership
	for rows.Next() {
		var i IdentityTenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Designation,
			&i.Department,
			&i.StatusMessage,
			&i.ReportsTo,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMembershipsInTenantPage = `-- name: ListActiveMembershipsInTenantPage :many
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to,
       created_by_membership_id
FROM   identity.tenant_memberships
WHERE  status = 'active'
  AND  (joined_at, id) < ($1::timestamptz, $2::uuid)
ORDER  BY joined_at DESC, id DESC
LIMIT  $3
`

type ListActiveMembershipsInTenantPageParams struct {
	BeforeJoinedAt pgtype.Timestamptz
	BeforeID       pgtype.UUID
	Limit          int32
}

// Keyset-paginated active-only listing per ADR 0038. Backed by the
// partial composite index idx_memberships_tenant_active_joined
// (tenant_id, joined_at DESC, id DESC) WHERE status = 'active' â€”
// planner emits Index Scan, not Seq Scan + Filter, when the cursor
// predicate uses tuple-comparison.
//
// Cursor semantics: (BeforeJoinedAt, BeforeID) is the previous-page
// boundary. First page passes (now() + 1 day, '00000000-...') so the
// tuple comparison admits every row.
//
// LIMIT is page_size+1 (the "peek one extra" trick from ADR 0038);
// the caller drops the extra row when present + uses it to set
// next_cursor.
func (q *Queries) ListActiveMembershipsInTenantPage(ctx context.Context, arg ListActiveMembershipsInTenantPageParams) ([]IdentityTenantMembership, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsInTenantPage, arg.BeforeJoinedAt, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityTenantMembership
	for rows.Next() {
		var i IdentityTenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Designation,
			&i.Department,
			&i.StatusMessage,
			&i.ReportsTo,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionOverridesByMembership = `-- name: ListPermissionOverridesByMembership :many
SELECT membership_id, permission_name, kind, tenant_id, updated_at
FROM   identity.membership_permission_overrides
WHERE  membership_id = $1
ORDER  BY permission_name
`

func (q *Queries) ListPermissionOverridesByMembership(ctx context.Context, membershipID pgtype.UUID) ([]IdentityMembershipPermissionOverride, error) {
	rows, err := q.db.Query(ctx, listPermissionOverridesByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityMembershipPermissionOverride
	for rows.Next() {
		var i IdentityMembershipPermissionOverride
		if err := rows.Scan(
			&i.MembershipID,
			&i.PermissionName,
			&i.Kind,
			&i.TenantID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentsByMembership = `-- name: ListRoleAssignmentsByMembership :many
SELECT membership_id, role_id, tenant_id, assigned_at
FROM   identity.role_assignments
WHERE  membership_id = $1
ORDER  BY assigned_at, role_id
`

func (q *Queries) ListRoleAssignmentsByMembership(ctx context.Context, membershipID pgtype.UUID) ([]IdentityRoleAssignment, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRoleAssignment
	for rows.Next() {
		var i IdentityRoleAssignment
		if err := rows.Scan(
			&i.MembershipID,
			&i.RoleID,
			&i.TenantID,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuperAdminMembershipsInTenant = `-- name: ListSuperAdminMembershipsInTenant :many
SELECT m.id, m.person_id, m.tenant_id, m.status, m.joined_at,
       m.left_at, m.designation, m.department, m.status_message,
       m.reports_to, m.created_by_membership_id
FROM   identity.tenant_memberships m
JOIN   identity.role_assignments  ra ON ra.membership_id = m.id
JOIN   identity.roles             r  ON r.id = ra.role_id
WHERE  m.tenant_id     = $1
  AND  m.status        = 'active'
  AND  r.is_super_admin = true
  AND  NOT r.is_deleted
`

// Returns the active Memberships in the supplied tenant that hold a
// role flagged is_super_admin=true. Powers the platform-tenant
// deletion guard (cmd 20260507000008): a tenant containing any
// SuperAdmin role-holder cannot be soft-deleted via the standard
// tenant lifecycle commands. Queryable in O(1) via the partial index
// idx_roles_super_admin.
func (q *Queries) ListSuperAdminMembershipsInTenant(ctx context.Context, tenantID pgtype.UUID) ([]IdentityTenantMembership, error) {
	rows, err := q.db.Query(ctx, listSuperAdminMembershipsInTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityTenantMembership
	for rows.Next() {
		var i IdentityTenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Designation,
			&i.Department,
			&i.StatusMessage,
			&i.ReportsTo,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipProfile = `-- name: UpdateMembershipProfile :exec
UPDATE identity.tenant_memberships
SET    designation    = $2,
       department     = $3,
       status_message = $4,
       reports_to     = $5
WHERE  id = $1
`

type UpdateMembershipProfileParams struct {
	ID            pgtype.UUID
	Designation   string
	Department    string
	StatusMessage string
	ReportsTo     pgtype.UUID
}

// Per-tenant profile fields. designation/department/status_message default
// to â€ (NOT NULL DEFAULT â€); reports_to is NULLable (top-of-tree). Caller
// (UpdateByID) writes the aggregate's current state â€” no per-field diff.
func (q *Queries) UpdateMembershipProfile(ctx context.Context, arg UpdateMembershipProfileParams) error {
	_, err := q.db.Exec(ctx, updateMembershipProfile,
		arg.ID,
		arg.Designation,
		arg.Department,
		arg.StatusMessage,
		arg.ReportsTo,
	)
	return err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :exec
UPDATE identity.tenant_memberships
SET    status  = $2,
       left_at = $3
WHERE  id = $1
`

type UpdateMembershipStatusParams struct {
	ID     pgtype.UUID
	Status string
	LeftAt pgtype.Timestamptz
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) error {
	_, err := q.db.Exec(ctx, updateMembershipStatus, arg.ID, arg.Status, arg.LeftAt)
	return err
}
