// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// X-Command-Id replay store per Stripe Idempotency-Key canon. 24h default TTL; background purge.
type AppCommandIdempotency struct {
	CommandID      string
	BodyHash       string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	// Per-caller scoping per Stripe Idempotency-Key canon. Tenant ID for tenant requests, "platform:<user>" for operator paths, "anon:<ip>" for unauth (defense-in-depth â€” middleware should not be on unauth routes).
	CallerID string
	// Captured response headers for verbatim replay (Content-Type minimum; ETag / X-Request-Id when set).
	ResponseHeaders []byte
}

// Per-request operator impersonation activity. Indexed on operator + target tenant for forensic queries. 7-year retention per SOC2 CC4.1 / DPDP Â§12.
type BuildingblocksAdminImpersonationAudit struct {
	ID             pgtype.UUID
	SessionID      pgtype.UUID
	OperatorUserID pgtype.UUID
	TargetTenantID pgtype.UUID
	CorrelationID  string
	HttpRoute      string
	HttpMethod     string
	Reason         string
	StartedAtUtc   pgtype.Timestamptz
	IsGodMode      bool
}

// Auto-written per command via Watermill AuditLoggingMiddleware. 7-year retention; daily purge.
type BuildingblocksAuditLogEntry struct {
	ID            pgtype.UUID
	Action        string
	UserID        pgtype.UUID
	TenantID      pgtype.UUID
	CorrelationID pgtype.UUID
	OccurredAtUtc pgtype.Timestamptz
	DurationMs    int64
	Succeeded     bool
	FailureReason *string
	Payload       []byte
}

// Cross-tenant emailâ†’tenant index for login. NOT RLS-scoped (intentional â€” login flow predates tenant context). Maintained via Watermill events.
type IdentityAuthRouting struct {
	Email          string
	PersonID       pgtype.UUID
	ActiveTenantID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

// Per-Membership permission overlay. Effective set = role union âˆª granted \ revoked.
type IdentityMembershipPermissionOverride struct {
	MembershipID   pgtype.UUID
	PermissionName string
	Kind           string
	TenantID       pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

// Domain events written same-tx as aggregate state. Watermill SQL forwarder polls + republishes. Doubles as audit log per ADR 0027.
type IdentityOutbox struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Topic       string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Forwarded   bool
	ForwardedAt pgtype.Timestamptz
}

// Person aggregate. Global identity (Auth0/Entra ID pattern). NOT tenant-scoped.
type IdentityPerson struct {
	ID                          pgtype.UUID
	Email                       string
	FirstName                   string
	LastName                    string
	PasswordHash                string
	SecurityStamp               pgtype.UUID
	IsActive                    bool
	IsAnonymised                bool
	CreatedAt                   pgtype.Timestamptz
	AnonymisedAt                pgtype.Timestamptz
	IsGloballySuspended         bool
	GlobalSuspensionReason      string
	GloballySuspendedAt         pgtype.Timestamptz
	PasswordResetTokenHash      *string
	PasswordResetExpiresAt      pgtype.Timestamptz
	PendingEmailChangeNewEmail  *string
	PendingEmailChangeTokenHash *string
	PendingEmailChangeExpiresAt pgtype.Timestamptz
	// Audit chain â€” Person of the user who created this row globally. NULL = system-bootstrapped (SuperAdmin, first-admin via RegisterTenant). Allows cross-tenant lookup of "who originally onboarded this user."
	CreatedByPersonID pgtype.UUID
}

// Per-handler inbox dedup. (message_id, handler_name) PK guarantees at-most-once-per-handler delivery.
type IdentityProcessedMessage struct {
	MessageID      pgtype.UUID
	HandlerName    string
	ProcessedAtUtc pgtype.Timestamptz
}

// Individual tokens within a family. Hash-only storage; plaintext NEVER persisted. RFC 9700 reuse detection in domain layer.
type IdentityRefreshToken struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	TokenHash    string
	Generation   int32
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

// Refresh-token family per RFC 9700 Â§4.13 + ADR 0011. NOT tenant-scoped â€” session-management infrastructure.
type IdentityRefreshTokenFamily struct {
	ID           pgtype.UUID
	PersonID     pgtype.UUID
	TenantID     pgtype.UUID
	DeviceLabel  string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Per-tenant Role catalogue. Tenant-scoped, FORCE RLS. SuperAdmin (is_super_admin=true) is seeded once in the platform tenant per multi-tenancy.md "SuperUser god-mode".
type IdentityRole struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	IsSystemDefault bool
	IsSuperAdmin    bool
	HierarchyLevel  int32
	Permissions     []byte
	CreatedAt       pgtype.Timestamptz
	IsDeleted       bool
	DeletedAt       pgtype.Timestamptz
	DeletedBy       *string
}

// Membership â†” Role junction with denormalised tenant_id. Composite FK ensures no cross-tenant role assignment.
type IdentityRoleAssignment struct {
	MembershipID pgtype.UUID
	RoleID       pgtype.UUID
	TenantID     pgtype.UUID
	AssignedAt   pgtype.Timestamptz
}

// Tenant aggregate root. Each row IS a tenant; not tenant-scoped (no RLS).
type IdentityTenant struct {
	ID                        pgtype.UUID
	Slug                      string
	LegalName                 string
	DisplayName               string
	Status                    string
	CreatedAt                 pgtype.Timestamptz
	ActivatedAt               pgtype.Timestamptz
	SuspendedAt               pgtype.Timestamptz
	GstNumber                 string
	PanNumber                 string
	DrugLicenceNumber         string
	AdminPhone                string
	AdminAddressStreet        string
	AdminAddressCity          string
	AdminAddressDistrict      string
	AdminAddressState         string
	AdminAddressStateCode     string
	AdminAddressPincode       string
	PasswordMinLength         int32
	PasswordRequireUppercase  bool
	PasswordRequireLowercase  bool
	PasswordRequireDigit      bool
	PasswordRequireSymbol     bool
	PasswordMaxFailedAttempts int32
	PasswordLockoutMinutes    int32
	Locale                    string
	TimeZone                  string
	DateFormat                string
	Currency                  string
	DeletionScheduledAt       pgtype.Timestamptz
	DeletionReason            string
	HardDeletedAt             pgtype.Timestamptz
}

// Per-tenant junction (Person â†” Tenant). Tenant-scoped, FORCE RLS. Single-Active-Membership invariant via partial unique index.
type IdentityTenantMembership struct {
	ID            pgtype.UUID
	PersonID      pgtype.UUID
	TenantID      pgtype.UUID
	Status        string
	JoinedAt      pgtype.Timestamptz
	LeftAt        pgtype.Timestamptz
	Designation   string
	Department    string
	StatusMessage string
	ReportsTo     pgtype.UUID
	// Audit chain â€” Membership of the user who created this row. NULL = system-bootstrapped (SuperAdmin, first-admin during tenant onboarding). Composite FK to (id, tenant_id) prevents cross-tenant spoofing.
	CreatedByMembershipID pgtype.UUID
}
