// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO identity.outbox (
    id, tenant_id, topic, payload, occurred_at,
    act_operator_id, act_session_id, act_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Outbox queries — identity.outbox is RLS+FORCE per ADR 0027 ("outbox
// table doubles as audit log"). Insert happens inside the same tx as
// aggregate state (Brandur "events table" pattern). Forwarder runs
// under platform-bypass to drain.
// act_operator_id / act_session_id / act_reason carry impersonation
// context (RFC 8693 act claim) per ADR 0056. NULL for non-impersonation
// events; populated when the emitting handler ran under a scoped JWT.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.Topic,
		arg.Payload,
		arg.OccurredAt,
		arg.ActOperatorID,
		arg.ActSessionID,
		arg.ActReason,
	)
	return err
}

const listAuditEventsForTenant = `-- name: ListAuditEventsForTenant :many
SELECT id, tenant_id, topic, payload, occurred_at, created_at,
       forwarded, forwarded_at,
       act_operator_id, act_session_id, act_reason
FROM   identity.outbox
WHERE  topic = $1
  AND  occurred_at >= $2
ORDER  BY occurred_at DESC, id DESC
LIMIT  $3
`

type ListAuditEventsForTenantParams struct {
	Topic      string
	OccurredAt pgtype.Timestamptz
	Limit      int32
}

// Per-tenant audit query (the outbox doubling as audit log per ADR 0027).
// Runs under tenant scope; RLS filters automatically.
func (q *Queries) ListAuditEventsForTenant(ctx context.Context, arg ListAuditEventsForTenantParams) ([]IdentityOutbox, error) {
	rows, err := q.db.Query(ctx, listAuditEventsForTenant, arg.Topic, arg.OccurredAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityOutbox
	for rows.Next() {
		var i IdentityOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Forwarded,
			&i.ForwardedAt,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnforwardedOutboxEvents = `-- name: ListUnforwardedOutboxEvents :many
SELECT id, tenant_id, topic, payload, occurred_at, created_at,
       forwarded, forwarded_at,
       act_operator_id, act_session_id, act_reason
FROM   identity.outbox
WHERE  forwarded = false
ORDER  BY created_at, id
LIMIT  $1
FOR    UPDATE SKIP LOCKED
`

// Forwarder polls this. Caller MUST run under app.is_platform=true so
// RLS policy outbox_select returns rows from every tenant.
//
// FOR UPDATE SKIP LOCKED (Postgres 9.5+) lets multiple forwarder
// replicas drain the outbox concurrently without double-publishing.
// During a Kubernetes rolling deploy the old + new pod overlap; a
// plain SELECT here would let both pick up the same rows + both
// publish + both UPDATE forwarded=true (one win, one duplicate
// downstream). SKIP LOCKED makes Postgres skip rows already row-
// locked by a sibling tx, so each in-flight forwarder sees a
// disjoint slice. Canonical Watermill SQL outbox shape +
// river-queue + Brandur Leach "Transactionally staged job drains
// in Postgres" use the same primitive.
func (q *Queries) ListUnforwardedOutboxEvents(ctx context.Context, limit int32) ([]IdentityOutbox, error) {
	rows, err := q.db.Query(ctx, listUnforwardedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityOutbox
	for rows.Next() {
		var i IdentityOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Forwarded,
			&i.ForwardedAt,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventForwarded = `-- name: MarkOutboxEventForwarded :exec
UPDATE identity.outbox
SET    forwarded    = true,
       forwarded_at = $2
WHERE  id = $1
`

type MarkOutboxEventForwardedParams struct {
	ID          pgtype.UUID
	ForwardedAt pgtype.Timestamptz
}

// Forwarder writes this AFTER successful publish to the broker. Policy
// outbox_modify requires app.is_platform=true.
func (q *Queries) MarkOutboxEventForwarded(ctx context.Context, arg MarkOutboxEventForwardedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventForwarded, arg.ID, arg.ForwardedAt)
	return err
}
