// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPermissionRequestByID = `-- name: GetPermissionRequestByID :one
SELECT id, tenant_id, requester_membership_id, permission_constant,
       duration_days, reason, state, approver_membership_id,
       decided_at, decision_reason, granted_override_id, expires_at,
       created_at, updated_at
FROM   identity.permission_requests
WHERE  id = $1
`

func (q *Queries) GetPermissionRequestByID(ctx context.Context, id pgtype.UUID) (IdentityPermissionRequest, error) {
	row := q.db.QueryRow(ctx, getPermissionRequestByID, id)
	var i IdentityPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterMembershipID,
		&i.PermissionConstant,
		&i.DurationDays,
		&i.Reason,
		&i.State,
		&i.ApproverMembershipID,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.GrantedOverrideID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPermissionRequest = `-- name: InsertPermissionRequest :exec

INSERT INTO identity.permission_requests (
    id, tenant_id, requester_membership_id, permission_constant,
    duration_days, reason, state, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $7)
`

type InsertPermissionRequestParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	RequesterMembershipID pgtype.UUID
	PermissionConstant    string
	DurationDays          int32
	Reason                string
	CreatedAt             pgtype.Timestamptz
}

// Permission-elevation request queries — identity.permission_requests
// is RLS+FORCE per ADR 0055. Reads/writes flow through RLS: only the
// current tenant's rows are visible unless app.is_platform=true.
//
// The at-most-one-pending-per-(membership, permission) invariant lives
// in a partial unique index (uq_permission_requests_pending); the
// adapter translates the SQLSTATE 23505 raised on collision into
// permissionrequest.ErrPendingRequestExists.
// Pending-state row. State / decision fields NULL at creation; only
// populated by InsertPermissionRequestDecision once Approve/Deny/Cancel
// fires.
func (q *Queries) InsertPermissionRequest(ctx context.Context, arg InsertPermissionRequestParams) error {
	_, err := q.db.Exec(ctx, insertPermissionRequest,
		arg.ID,
		arg.TenantID,
		arg.RequesterMembershipID,
		arg.PermissionConstant,
		arg.DurationDays,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listPendingPermissionRequestsByApproverPage = `-- name: ListPendingPermissionRequestsByApproverPage :many
SELECT id, tenant_id, requester_membership_id, permission_constant,
       duration_days, reason, state, approver_membership_id,
       decided_at, decision_reason, granted_override_id, expires_at,
       created_at, updated_at
FROM   identity.permission_requests
WHERE  approver_membership_id = $1
  AND  state                  = 'pending'
  AND  (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER  BY created_at DESC, id DESC
LIMIT  $4
`

type ListPendingPermissionRequestsByApproverPageParams struct {
	ApproverMembershipID pgtype.UUID
	Column2              pgtype.Timestamptz
	Column3              pgtype.UUID
	Limit                int32
}

// Approver-side queue (state=pending). Same keyset semantics as the
// requester page. Backed by idx_permission_requests_approver_pending.
func (q *Queries) ListPendingPermissionRequestsByApproverPage(ctx context.Context, arg ListPendingPermissionRequestsByApproverPageParams) ([]IdentityPermissionRequest, error) {
	rows, err := q.db.Query(ctx, listPendingPermissionRequestsByApproverPage,
		arg.ApproverMembershipID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPermissionRequest
	for rows.Next() {
		var i IdentityPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterMembershipID,
			&i.PermissionConstant,
			&i.DurationDays,
			&i.Reason,
			&i.State,
			&i.ApproverMembershipID,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.GrantedOverrideID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPermissionRequestsForMembership = `-- name: ListPendingPermissionRequestsForMembership :many
SELECT id, tenant_id, requester_membership_id, permission_constant,
       duration_days, reason, state, approver_membership_id,
       decided_at, decision_reason, granted_override_id, expires_at,
       created_at, updated_at
FROM   identity.permission_requests
WHERE  requester_membership_id = $1
  AND  state                   = 'pending'
ORDER  BY created_at DESC
`

// Used by the requester-side endpoint + the at-most-one-pending
// invariant guard at handler-time pre-validation.
func (q *Queries) ListPendingPermissionRequestsForMembership(ctx context.Context, requesterMembershipID pgtype.UUID) ([]IdentityPermissionRequest, error) {
	rows, err := q.db.Query(ctx, listPendingPermissionRequestsForMembership, requesterMembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPermissionRequest
	for rows.Next() {
		var i IdentityPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterMembershipID,
			&i.PermissionConstant,
			&i.DurationDays,
			&i.Reason,
			&i.State,
			&i.ApproverMembershipID,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.GrantedOverrideID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRequestsByRequesterPage = `-- name: ListPermissionRequestsByRequesterPage :many
SELECT id, tenant_id, requester_membership_id, permission_constant,
       duration_days, reason, state, approver_membership_id,
       decided_at, decision_reason, granted_override_id, expires_at,
       created_at, updated_at
FROM   identity.permission_requests
WHERE  requester_membership_id = $1
  AND  (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER  BY created_at DESC, id DESC
LIMIT  $4
`

type ListPermissionRequestsByRequesterPageParams struct {
	RequesterMembershipID pgtype.UUID
	Column2               pgtype.Timestamptz
	Column3               pgtype.UUID
	Limit                 int32
}

// Requester-side keyset-paginated history. Cursor walks (created_at
// DESC, id DESC). LIMIT $4 is page_size+1 per ADR 0038 "peek one extra".
func (q *Queries) ListPermissionRequestsByRequesterPage(ctx context.Context, arg ListPermissionRequestsByRequesterPageParams) ([]IdentityPermissionRequest, error) {
	rows, err := q.db.Query(ctx, listPermissionRequestsByRequesterPage,
		arg.RequesterMembershipID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPermissionRequest
	for rows.Next() {
		var i IdentityPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterMembershipID,
			&i.PermissionConstant,
			&i.DurationDays,
			&i.Reason,
			&i.State,
			&i.ApproverMembershipID,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.GrantedOverrideID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermissionRequestDecision = `-- name: UpdatePermissionRequestDecision :exec
UPDATE identity.permission_requests
SET    state                  = $2,
       approver_membership_id = $3,
       decided_at             = $4,
       decision_reason        = $5,
       granted_override_id    = $6,
       expires_at             = $7,
       updated_at             = $8
WHERE  id = $1
`

type UpdatePermissionRequestDecisionParams struct {
	ID                   pgtype.UUID
	State                string
	ApproverMembershipID pgtype.UUID
	DecidedAt            pgtype.Timestamptz
	DecisionReason       *string
	GrantedOverrideID    pgtype.UUID
	ExpiresAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

// Approve / Deny / Cancel sets the decision-side columns under
// the UpdateFn pattern. State enforced at the application layer via
// the aggregate's state machine; the SQL just writes whatever the
// aggregate computed.
func (q *Queries) UpdatePermissionRequestDecision(ctx context.Context, arg UpdatePermissionRequestDecisionParams) error {
	_, err := q.db.Exec(ctx, updatePermissionRequestDecision,
		arg.ID,
		arg.State,
		arg.ApproverMembershipID,
		arg.DecidedAt,
		arg.DecisionReason,
		arg.GrantedOverrideID,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	return err
}
