// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const platformStatsBase = `-- name: PlatformStatsBase :one

SELECT
    (SELECT count(*) FROM identity.tenants)                                          AS tenants_total,
    (SELECT count(*) FROM identity.tenants WHERE status = 'active')                  AS tenants_active,
    (SELECT count(*) FROM identity.tenants WHERE status = 'suspended')               AS tenants_suspended,
    (SELECT count(*) FROM identity.persons WHERE NOT is_anonymised)                  AS persons_total,
    (SELECT count(*) FROM identity.tenant_memberships WHERE status = 'active')        AS memberships_active
`

type PlatformStatsBaseRow struct {
	TenantsTotal      int64
	TenantsActive     int64
	TenantsSuspended  int64
	PersonsTotal      int64
	MembershipsActive int64
}

// Platform operator-dashboard COUNT(*) rollups. Run under TxScopePlatform
// so the RLS-scoped tenant_memberships count sees every tenant's rows.
//
// Each method is collapsed to ONE round-trip via scalar subqueries
// (was N sequential SELECT COUNT(*) round-trips before the sqlc port).
// Counts/filters preserve the exact semantics of the prior hand-rolled
// queries.
func (q *Queries) PlatformStatsBase(ctx context.Context) (PlatformStatsBaseRow, error) {
	row := q.db.QueryRow(ctx, platformStatsBase)
	var i PlatformStatsBaseRow
	err := row.Scan(
		&i.TenantsTotal,
		&i.TenantsActive,
		&i.TenantsSuspended,
		&i.PersonsTotal,
		&i.MembershipsActive,
	)
	return i, err
}

const platformStatsDeltas = `-- name: PlatformStatsDeltas :one
SELECT
    (SELECT count(*) FROM identity.tenants
        WHERE created_at > now() - $1::interval)                        AS tenants_total,
    (SELECT count(*) FROM identity.tenants
        WHERE activated_at > now() - $1::interval)                      AS tenants_active,
    (SELECT count(*) FROM identity.persons
        WHERE created_at > now() - $1::interval
          AND NOT is_anonymised)                                                     AS persons_total,
    (SELECT count(*) FROM identity.tenant_memberships
        WHERE joined_at > now() - $1::interval
          AND status = 'active')                                                     AS memberships_active
`

type PlatformStatsDeltasRow struct {
	TenantsTotal      int64
	TenantsActive     int64
	PersonsTotal      int64
	MembershipsActive int64
}

// "new rows in interval" rollup. window is a Postgres interval string
// ("24 hours" / "7 days" / "30 days"); the closed-set label validator
// lives in the app layer.
func (q *Queries) PlatformStatsDeltas(ctx context.Context, win pgtype.Interval) (PlatformStatsDeltasRow, error) {
	row := q.db.QueryRow(ctx, platformStatsDeltas, win)
	var i PlatformStatsDeltasRow
	err := row.Scan(
		&i.TenantsTotal,
		&i.TenantsActive,
		&i.PersonsTotal,
		&i.MembershipsActive,
	)
	return i, err
}
