// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, is_system_default, is_super_admin,
       hierarchy_level, permissions, created_at,
       is_deleted, deleted_at, deleted_by
FROM   identity.roles
WHERE  id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsSystemDefault,
		&i.IsSuperAdmin,
		&i.HierarchyLevel,
		&i.Permissions,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRoleByTenantAndName = `-- name: GetRoleByTenantAndName :one
SELECT id, tenant_id, name, is_system_default, is_super_admin,
       hierarchy_level, permissions, created_at,
       is_deleted, deleted_at, deleted_by
FROM   identity.roles
WHERE  tenant_id = $1
  AND  name      = $2
  AND  NOT is_deleted
`

type GetRoleByTenantAndNameParams struct {
	TenantID pgtype.UUID
	Name     string
}

// Used by DefaultRoleCatalog seeding (Task 19) to detect re-seeds and
// by RoleRepository for "lookup-by-name" admin flows. Live rows only.
func (q *Queries) GetRoleByTenantAndName(ctx context.Context, arg GetRoleByTenantAndNameParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByTenantAndName, arg.TenantID, arg.Name)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsSystemDefault,
		&i.IsSuperAdmin,
		&i.HierarchyLevel,
		&i.Permissions,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, tenant_id, name, is_system_default, is_super_admin,
       hierarchy_level, permissions, created_at,
       is_deleted, deleted_at, deleted_by
FROM   identity.roles
WHERE  id = ANY($1::uuid[])
  AND  NOT is_deleted
`

// Bulk load for the PermissionResolver (Task 21) â€” given a Membership's
// RoleAssignments, hydrate each Role's permission set in one query.
// RLS still applies; cross-tenant lookups must run under platform.
func (q *Queries) GetRolesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRole
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IsSystemDefault,
			&i.IsSuperAdmin,
			&i.HierarchyLevel,
			&i.Permissions,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRole = `-- name: InsertRole :exec

INSERT INTO identity.roles (
    id, tenant_id, name, is_system_default, is_super_admin,
    hierarchy_level, permissions, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRoleParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	IsSystemDefault bool
	IsSuperAdmin    bool
	HierarchyLevel  int32
	Permissions     []byte
	CreatedAt       pgtype.Timestamptz
}

// Role queries â€” identity.roles is RLS+FORCE per multi-tenancy.md.
// Reads/writes flow through RLS: only the current tenant's rows are
// visible unless app.is_platform=true. Seeded SuperAdmin + custom
// per-tenant roles share the same table; isolation is enforced by RLS,
// not by the application layer.
func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.Exec(ctx, insertRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IsSystemDefault,
		arg.IsSuperAdmin,
		arg.HierarchyLevel,
		arg.Permissions,
		arg.CreatedAt,
	)
	return err
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, name, is_system_default, is_super_admin,
       hierarchy_level, permissions, created_at,
       is_deleted, deleted_at, deleted_by
FROM   identity.roles
WHERE  tenant_id  = $1
  AND  NOT is_deleted
ORDER  BY hierarchy_level, name
`

// Live (non-deleted) catalog for the current tenant. RLS scopes to the
// bound tenant_id GUC; passing $1 is belt-and-suspenders for explicit
// intent + platform-bypass paths that want a specific tenant.
func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]IdentityRole, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRole
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IsSystemDefault,
			&i.IsSuperAdmin,
			&i.HierarchyLevel,
			&i.Permissions,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE identity.roles
SET    is_deleted = true,
       deleted_at = $2,
       deleted_by = $3
WHERE  id = $1
`

type SoftDeleteRoleParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *string
}

// One-way soft-delete. Filtered out by every other query via
// "AND NOT is_deleted" predicate; the partial unique index on
// (tenant_id, name) WHERE NOT is_deleted releases the name for reuse.
func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.Exec(ctx, softDeleteRole, arg.ID, arg.DeletedAt, arg.DeletedBy)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE identity.roles
SET    name            = $2,
       hierarchy_level = $3,
       permissions     = $4
WHERE  id = $1
`

type UpdateRoleParams struct {
	ID             pgtype.UUID
	Name           string
	HierarchyLevel int32
	Permissions    []byte
}

// Persists the mutable Role state â€” name, hierarchy_level, permissions
// â€” under the UpdateFn pattern (Task 17). is_system_default + is_super_admin
// + tenant_id + created_at are aggregate-immutable; soft-delete uses
// SoftDeleteRole below.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.HierarchyLevel,
		arg.Permissions,
	)
	return err
}
