// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_hierarchy_edges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveHierarchyEdgeByChild = `-- name: GetActiveHierarchyEdgeByChild :one
SELECT id, tenant_id, child_role_id, parent_role_id,
       established_at, established_by_membership_id, reason,
       removed_at, removed_by_membership_id, removal_reason
FROM   identity.role_hierarchy_edges
WHERE  child_role_id = $1
  AND  removed_at    IS NULL
`

// Used by SetRoleParent's "replace existing parent" path + the
// read-side RoleView projection (join to populate parent_role_id).
func (q *Queries) GetActiveHierarchyEdgeByChild(ctx context.Context, childRoleID pgtype.UUID) (IdentityRoleHierarchyEdge, error) {
	row := q.db.QueryRow(ctx, getActiveHierarchyEdgeByChild, childRoleID)
	var i IdentityRoleHierarchyEdge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChildRoleID,
		&i.ParentRoleID,
		&i.EstablishedAt,
		&i.EstablishedByMembershipID,
		&i.Reason,
		&i.RemovedAt,
		&i.RemovedByMembershipID,
		&i.RemovalReason,
	)
	return i, err
}

const getHierarchyAncestorsByChild = `-- name: GetHierarchyAncestorsByChild :many
WITH RECURSIVE ancestor_chain AS (
    SELECT e.id, e.tenant_id, e.child_role_id, e.parent_role_id,
           e.established_at, e.established_by_membership_id, e.reason,
           e.removed_at, e.removed_by_membership_id, e.removal_reason,
           0 AS depth
    FROM   identity.role_hierarchy_edges e
    WHERE  e.child_role_id = $1
      AND  e.removed_at    IS NULL
    UNION ALL
    SELECT step.id, step.tenant_id, step.child_role_id, step.parent_role_id,
           step.established_at, step.established_by_membership_id, step.reason,
           step.removed_at, step.removed_by_membership_id, step.removal_reason,
           ac.depth + 1
    FROM   identity.role_hierarchy_edges step
    INNER JOIN ancestor_chain ac ON step.child_role_id = ac.parent_role_id
    WHERE  step.removed_at IS NULL
      AND  ac.depth        < 32
)
SELECT id, tenant_id, child_role_id, parent_role_id,
       established_at, established_by_membership_id, reason,
       removed_at, removed_by_membership_id, removal_reason
FROM   ancestor_chain
ORDER  BY depth ASC
`

type GetHierarchyAncestorsByChildRow struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	ChildRoleID               pgtype.UUID
	ParentRoleID              pgtype.UUID
	EstablishedAt             pgtype.Timestamptz
	EstablishedByMembershipID pgtype.UUID
	Reason                    *string
	RemovedAt                 pgtype.Timestamptz
	RemovedByMembershipID     pgtype.UUID
	RemovalReason             *string
}

// Recursive CTE walking the parent chain UPWARD from the supplied
// child_role_id. Only ACTIVE edges (removed_at IS NULL) are walked.
// The seed row (the input child) is NOT returned; only its ancestor
// edges are.
//
// Depth column drives the ORDER BY so the caller gets
// child's-parent first → grandparent → … root.
func (q *Queries) GetHierarchyAncestorsByChild(ctx context.Context, childRoleID pgtype.UUID) ([]GetHierarchyAncestorsByChildRow, error) {
	rows, err := q.db.Query(ctx, getHierarchyAncestorsByChild, childRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHierarchyAncestorsByChildRow
	for rows.Next() {
		var i GetHierarchyAncestorsByChildRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChildRoleID,
			&i.ParentRoleID,
			&i.EstablishedAt,
			&i.EstablishedByMembershipID,
			&i.Reason,
			&i.RemovedAt,
			&i.RemovedByMembershipID,
			&i.RemovalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHierarchyEdgeByID = `-- name: GetHierarchyEdgeByID :one
SELECT id, tenant_id, child_role_id, parent_role_id,
       established_at, established_by_membership_id, reason,
       removed_at, removed_by_membership_id, removal_reason
FROM   identity.role_hierarchy_edges
WHERE  id = $1
`

func (q *Queries) GetHierarchyEdgeByID(ctx context.Context, id pgtype.UUID) (IdentityRoleHierarchyEdge, error) {
	row := q.db.QueryRow(ctx, getHierarchyEdgeByID, id)
	var i IdentityRoleHierarchyEdge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChildRoleID,
		&i.ParentRoleID,
		&i.EstablishedAt,
		&i.EstablishedByMembershipID,
		&i.Reason,
		&i.RemovedAt,
		&i.RemovedByMembershipID,
		&i.RemovalReason,
	)
	return i, err
}

const insertHierarchyEdge = `-- name: InsertHierarchyEdge :exec

INSERT INTO identity.role_hierarchy_edges (
    id, tenant_id, child_role_id, parent_role_id,
    established_at, established_by_membership_id, reason
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertHierarchyEdgeParams struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	ChildRoleID               pgtype.UUID
	ParentRoleID              pgtype.UUID
	EstablishedAt             pgtype.Timestamptz
	EstablishedByMembershipID pgtype.UUID
	Reason                    *string
}

// Role hierarchy edge queries — identity.role_hierarchy_edges is
// RLS+FORCE per ADR 0058 (Wave 9.4). Reads/writes flow through RLS:
// only the current tenant's rows are visible unless
// app.is_platform = true.
//
// The single-parent invariant ("a child has at most one ACTIVE
// parent") lives in the partial unique index
// uq_role_hierarchy_active_edge_per_child; the adapter translates
// the SQLSTATE 23505 raised on collision into
// rolehierarchy.ErrEdgeAlreadyExists.
// Active-state row. removed_at / removed_by / removal_reason NULL at
// creation; populated by UpdateHierarchyEdgeRemoved once
// Remove fires through the UpdateFn pattern.
func (q *Queries) InsertHierarchyEdge(ctx context.Context, arg InsertHierarchyEdgeParams) error {
	_, err := q.db.Exec(ctx, insertHierarchyEdge,
		arg.ID,
		arg.TenantID,
		arg.ChildRoleID,
		arg.ParentRoleID,
		arg.EstablishedAt,
		arg.EstablishedByMembershipID,
		arg.Reason,
	)
	return err
}

const listActiveHierarchyEdgesByParent = `-- name: ListActiveHierarchyEdgesByParent :many
SELECT id, tenant_id, child_role_id, parent_role_id,
       established_at, established_by_membership_id, reason,
       removed_at, removed_by_membership_id, removal_reason
FROM   identity.role_hierarchy_edges
WHERE  parent_role_id = $1
  AND  removed_at     IS NULL
ORDER  BY established_at ASC
`

// "Show direct children of X" — used by approval-workflow reporting
// + future org-chart UI. Ordered by establishment time so audit
// dashboards render edges chronologically.
func (q *Queries) ListActiveHierarchyEdgesByParent(ctx context.Context, parentRoleID pgtype.UUID) ([]IdentityRoleHierarchyEdge, error) {
	rows, err := q.db.Query(ctx, listActiveHierarchyEdgesByParent, parentRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRoleHierarchyEdge
	for rows.Next() {
		var i IdentityRoleHierarchyEdge
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChildRoleID,
			&i.ParentRoleID,
			&i.EstablishedAt,
			&i.EstablishedByMembershipID,
			&i.Reason,
			&i.RemovedAt,
			&i.RemovedByMembershipID,
			&i.RemovalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHierarchyEdgeRemoved = `-- name: UpdateHierarchyEdgeRemoved :exec
UPDATE identity.role_hierarchy_edges
SET    removed_at               = $2,
       removed_by_membership_id = $3,
       removal_reason           = $4
WHERE  id = $1
`

type UpdateHierarchyEdgeRemovedParams struct {
	ID                    pgtype.UUID
	RemovedAt             pgtype.Timestamptz
	RemovedByMembershipID pgtype.UUID
	RemovalReason         *string
}

// Soft-delete via the UpdateFn pattern. State enforced at the
// application layer via the aggregate's IsActive guard; the SQL
// just writes whatever the aggregate computed.
func (q *Queries) UpdateHierarchyEdgeRemoved(ctx context.Context, arg UpdateHierarchyEdgeRemovedParams) error {
	_, err := q.db.Exec(ctx, updateHierarchyEdgeRemoved,
		arg.ID,
		arg.RemovedAt,
		arg.RemovedByMembershipID,
		arg.RemovalReason,
	)
	return err
}
