// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssignmentHistoryByID = `-- name: GetAssignmentHistoryByID :one
SELECT id, tenant_id, lead_id,
       previous_assignee_membership_id, assignee_membership_id,
       assigned_by_membership_id, reason, assigned_at, created_at
FROM   crm.assignment_history
WHERE  id = $1
`

func (q *Queries) GetAssignmentHistoryByID(ctx context.Context, id pgtype.UUID) (CrmAssignmentHistory, error) {
	row := q.db.QueryRow(ctx, getAssignmentHistoryByID, id)
	var i CrmAssignmentHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeadID,
		&i.PreviousAssigneeMembershipID,
		&i.AssigneeMembershipID,
		&i.AssignedByMembershipID,
		&i.Reason,
		&i.AssignedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssignmentHistory = `-- name: InsertAssignmentHistory :exec

INSERT INTO crm.assignment_history (
    id, tenant_id, lead_id,
    previous_assignee_membership_id, assignee_membership_id,
    assigned_by_membership_id, reason, assigned_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAssignmentHistoryParams struct {
	ID                           pgtype.UUID
	TenantID                     pgtype.UUID
	LeadID                       pgtype.UUID
	PreviousAssigneeMembershipID pgtype.UUID
	AssigneeMembershipID         pgtype.UUID
	AssignedByMembershipID       pgtype.UUID
	Reason                       string
	AssignedAt                   pgtype.Timestamptz
	CreatedAt                    pgtype.Timestamptz
}

// AssignmentHistory queries — crm.assignment_history is RLS+FORCE per
// ADR 0006 + migration 20260602000001. Append-only: no UPDATE / DELETE.
func (q *Queries) InsertAssignmentHistory(ctx context.Context, arg InsertAssignmentHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAssignmentHistory,
		arg.ID,
		arg.TenantID,
		arg.LeadID,
		arg.PreviousAssigneeMembershipID,
		arg.AssigneeMembershipID,
		arg.AssignedByMembershipID,
		arg.Reason,
		arg.AssignedAt,
		arg.CreatedAt,
	)
	return err
}

const listAssignmentHistoryByLead = `-- name: ListAssignmentHistoryByLead :many
SELECT id, tenant_id, lead_id,
       previous_assignee_membership_id, assignee_membership_id,
       assigned_by_membership_id, reason, assigned_at, created_at
FROM   crm.assignment_history
WHERE  lead_id = $1
ORDER  BY assigned_at DESC, id DESC
`

func (q *Queries) ListAssignmentHistoryByLead(ctx context.Context, leadID pgtype.UUID) ([]CrmAssignmentHistory, error) {
	rows, err := q.db.Query(ctx, listAssignmentHistoryByLead, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmAssignmentHistory
	for rows.Next() {
		var i CrmAssignmentHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LeadID,
			&i.PreviousAssigneeMembershipID,
			&i.AssigneeMembershipID,
			&i.AssignedByMembershipID,
			&i.Reason,
			&i.AssignedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
