// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: call_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCallLogByID = `-- name: GetCallLogByID :one
SELECT id, tenant_id, lead_id, outcome, notes,
       logged_by_membership_id, logged_at, created_at
FROM   crm.call_logs
WHERE  id = $1
`

func (q *Queries) GetCallLogByID(ctx context.Context, id pgtype.UUID) (CrmCallLog, error) {
	row := q.db.QueryRow(ctx, getCallLogByID, id)
	var i CrmCallLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeadID,
		&i.Outcome,
		&i.Notes,
		&i.LoggedByMembershipID,
		&i.LoggedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCallLog = `-- name: InsertCallLog :exec

INSERT INTO crm.call_logs (
    id, tenant_id, lead_id, outcome, notes,
    logged_by_membership_id, logged_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCallLogParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	LeadID               pgtype.UUID
	Outcome              string
	Notes                string
	LoggedByMembershipID pgtype.UUID
	LoggedAt             pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

// CallLog queries — crm.call_logs is RLS+FORCE per ADR 0006 +
// migration 20260602000001. Append-only: no UPDATE / DELETE queries.
func (q *Queries) InsertCallLog(ctx context.Context, arg InsertCallLogParams) error {
	_, err := q.db.Exec(ctx, insertCallLog,
		arg.ID,
		arg.TenantID,
		arg.LeadID,
		arg.Outcome,
		arg.Notes,
		arg.LoggedByMembershipID,
		arg.LoggedAt,
		arg.CreatedAt,
	)
	return err
}

const listCallLogsByLead = `-- name: ListCallLogsByLead :many
SELECT id, tenant_id, lead_id, outcome, notes,
       logged_by_membership_id, logged_at, created_at
FROM   crm.call_logs
WHERE  lead_id = $1
ORDER  BY logged_at DESC, id DESC
`

func (q *Queries) ListCallLogsByLead(ctx context.Context, leadID pgtype.UUID) ([]CrmCallLog, error) {
	rows, err := q.db.Query(ctx, listCallLogsByLead, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCallLog
	for rows.Next() {
		var i CrmCallLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LeadID,
			&i.Outcome,
			&i.Notes,
			&i.LoggedByMembershipID,
			&i.LoggedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
