// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crm_leads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCrmLeadByID = `-- name: GetCrmLeadByID :one
SELECT id, tenant_id, source_purchase_id, source_platform_lead_id,
       stage, temperature,
       contact_name, phone_e164, city, district, state, pincode,
       business_type, medicine_system, order_value, buy_timeline,
       has_drug_licence, has_gst, gst_verified,
       product_ranges, dosage_forms, extra_profile,
       assignee_membership_id, assigned_at,
       converted_at, converted_by_membership_id,
       lost_at, lost_by_membership_id, lost_reason,
       created_at, created_by_membership_id
FROM   crm.crm_leads
WHERE  id = $1
`

func (q *Queries) GetCrmLeadByID(ctx context.Context, id pgtype.UUID) (CrmCrmLead, error) {
	row := q.db.QueryRow(ctx, getCrmLeadByID, id)
	var i CrmCrmLead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourcePurchaseID,
		&i.SourcePlatformLeadID,
		&i.Stage,
		&i.Temperature,
		&i.ContactName,
		&i.PhoneE164,
		&i.City,
		&i.District,
		&i.State,
		&i.Pincode,
		&i.BusinessType,
		&i.MedicineSystem,
		&i.OrderValue,
		&i.BuyTimeline,
		&i.HasDrugLicence,
		&i.HasGst,
		&i.GstVerified,
		&i.ProductRanges,
		&i.DosageForms,
		&i.ExtraProfile,
		&i.AssigneeMembershipID,
		&i.AssignedAt,
		&i.ConvertedAt,
		&i.ConvertedByMembershipID,
		&i.LostAt,
		&i.LostByMembershipID,
		&i.LostReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getCrmLeadByPurchaseID = `-- name: GetCrmLeadByPurchaseID :one
SELECT id, tenant_id, source_purchase_id, source_platform_lead_id,
       stage, temperature,
       contact_name, phone_e164, city, district, state, pincode,
       business_type, medicine_system, order_value, buy_timeline,
       has_drug_licence, has_gst, gst_verified,
       product_ranges, dosage_forms, extra_profile,
       assignee_membership_id, assigned_at,
       converted_at, converted_by_membership_id,
       lost_at, lost_by_membership_id, lost_reason,
       created_at, created_by_membership_id
FROM   crm.crm_leads
WHERE  source_purchase_id = $1
`

// Subscriber idempotency lookup. NULL inputs are not valid here — the
// subscriber's command short-circuits before the call when PurchaseID
// is empty.
func (q *Queries) GetCrmLeadByPurchaseID(ctx context.Context, sourcePurchaseID pgtype.UUID) (CrmCrmLead, error) {
	row := q.db.QueryRow(ctx, getCrmLeadByPurchaseID, sourcePurchaseID)
	var i CrmCrmLead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourcePurchaseID,
		&i.SourcePlatformLeadID,
		&i.Stage,
		&i.Temperature,
		&i.ContactName,
		&i.PhoneE164,
		&i.City,
		&i.District,
		&i.State,
		&i.Pincode,
		&i.BusinessType,
		&i.MedicineSystem,
		&i.OrderValue,
		&i.BuyTimeline,
		&i.HasDrugLicence,
		&i.HasGst,
		&i.GstVerified,
		&i.ProductRanges,
		&i.DosageForms,
		&i.ExtraProfile,
		&i.AssigneeMembershipID,
		&i.AssignedAt,
		&i.ConvertedAt,
		&i.ConvertedByMembershipID,
		&i.LostAt,
		&i.LostByMembershipID,
		&i.LostReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertCrmLead = `-- name: InsertCrmLead :exec

INSERT INTO crm.crm_leads (
    id, tenant_id, source_purchase_id, source_platform_lead_id,
    stage, temperature,
    contact_name, phone_e164, city, district, state, pincode,
    business_type, medicine_system, order_value, buy_timeline,
    has_drug_licence, has_gst, gst_verified,
    product_ranges, dosage_forms, extra_profile,
    assignee_membership_id, assigned_at,
    converted_at, converted_by_membership_id,
    lost_at, lost_by_membership_id, lost_reason,
    created_at, created_by_membership_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22,
    $23, $24,
    $25, $26,
    $27, $28, $29,
    $30, $31
)
`

type InsertCrmLeadParams struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	SourcePurchaseID        pgtype.UUID
	SourcePlatformLeadID    pgtype.UUID
	Stage                   string
	Temperature             string
	ContactName             string
	PhoneE164               string
	City                    string
	District                string
	State                   string
	Pincode                 string
	BusinessType            string
	MedicineSystem          string
	OrderValue              string
	BuyTimeline             string
	HasDrugLicence          bool
	HasGst                  bool
	GstVerified             bool
	ProductRanges           []string
	DosageForms             []string
	ExtraProfile            []byte
	AssigneeMembershipID    pgtype.UUID
	AssignedAt              pgtype.Timestamptz
	ConvertedAt             pgtype.Timestamptz
	ConvertedByMembershipID pgtype.UUID
	LostAt                  pgtype.Timestamptz
	LostByMembershipID      pgtype.UUID
	LostReason              string
	CreatedAt               pgtype.Timestamptz
	CreatedByMembershipID   pgtype.UUID
}

// CrmLead queries — crm.crm_leads is RLS+FORCE per ADR 0006 +
// migration 20260602000001. Reads/writes flow through RLS: only the
// current tenant's rows are visible unless app.is_platform=true.
//
// Slice 1 surfaces:
//
//	InsertCrmLead          → repo Add path (subscriber + future manual import)
//	GetCrmLeadByID         → repo GetByID + UpdateByID load path
//	GetCrmLeadByPurchaseID → subscriber idempotency check (ADR 0060
//	                          natural-key idempotency)
//	UpdateCrmLead          → repo UpdateByID persist path; writes the
//	                          mutable columns (stage, temperature,
//	                          assignee, lifecycle terminals)
//	ListCrmLeadsPage       → cursor-paginated list per ADR 0038. Filter
//	                          columns merged inline; null/empty filters
//	                          short-circuit via IS NULL checks.
func (q *Queries) InsertCrmLead(ctx context.Context, arg InsertCrmLeadParams) error {
	_, err := q.db.Exec(ctx, insertCrmLead,
		arg.ID,
		arg.TenantID,
		arg.SourcePurchaseID,
		arg.SourcePlatformLeadID,
		arg.Stage,
		arg.Temperature,
		arg.ContactName,
		arg.PhoneE164,
		arg.City,
		arg.District,
		arg.State,
		arg.Pincode,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstVerified,
		arg.ProductRanges,
		arg.DosageForms,
		arg.ExtraProfile,
		arg.AssigneeMembershipID,
		arg.AssignedAt,
		arg.ConvertedAt,
		arg.ConvertedByMembershipID,
		arg.LostAt,
		arg.LostByMembershipID,
		arg.LostReason,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const listCrmLeadsPage = `-- name: ListCrmLeadsPage :many
SELECT id, tenant_id, source_purchase_id, source_platform_lead_id,
       stage, temperature,
       contact_name, phone_e164, city, district, state, pincode,
       business_type, medicine_system, order_value, buy_timeline,
       has_drug_licence, has_gst, gst_verified,
       product_ranges, dosage_forms, extra_profile,
       assignee_membership_id, assigned_at,
       converted_at, converted_by_membership_id,
       lost_at, lost_by_membership_id, lost_reason,
       created_at, created_by_membership_id
FROM   crm.crm_leads
WHERE  tenant_id = $1
  AND  ($2::text IS NULL OR stage = $2::text)
  AND  ($3::text IS NULL OR temperature = $3::text)
  AND  ($4::uuid IS NULL OR assignee_membership_id = $4::uuid)
  AND  ($5::uuid IS NULL OR assignee_membership_id = $5::uuid)
  AND  ($6::text IS NULL OR city = $6::text)
  AND  ($7::text IS NULL OR pincode = $7::text)
  AND  ($8::text IS NULL OR business_type = $8::text)
  AND  ($9::text IS NULL OR medicine_system = $9::text)
  AND  ($10::text[] IS NULL OR product_ranges @> $10::text[])
  AND  ($11::text[] IS NULL OR dosage_forms @> $11::text[])
  AND  ($12::text IS NULL OR contact_name ILIKE $12::text)
  AND  ($13::timestamptz IS NULL OR
        (created_at, id) < ($13::timestamptz, $14::uuid))
ORDER  BY created_at DESC, id DESC
LIMIT  $15::int
`

type ListCrmLeadsPageParams struct {
	TenantID        pgtype.UUID
	Stage           *string
	Temperature     *string
	Assignee        pgtype.UUID
	SelfAssignee    pgtype.UUID
	City            *string
	Pincode         *string
	BusinessType    *string
	MedicineSystem  *string
	ProductRanges   []string
	DosageForms     []string
	NameQuery       *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

// Cursor (keyset) pagination on (created_at, id) DESC per ADR 0038.
// Composite filter columns supplied as nullable params — pass NULL /
// empty to disable a given filter.
//
// LIMIT is $page_size + 1 (peek-one-extra) — adapter strips the extra
// row + sets HasMore based on the returned row count.
//
// pg_trgm name search uses ILIKE so the GIN trgm index lights up
// naturally; the adapter wraps the user-supplied query in `%pat%`.
func (q *Queries) ListCrmLeadsPage(ctx context.Context, arg ListCrmLeadsPageParams) ([]CrmCrmLead, error) {
	rows, err := q.db.Query(ctx, listCrmLeadsPage,
		arg.TenantID,
		arg.Stage,
		arg.Temperature,
		arg.Assignee,
		arg.SelfAssignee,
		arg.City,
		arg.Pincode,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.ProductRanges,
		arg.DosageForms,
		arg.NameQuery,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCrmLead
	for rows.Next() {
		var i CrmCrmLead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourcePurchaseID,
			&i.SourcePlatformLeadID,
			&i.Stage,
			&i.Temperature,
			&i.ContactName,
			&i.PhoneE164,
			&i.City,
			&i.District,
			&i.State,
			&i.Pincode,
			&i.BusinessType,
			&i.MedicineSystem,
			&i.OrderValue,
			&i.BuyTimeline,
			&i.HasDrugLicence,
			&i.HasGst,
			&i.GstVerified,
			&i.ProductRanges,
			&i.DosageForms,
			&i.ExtraProfile,
			&i.AssigneeMembershipID,
			&i.AssignedAt,
			&i.ConvertedAt,
			&i.ConvertedByMembershipID,
			&i.LostAt,
			&i.LostByMembershipID,
			&i.LostReason,
			&i.CreatedAt,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrmLead = `-- name: UpdateCrmLead :exec
UPDATE crm.crm_leads
SET    stage                      = $2,
       temperature                = $3,
       assignee_membership_id     = $4,
       assigned_at                = $5,
       converted_at               = $6,
       converted_by_membership_id = $7,
       lost_at                    = $8,
       lost_by_membership_id      = $9,
       lost_reason                = $10,
       extra_profile              = $11,
       contact_name               = $12,
       phone_e164                 = $13,
       city                       = $14,
       district                   = $15,
       state                      = $16,
       pincode                    = $17,
       business_type              = $18,
       medicine_system            = $19,
       order_value                = $20,
       buy_timeline               = $21,
       has_drug_licence           = $22,
       has_gst                    = $23,
       gst_verified               = $24,
       product_ranges             = $25,
       dosage_forms               = $26
WHERE  id = $1
`

type UpdateCrmLeadParams struct {
	ID                      pgtype.UUID
	Stage                   string
	Temperature             string
	AssigneeMembershipID    pgtype.UUID
	AssignedAt              pgtype.Timestamptz
	ConvertedAt             pgtype.Timestamptz
	ConvertedByMembershipID pgtype.UUID
	LostAt                  pgtype.Timestamptz
	LostByMembershipID      pgtype.UUID
	LostReason              string
	ExtraProfile            []byte
	ContactName             string
	PhoneE164               string
	City                    string
	District                string
	State                   string
	Pincode                 string
	BusinessType            string
	MedicineSystem          string
	OrderValue              string
	BuyTimeline             string
	HasDrugLicence          bool
	HasGst                  bool
	GstVerified             bool
	ProductRanges           []string
	DosageForms             []string
}

// Persists the mutable CrmLead state. tenant_id + source_* + created_at
// + created_by_membership_id are aggregate-immutable; this query
// intentionally does NOT write them.
func (q *Queries) UpdateCrmLead(ctx context.Context, arg UpdateCrmLeadParams) error {
	_, err := q.db.Exec(ctx, updateCrmLead,
		arg.ID,
		arg.Stage,
		arg.Temperature,
		arg.AssigneeMembershipID,
		arg.AssignedAt,
		arg.ConvertedAt,
		arg.ConvertedByMembershipID,
		arg.LostAt,
		arg.LostByMembershipID,
		arg.LostReason,
		arg.ExtraProfile,
		arg.ContactName,
		arg.PhoneE164,
		arg.City,
		arg.District,
		arg.State,
		arg.Pincode,
		arg.BusinessType,
		arg.MedicineSystem,
		arg.OrderValue,
		arg.BuyTimeline,
		arg.HasDrugLicence,
		arg.HasGst,
		arg.GstVerified,
		arg.ProductRanges,
		arg.DosageForms,
	)
	return err
}
