// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// X-Command-Id replay store per Stripe Idempotency-Key canon. 24h default TTL; background purge.
type AppCommandIdempotency struct {
	CommandID      string
	BodyHash       string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	// Per-caller scoping per Stripe Idempotency-Key canon. Tenant ID for tenant requests, "platform:<user>" for operator paths, "anon:<ip>" for unauth (defense-in-depth — middleware should not be on unauth routes).
	CallerID string
	// Captured response headers for verbatim replay (Content-Type minimum; ETag / X-Request-Id when set).
	ResponseHeaders []byte
}

// Per-request operator impersonation activity. Indexed on operator + target tenant for forensic queries. 7-year retention per SOC2 CC4.1 / DPDP §12.
type BuildingblocksAdminImpersonationAudit struct {
	ID             pgtype.UUID
	SessionID      pgtype.UUID
	OperatorUserID pgtype.UUID
	TargetTenantID pgtype.UUID
	CorrelationID  string
	HttpRoute      string
	HttpMethod     string
	Reason         string
	StartedAtUtc   pgtype.Timestamptz
	IsGodMode      bool
}

// Auto-written per command via Watermill AuditLoggingMiddleware. 7-year retention; daily purge.
type BuildingblocksAuditLogEntry struct {
	ID            pgtype.UUID
	Action        string
	UserID        pgtype.UUID
	TenantID      pgtype.UUID
	CorrelationID pgtype.UUID
	OccurredAtUtc pgtype.Timestamptz
	DurationMs    int64
	Succeeded     bool
	FailureReason *string
	Payload       []byte
	// RFC 8693 act.sub — the original operator who initiated the impersonation session. NULL for non-impersonation rows.
	ActOperatorID pgtype.UUID
	// Impersonation session ID — joins to the impersonation store (Redis). NULL for non-impersonation rows.
	ActSessionID pgtype.UUID
	// Denormalised reason from the impersonation session — captured at-rest for forensic queryability without needing to re-resolve the session record. NULL for non-impersonation rows.
	ActReason *string
}

// AssignmentHistory aggregate per ADR 0060. Append-only assignment audit. Latest row by assigned_at == current assignee (mirrored on crm.crm_leads.assignee_membership_id).
type CrmAssignmentHistory struct {
	ID                           pgtype.UUID
	TenantID                     pgtype.UUID
	LeadID                       pgtype.UUID
	PreviousAssigneeMembershipID pgtype.UUID
	AssigneeMembershipID         pgtype.UUID
	AssignedByMembershipID       pgtype.UUID
	Reason                       string
	AssignedAt                   pgtype.Timestamptz
	CreatedAt                    pgtype.Timestamptz
}

// CallLog aggregate per ADR 0060. Append-only. Tenant-scoped FORCE RLS.
type CrmCallLog struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	LeadID               pgtype.UUID
	Outcome              string
	Notes                string
	LoggedByMembershipID pgtype.UUID
	LoggedAt             pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

// CrmLead aggregate per ADR 0060 + BRD §6.3. Stage state machine + independent temperature axis. source_purchase_id is the idempotency key for the lead-purchased subscriber.
type CrmCrmLead struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	SourcePurchaseID        pgtype.UUID
	SourcePlatformLeadID    pgtype.UUID
	Stage                   string
	Temperature             string
	ContactName             string
	PhoneE164               string
	City                    string
	District                string
	State                   string
	Pincode                 string
	BusinessType            string
	MedicineSystem          string
	OrderValue              string
	BuyTimeline             string
	HasDrugLicence          bool
	HasGst                  bool
	GstVerified             bool
	ProductRanges           []string
	DosageForms             []string
	ExtraProfile            []byte
	AssigneeMembershipID    pgtype.UUID
	AssignedAt              pgtype.Timestamptz
	ConvertedAt             pgtype.Timestamptz
	ConvertedByMembershipID pgtype.UUID
	LostAt                  pgtype.Timestamptz
	LostByMembershipID      pgtype.UUID
	LostReason              string
	CreatedAt               pgtype.Timestamptz
	CreatedByMembershipID   pgtype.UUID
}

// Per-module outbox per ADR 0008 + 0027. Same shape as identity.outbox + platform.outbox; forwarder publishes to Watermill topic crm.events. Doubles as audit log.
type CrmOutbox struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	Forwarded     bool
	ForwardedAt   pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Cross-tenant email→tenant index for login. NOT RLS-scoped (intentional — login flow predates tenant context). Maintained via Watermill events.
type IdentityAuthRouting struct {
	Email          string
	PersonID       pgtype.UUID
	ActiveTenantID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

// Per-Membership permission overlay. Effective set = role union ∪ granted \ revoked.
type IdentityMembershipPermissionOverride struct {
	MembershipID   pgtype.UUID
	PermissionName string
	Kind           string
	TenantID       pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
	// ADR 0055 — time-bound overlay grant. NULL = perpetual. Resolver filters expired entries at resolve time; no cron sweep at v0.2 scale.
	ExpiresAt pgtype.Timestamptz
}

// Domain events written same-tx as aggregate state. Watermill SQL forwarder polls + republishes. Doubles as audit log per ADR 0027.
type IdentityOutbox struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Topic       string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Forwarded   bool
	ForwardedAt pgtype.Timestamptz
	// RFC 8693 act.sub — operator who initiated the impersonation session under which this event was emitted. NULL for non-impersonation rows. Stamped by the outbox writer from authn.ClaimsFromContext(ctx).Act.Sub; the forwarder propagates onto Watermill message metadata so the subscriber-side AuditMiddleware can populate audit_log_entry.act_operator_id.
	ActOperatorID pgtype.UUID
	// Impersonation session ID — same propagation path as act_operator_id. NULL for non-impersonation rows.
	ActSessionID pgtype.UUID
	// Denormalised reason from the impersonation session — same propagation path. NULL for non-impersonation rows.
	ActReason *string
}

// ADR 0055 — permission-elevation approval workflow. Stores Requested → Approved/Denied/Cancelled history; approved grants land on identity.membership_permission_overrides with expires_at bounded.
type IdentityPermissionRequest struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	RequesterMembershipID pgtype.UUID
	PermissionConstant    string
	DurationDays          int32
	Reason                string
	State                 string
	ApproverMembershipID  pgtype.UUID
	DecidedAt             pgtype.Timestamptz
	DecisionReason        *string
	GrantedOverrideID     pgtype.UUID
	ExpiresAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// Person aggregate. Global identity (Auth0/Entra ID pattern). NOT tenant-scoped.
type IdentityPerson struct {
	ID                          pgtype.UUID
	Email                       string
	FirstName                   string
	LastName                    string
	PasswordHash                string
	SecurityStamp               pgtype.UUID
	IsActive                    bool
	IsAnonymised                bool
	CreatedAt                   pgtype.Timestamptz
	AnonymisedAt                pgtype.Timestamptz
	IsGloballySuspended         bool
	GlobalSuspensionReason      string
	GloballySuspendedAt         pgtype.Timestamptz
	PasswordResetTokenHash      *string
	PasswordResetExpiresAt      pgtype.Timestamptz
	PendingEmailChangeNewEmail  *string
	PendingEmailChangeTokenHash *string
	PendingEmailChangeExpiresAt pgtype.Timestamptz
	// Audit chain — Person of the user who created this row globally. NULL = system-bootstrapped (SuperAdmin, first-admin via RegisterTenant). Allows cross-tenant lookup of "who originally onboarded this user."
	CreatedByPersonID pgtype.UUID
	// BRD line 241 — true when admin/operator provisioned the credential; cleared on self-change/self-reset. Login still succeeds (frontend redirects); strict middleware enforcement is a v0.3 follow-up.
	MustChangePassword bool
	// NIST 800-63B §5.2.2 — count of consecutive failed login attempts in the current sliding window. Reset to 0 on successful login OR when LockoutWindow elapses since last_failed_login_at.
	FailedLoginCount int32
	// NIST 800-63B §5.2.2 — set to now+LockoutDuration when failed_login_count reaches MaxFailedLogins. NULL once login has succeeded (or never been locked).
	LockedUntil pgtype.Timestamptz
	// Timestamp of the most recent failed login; drives the sliding-window counter reset. NULL when failed_login_count = 0.
	LastFailedLoginAt pgtype.Timestamptz
}

// Per-handler inbox dedup. (message_id, handler_name) PK guarantees at-most-once-per-handler delivery.
type IdentityProcessedMessage struct {
	MessageID      pgtype.UUID
	HandlerName    string
	ProcessedAtUtc pgtype.Timestamptz
}

// Individual tokens within a family. Hash-only storage; plaintext NEVER persisted. RFC 9700 reuse detection in domain layer.
type IdentityRefreshToken struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	TokenHash    string
	Generation   int32
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

// Refresh-token family per RFC 9700 §4.13 + ADR 0011. NOT tenant-scoped — session-management infrastructure.
type IdentityRefreshTokenFamily struct {
	ID           pgtype.UUID
	PersonID     pgtype.UUID
	TenantID     pgtype.UUID
	DeviceLabel  string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Per-tenant Role catalogue. Tenant-scoped, FORCE RLS. SuperAdmin (is_super_admin=true) is seeded once in the platform tenant per multi-tenancy.md "SuperUser god-mode".
type IdentityRole struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	IsSystemDefault bool
	IsSuperAdmin    bool
	HierarchyLevel  int32
	Permissions     []byte
	CreatedAt       pgtype.Timestamptz
	IsDeleted       bool
	DeletedAt       pgtype.Timestamptz
	DeletedBy       *string
}

// Membership ↔ Role junction with denormalised tenant_id. Composite FK ensures no cross-tenant role assignment.
type IdentityRoleAssignment struct {
	MembershipID pgtype.UUID
	RoleID       pgtype.UUID
	TenantID     pgtype.UUID
	AssignedAt   pgtype.Timestamptz
}

// ADR 0058 — role-hierarchy aggregate (Wave 9.4). One row per directed parent→child edge. Soft-delete preserves history. Single-parent invariant via partial unique index uq_role_hierarchy_active_edge_per_child.
type IdentityRoleHierarchyEdge struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	ChildRoleID               pgtype.UUID
	ParentRoleID              pgtype.UUID
	EstablishedAt             pgtype.Timestamptz
	EstablishedByMembershipID pgtype.UUID
	Reason                    *string
	RemovedAt                 pgtype.Timestamptz
	RemovedByMembershipID     pgtype.UUID
	RemovalReason             *string
}

// Tenant aggregate root. Each row IS a tenant; not tenant-scoped (no RLS).
type IdentityTenant struct {
	ID                        pgtype.UUID
	Slug                      string
	LegalName                 string
	DisplayName               string
	Status                    string
	CreatedAt                 pgtype.Timestamptz
	ActivatedAt               pgtype.Timestamptz
	SuspendedAt               pgtype.Timestamptz
	GstNumber                 string
	PanNumber                 string
	DrugLicenceNumber         string
	AdminPhone                string
	AdminAddressStreet        string
	AdminAddressCity          string
	AdminAddressDistrict      string
	AdminAddressState         string
	AdminAddressStateCode     string
	AdminAddressPincode       string
	PasswordMinLength         int32
	PasswordRequireUppercase  bool
	PasswordRequireLowercase  bool
	PasswordRequireDigit      bool
	PasswordRequireSymbol     bool
	PasswordMaxFailedAttempts int32
	PasswordLockoutMinutes    int32
	Locale                    string
	TimeZone                  string
	DateFormat                string
	Currency                  string
	DeletionScheduledAt       pgtype.Timestamptz
	DeletionReason            string
	HardDeletedAt             pgtype.Timestamptz
}

// Per-tenant junction (Person ↔ Tenant). Tenant-scoped, FORCE RLS. Single-Active-Membership invariant via partial unique index.
type IdentityTenantMembership struct {
	ID            pgtype.UUID
	PersonID      pgtype.UUID
	TenantID      pgtype.UUID
	Status        string
	JoinedAt      pgtype.Timestamptz
	LeftAt        pgtype.Timestamptz
	Designation   string
	Department    string
	StatusMessage string
	ReportsTo     pgtype.UUID
	// Audit chain — Membership of the user who created this row. NULL = system-bootstrapped (SuperAdmin, first-admin during tenant onboarding). Composite FK to (id, tenant_id) prevents cross-tenant spoofing.
	CreatedByMembershipID pgtype.UUID
}

// Per-tenant credit balance. Optimistic concurrency: every UPDATE checks WHERE version = $old_version + sets version = $old_version + 1; 0 rows affected → conflict → command handler retries with backoff. Per ADR 0059.
type PlatformLeadCredit struct {
	TenantID  pgtype.UUID
	Balance   int64
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Per-module outbox per ADR 0008 + 0027. Same shape as identity.outbox; forwarder publishes to Watermill topic platform.events. Doubles as audit log.
type PlatformOutbox struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	Forwarded     bool
	ForwardedAt   pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Verified leads in the marketplace. RLS: unsold rows openly browsable; sold rows visible only to purchaser + platform. Per ADR 0059.
type PlatformPlatformLead struct {
	ID                     pgtype.UUID
	SourceContactID        pgtype.UUID
	SoldToTenantID         pgtype.UUID
	SoldAt                 pgtype.Timestamptz
	SoldToMembershipID     pgtype.UUID
	AmountPaisa            int64
	ContactName            string
	MobileE164             string
	Email                  string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	Street                 string
	HasDrugLicence         bool
	HasGst                 bool
	GstNumber              string
	GstVerified            bool
	HasPan                 bool
	PanNumber              string
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

// Lead Agent work queue. Platform-only (no tenant). State machine: new → in_call → verified | rejected | busy. On verified, a platform_leads row is created in the same tx.
type PlatformUnverifiedContact struct {
	ID                     pgtype.UUID
	State                  string
	RejectionReason        string
	BusyCallbackAt         pgtype.Timestamptz
	BusyCallbackEndAt      pgtype.Timestamptz
	PlatformLeadID         pgtype.UUID
	ContactName            string
	MobileE164             string
	Email                  string
	Pincode                string
	City                   string
	District               string
	StateGeo               string
	Street                 string
	HasDrugLicence         bool
	HasGst                 bool
	GstNumber              string
	HasPan                 bool
	PanNumber              string
	BusinessType           string
	MedicineSystem         string
	ProductRanges          []string
	DosageForms            []string
	OrderValue             string
	BuyTimeline            string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
	VerifiedAt             pgtype.Timestamptz
	VerifiedByMembershipID pgtype.UUID
	RejectedAt             pgtype.Timestamptz
	RejectedByMembershipID pgtype.UUID
}

// Append-only call log. Each row immutable post-insert. Callback window populated when outcome=busy (auto-creates a Reminder downstream in Phase 2.2).
type PlatformVerificationCall struct {
	ID                    pgtype.UUID
	ContactID             pgtype.UUID
	OutcomeCode           string
	Notes                 string
	CallbackWindowStartAt pgtype.Timestamptz
	CallbackWindowEndAt   pgtype.Timestamptz
	LoggedAt              pgtype.Timestamptz
	LoggedByMembershipID  pgtype.UUID
}
