// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCRMOutboxEvent = `-- name: InsertCRMOutboxEvent :exec

INSERT INTO crm.outbox (
    id, tenant_id, topic, payload, occurred_at,
    act_operator_id, act_session_id, act_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCRMOutboxEventParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// CRM outbox queries — crm.outbox is RLS+FORCE; mirror of
// identity.outbox + platform.outbox. Per ADR 0008 + 0027 + 0056.
//
// The forwarder polls via [SelectUnforwardedCRMEvents]; per-handler
// writes use [InsertOutboxEvent] inside the same tx as the aggregate
// mutation; the forwarder marks rows via [MarkCRMEventForwarded] after
// successful broker publish.
func (q *Queries) InsertCRMOutboxEvent(ctx context.Context, arg InsertCRMOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertCRMOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.Topic,
		arg.Payload,
		arg.OccurredAt,
		arg.ActOperatorID,
		arg.ActSessionID,
		arg.ActReason,
	)
	return err
}

const markCRMEventForwarded = `-- name: MarkCRMEventForwarded :exec
UPDATE crm.outbox
SET    forwarded = true,
       forwarded_at = $2
WHERE  id = $1
`

type MarkCRMEventForwardedParams struct {
	ID          pgtype.UUID
	ForwardedAt pgtype.Timestamptz
}

func (q *Queries) MarkCRMEventForwarded(ctx context.Context, arg MarkCRMEventForwardedParams) error {
	_, err := q.db.Exec(ctx, markCRMEventForwarded, arg.ID, arg.ForwardedAt)
	return err
}

const selectUnforwardedCRMEvents = `-- name: SelectUnforwardedCRMEvents :many
SELECT id, tenant_id, topic, payload, occurred_at, created_at,
       act_operator_id, act_session_id, act_reason
FROM   crm.outbox
WHERE  NOT forwarded
ORDER  BY created_at ASC, id ASC
LIMIT  $1
FOR    UPDATE SKIP LOCKED
`

type SelectUnforwardedCRMEventsRow struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Topic         string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	ActOperatorID pgtype.UUID
	ActSessionID  pgtype.UUID
	ActReason     *string
}

// Forwarder polling query.
//
// Ordering is created_at then id — the UUIDv7 id is the tiebreaker so
// events that commit with the same created_at still drain in causal order.
//
// FOR UPDATE SKIP LOCKED: lets multiple forwarder replicas drain
// concurrently without double-publishing — each replica locks a disjoint
// slice and skips rows another replica already holds. Mirrors the
// identity/platform/inventory drains; without it a rolling deploy with
// two forwarders republishes every row.
func (q *Queries) SelectUnforwardedCRMEvents(ctx context.Context, limit int32) ([]SelectUnforwardedCRMEventsRow, error) {
	rows, err := q.db.Query(ctx, selectUnforwardedCRMEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUnforwardedCRMEventsRow
	for rows.Next() {
		var i SelectUnforwardedCRMEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ActOperatorID,
			&i.ActSessionID,
			&i.ActReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
