// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPendingMatureForLead = `-- name: FindPendingMatureForLead :one
SELECT id, tenant_id, lead_id, assigned_to_membership_id,
       created_by_membership_id, source_call_log_id,
       type, state,
       due_at, notes,
       sent_at, marked_sent_by_membership_id,
       cancelled_at, cancelled_by_membership_id, cancel_reason,
       created_at
FROM   crm.reminders
WHERE  tenant_id = $1
  AND  lead_id   = $2
  AND  type      = 'mature_lead'
  AND  state     = 'pending'
`

type FindPendingMatureForLeadParams struct {
	TenantID pgtype.UUID
	LeadID   pgtype.UUID
}

// Hot-path probe for the mature-lead scheduler — saves the round-trip
// of catching a SQLSTATE 23505 on the partial unique index. Returns at
// most one row (the index enforces it).
func (q *Queries) FindPendingMatureForLead(ctx context.Context, arg FindPendingMatureForLeadParams) (CrmReminder, error) {
	row := q.db.QueryRow(ctx, findPendingMatureForLead, arg.TenantID, arg.LeadID)
	var i CrmReminder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeadID,
		&i.AssignedToMembershipID,
		&i.CreatedByMembershipID,
		&i.SourceCallLogID,
		&i.Type,
		&i.State,
		&i.DueAt,
		&i.Notes,
		&i.SentAt,
		&i.MarkedSentByMembershipID,
		&i.CancelledAt,
		&i.CancelledByMembershipID,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const getReminderByID = `-- name: GetReminderByID :one
SELECT id, tenant_id, lead_id, assigned_to_membership_id,
       created_by_membership_id, source_call_log_id,
       type, state,
       due_at, notes,
       sent_at, marked_sent_by_membership_id,
       cancelled_at, cancelled_by_membership_id, cancel_reason,
       created_at
FROM   crm.reminders
WHERE  id = $1
`

func (q *Queries) GetReminderByID(ctx context.Context, id pgtype.UUID) (CrmReminder, error) {
	row := q.db.QueryRow(ctx, getReminderByID, id)
	var i CrmReminder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeadID,
		&i.AssignedToMembershipID,
		&i.CreatedByMembershipID,
		&i.SourceCallLogID,
		&i.Type,
		&i.State,
		&i.DueAt,
		&i.Notes,
		&i.SentAt,
		&i.MarkedSentByMembershipID,
		&i.CancelledAt,
		&i.CancelledByMembershipID,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :exec

INSERT INTO crm.reminders (
    id, tenant_id, lead_id, assigned_to_membership_id,
    created_by_membership_id, source_call_log_id,
    type, state,
    due_at, notes,
    sent_at, marked_sent_by_membership_id,
    cancelled_at, cancelled_by_membership_id, cancel_reason,
    created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10,
    $11, $12,
    $13, $14, $15,
    $16
)
`

type InsertReminderParams struct {
	ID                       pgtype.UUID
	TenantID                 pgtype.UUID
	LeadID                   pgtype.UUID
	AssignedToMembershipID   pgtype.UUID
	CreatedByMembershipID    pgtype.UUID
	SourceCallLogID          pgtype.UUID
	Type                     string
	State                    string
	DueAt                    pgtype.Timestamptz
	Notes                    string
	SentAt                   pgtype.Timestamptz
	MarkedSentByMembershipID pgtype.UUID
	CancelledAt              pgtype.Timestamptz
	CancelledByMembershipID  pgtype.UUID
	CancelReason             string
	CreatedAt                pgtype.Timestamptz
}

// Reminder queries — crm.reminders is RLS+FORCE per slice A.2
// migration 20260603000601. RLS bind happens at WithinTxPgxTenant —
// queries here are tenant-blind.
//
// Slice surfaces:
//
//	InsertReminder              → repo Add (subscriber / cron / HTTP)
//	GetReminderByID             → repo GetByID + UpdateByID load path
//	UpdateReminderState         → repo UpdateByID persist path
//	                                (rewrites the mutable cols)
//	ListPendingRemindersPage    → cursor-paginated pending list per ADR 0038
//	FindPendingMatureForLead    → mature-lead idempotency probe
//	ListConvertedLeadsForMatureScan → mature-lead daily scan input
//
// mature-lead scan v0.2 approximation: the BRD says "no reorder in 3
// months" but crmlead doesn't track reorders at slice 1; the v0.2
// approximation uses converted_at < cutoff. v0.3 wires actual reorder
// tracking.
func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) error {
	_, err := q.db.Exec(ctx, insertReminder,
		arg.ID,
		arg.TenantID,
		arg.LeadID,
		arg.AssignedToMembershipID,
		arg.CreatedByMembershipID,
		arg.SourceCallLogID,
		arg.Type,
		arg.State,
		arg.DueAt,
		arg.Notes,
		arg.SentAt,
		arg.MarkedSentByMembershipID,
		arg.CancelledAt,
		arg.CancelledByMembershipID,
		arg.CancelReason,
		arg.CreatedAt,
	)
	return err
}

const listConvertedLeadsForMatureScanAllTenants = `-- name: ListConvertedLeadsForMatureScanAllTenants :many
SELECT id, tenant_id, assignee_membership_id, contact_name, converted_at
FROM   crm.crm_leads
WHERE  stage       = 'converted'
  AND  converted_at IS NOT NULL
  AND  converted_at < $1
  AND  assignee_membership_id IS NOT NULL
ORDER  BY tenant_id, converted_at ASC, id ASC
LIMIT  $2
`

type ListConvertedLeadsForMatureScanAllTenantsParams struct {
	ConvertedAt pgtype.Timestamptz
	Limit       int32
}

type ListConvertedLeadsForMatureScanAllTenantsRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	AssigneeMembershipID pgtype.UUID
	ContactName          string
	ConvertedAt          pgtype.Timestamptz
}

// Cross-tenant variant for the daily scan running under TxScopePlatform.
// Returns (tenant_id, lead_id, assignee, contact_name, converted_at)
// for every converted lead older than the cutoff. The river worker
// runs once per day for the whole installation; using a single
// platform-scoped query avoids a per-tenant tx round-trip when most
// tenants have no qualifying leads.
func (q *Queries) ListConvertedLeadsForMatureScanAllTenants(ctx context.Context, arg ListConvertedLeadsForMatureScanAllTenantsParams) ([]ListConvertedLeadsForMatureScanAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, listConvertedLeadsForMatureScanAllTenants, arg.ConvertedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConvertedLeadsForMatureScanAllTenantsRow
	for rows.Next() {
		var i ListConvertedLeadsForMatureScanAllTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssigneeMembershipID,
			&i.ContactName,
			&i.ConvertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRemindersPage = `-- name: ListPendingRemindersPage :many
SELECT id, tenant_id, lead_id, assigned_to_membership_id,
       created_by_membership_id, source_call_log_id,
       type, state,
       due_at, notes,
       sent_at, marked_sent_by_membership_id,
       cancelled_at, cancelled_by_membership_id, cancel_reason,
       created_at
FROM   crm.reminders
WHERE  tenant_id = $1
  AND  state = 'pending'
  AND  ($2::uuid IS NULL OR assigned_to_membership_id = $2::uuid)
  AND  ($3::text IS NULL OR type = $3::text)
  AND  ($4::uuid IS NULL OR lead_id = $4::uuid)
  AND  ($5::timestamptz IS NULL OR
        (due_at, id) > ($5::timestamptz, $6::uuid))
ORDER  BY due_at ASC, id ASC
LIMIT  $7::int
`

type ListPendingRemindersPageParams struct {
	TenantID    pgtype.UUID
	Assignee    pgtype.UUID
	Type        *string
	LeadID      pgtype.UUID
	CursorDueAt pgtype.Timestamptz
	CursorID    pgtype.UUID
	PageSize    int32
}

// Cursor (keyset) pagination on (due_at ASC, id ASC) per ADR 0038. Hot
// "today / upcoming / overdue" path uses the partial index
// idx_crm_reminders_pending_assignee_due — overdue rows surface first
// by virtue of the ASC ordering.
//
// LIMIT is $page_size + 1 (peek-one-extra) — adapter strips the extra
// row + sets HasMore based on the returned row count.
func (q *Queries) ListPendingRemindersPage(ctx context.Context, arg ListPendingRemindersPageParams) ([]CrmReminder, error) {
	rows, err := q.db.Query(ctx, listPendingRemindersPage,
		arg.TenantID,
		arg.Assignee,
		arg.Type,
		arg.LeadID,
		arg.CursorDueAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmReminder
	for rows.Next() {
		var i CrmReminder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LeadID,
			&i.AssignedToMembershipID,
			&i.CreatedByMembershipID,
			&i.SourceCallLogID,
			&i.Type,
			&i.State,
			&i.DueAt,
			&i.Notes,
			&i.SentAt,
			&i.MarkedSentByMembershipID,
			&i.CancelledAt,
			&i.CancelledByMembershipID,
			&i.CancelReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminderState = `-- name: UpdateReminderState :exec
UPDATE crm.reminders
SET    state                       = $2,
       sent_at                     = $3,
       marked_sent_by_membership_id = $4,
       cancelled_at                = $5,
       cancelled_by_membership_id  = $6,
       cancel_reason               = $7
WHERE  id = $1
`

type UpdateReminderStateParams struct {
	ID                       pgtype.UUID
	State                    string
	SentAt                   pgtype.Timestamptz
	MarkedSentByMembershipID pgtype.UUID
	CancelledAt              pgtype.Timestamptz
	CancelledByMembershipID  pgtype.UUID
	CancelReason             string
}

// Rewrites the mutable lifecycle columns. tenant_id + lead_id +
// assigned_to + created_by + source_call_log_id + type + due_at +
// notes + created_at are aggregate-immutable — this query
// intentionally does NOT write them.
func (q *Queries) UpdateReminderState(ctx context.Context, arg UpdateReminderStateParams) error {
	_, err := q.db.Exec(ctx, updateReminderState,
		arg.ID,
		arg.State,
		arg.SentAt,
		arg.MarkedSentByMembershipID,
		arg.CancelledAt,
		arg.CancelledByMembershipID,
		arg.CancelReason,
	)
	return err
}
