// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package adapters

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveMembershipByPersonAndTenant = `-- name: GetActiveMembershipByPersonAndTenant :one
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to
FROM   identity.tenant_memberships
WHERE  person_id = $1
  AND  tenant_id = $2
  AND  status    = 'active'
`

type GetActiveMembershipByPersonAndTenantParams struct {
	PersonID pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) GetActiveMembershipByPersonAndTenant(ctx context.Context, arg GetActiveMembershipByPersonAndTenantParams) (IdentityTenantMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByPersonAndTenant, arg.PersonID, arg.TenantID)
	var i IdentityTenantMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Designation,
		&i.Department,
		&i.StatusMessage,
		&i.ReportsTo,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to
FROM   identity.tenant_memberships
WHERE  id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id pgtype.UUID) (IdentityTenantMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i IdentityTenantMembership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Designation,
		&i.Department,
		&i.StatusMessage,
		&i.ReportsTo,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :exec

INSERT INTO identity.tenant_memberships (
    id, person_id, tenant_id, status, joined_at
) VALUES ($1, $2, $3, $4, $5)
`

type InsertMembershipParams struct {
	ID       pgtype.UUID
	PersonID pgtype.UUID
	TenantID pgtype.UUID
	Status   string
	JoinedAt pgtype.Timestamptz
}

// Membership queries — identity.tenant_memberships is RLS+FORCE.
// Reads through this query path see only the current tenant's rows
// unless app.is_platform=true. Cross-tenant resolution lives on the
// non-RLS auth_routing index (TBD), not here.
func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership,
		arg.ID,
		arg.PersonID,
		arg.TenantID,
		arg.Status,
		arg.JoinedAt,
	)
	return err
}

const listMembershipsForPerson = `-- name: ListMembershipsForPerson :many
SELECT id, person_id, tenant_id, status, joined_at, left_at,
       designation, department, status_message, reports_to
FROM   identity.tenant_memberships
WHERE  person_id = $1
ORDER  BY joined_at
`

// Cross-tenant list of a Person's memberships. RLS filters to current
// tenant unless platform-bypass is set; cross-tenant enumeration runs
// under platform context (anonymise / global-suspend cascade flows).
func (q *Queries) ListMembershipsForPerson(ctx context.Context, personID pgtype.UUID) ([]IdentityTenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityTenantMembership
	for rows.Next() {
		var i IdentityTenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Designation,
			&i.Department,
			&i.StatusMessage,
			&i.ReportsTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :exec
UPDATE identity.tenant_memberships
SET    status  = $2,
       left_at = $3
WHERE  id = $1
`

type UpdateMembershipStatusParams struct {
	ID     pgtype.UUID
	Status string
	LeftAt pgtype.Timestamptz
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) error {
	_, err := q.db.Exec(ctx, updateMembershipStatus, arg.ID, arg.Status, arg.LeftAt)
	return err
}
