// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adapters

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Cross-tenant email→tenant index for login. NOT RLS-scoped (intentional — login flow predates tenant context). Maintained via Watermill events.
type IdentityAuthRouting struct {
	Email          string
	PersonID       pgtype.UUID
	ActiveTenantID pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

// Domain events written same-tx as aggregate state. Watermill SQL forwarder polls + republishes. Doubles as audit log per ADR 0027.
type IdentityOutbox struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Topic       string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Forwarded   bool
	ForwardedAt pgtype.Timestamptz
}

// Person aggregate. Global identity (Auth0/Entra ID pattern). NOT tenant-scoped.
type IdentityPerson struct {
	ID            pgtype.UUID
	Email         string
	FirstName     string
	LastName      string
	PasswordHash  string
	SecurityStamp pgtype.UUID
	IsActive      bool
	IsAnonymised  bool
	CreatedAt     pgtype.Timestamptz
	AnonymisedAt  pgtype.Timestamptz
}

// Individual tokens within a family. Hash-only storage; plaintext NEVER persisted. RFC 9700 reuse detection in domain layer.
type IdentityRefreshToken struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	TokenHash    string
	Generation   int32
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

// Refresh-token family per RFC 9700 §4.13 + ADR 0011. NOT tenant-scoped — session-management infrastructure.
type IdentityRefreshTokenFamily struct {
	ID           pgtype.UUID
	PersonID     pgtype.UUID
	TenantID     pgtype.UUID
	DeviceLabel  string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Tenant aggregate root. Each row IS a tenant; not tenant-scoped (no RLS).
type IdentityTenant struct {
	ID          pgtype.UUID
	Slug        string
	LegalName   string
	DisplayName string
	AdminEmail  string
	Status      string
	CreatedAt   pgtype.Timestamptz
	ActivatedAt pgtype.Timestamptz
	SuspendedAt pgtype.Timestamptz
}

// Per-tenant junction (Person ↔ Tenant). Tenant-scoped, FORCE RLS. Single-Active-Membership invariant via partial unique index.
type IdentityTenantMembership struct {
	ID       pgtype.UUID
	PersonID pgtype.UUID
	TenantID pgtype.UUID
	Status   string
	JoinedAt pgtype.Timestamptz
	LeftAt   pgtype.Timestamptz
}
