// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persons.sql

package adapters

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymisePerson = `-- name: AnonymisePerson :exec
UPDATE identity.persons
SET    email          = $2,
       first_name     = '',
       last_name      = '',
       password_hash  = '',
       security_stamp = $3,
       is_active      = false,
       is_anonymised  = true,
       anonymised_at  = $4
WHERE  id = $1
`

type AnonymisePersonParams struct {
	ID            pgtype.UUID
	Email         string
	SecurityStamp pgtype.UUID
	AnonymisedAt  pgtype.Timestamptz
}

func (q *Queries) AnonymisePerson(ctx context.Context, arg AnonymisePersonParams) error {
	_, err := q.db.Exec(ctx, anonymisePerson,
		arg.ID,
		arg.Email,
		arg.SecurityStamp,
		arg.AnonymisedAt,
	)
	return err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, email, first_name, last_name, password_hash, security_stamp,
       is_active, is_anonymised, created_at, anonymised_at
FROM   identity.persons
WHERE  email = $1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (IdentityPerson, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i IdentityPerson
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.SecurityStamp,
		&i.IsActive,
		&i.IsAnonymised,
		&i.CreatedAt,
		&i.AnonymisedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, email, first_name, last_name, password_hash, security_stamp,
       is_active, is_anonymised, created_at, anonymised_at
FROM   identity.persons
WHERE  id = $1
`

func (q *Queries) GetPersonByID(ctx context.Context, id pgtype.UUID) (IdentityPerson, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i IdentityPerson
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.SecurityStamp,
		&i.IsActive,
		&i.IsAnonymised,
		&i.CreatedAt,
		&i.AnonymisedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :exec

INSERT INTO identity.persons (
    id, email, first_name, last_name, password_hash, security_stamp,
    is_active, is_anonymised, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPersonParams struct {
	ID            pgtype.UUID
	Email         string
	FirstName     string
	LastName      string
	PasswordHash  string
	SecurityStamp pgtype.UUID
	IsActive      bool
	IsAnonymised  bool
	CreatedAt     pgtype.Timestamptz
}

// Person queries — identity.persons is non-RLS (global identity).
// Email is globally unique; lookup by email is the entry point for login
// + password-reset + email-change flows per multi-tenancy.md "Identity model".
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.Exec(ctx, insertPerson,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.SecurityStamp,
		arg.IsActive,
		arg.IsAnonymised,
		arg.CreatedAt,
	)
	return err
}

const updatePersonPassword = `-- name: UpdatePersonPassword :exec
UPDATE identity.persons
SET    password_hash  = $2,
       security_stamp = $3
WHERE  id = $1
`

type UpdatePersonPasswordParams struct {
	ID            pgtype.UUID
	PasswordHash  string
	SecurityStamp pgtype.UUID
}

func (q *Queries) UpdatePersonPassword(ctx context.Context, arg UpdatePersonPasswordParams) error {
	_, err := q.db.Exec(ctx, updatePersonPassword, arg.ID, arg.PasswordHash, arg.SecurityStamp)
	return err
}
