// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package adapters

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, family_id, token_hash, generation,
       issued_at, expires_at, consumed_at, replaced_by_id
FROM   identity.refresh_tokens
WHERE  token_hash = $1
`

// Single indexed lookup by token hash — the rotation flow's entry point.
// Returns the token row; caller resolves the family via family_id.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.TokenHash,
		&i.Generation,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getRefreshTokenFamilyByID = `-- name: GetRefreshTokenFamilyByID :one
SELECT id, person_id, tenant_id, device_label,
       created_at, last_used_at, revoked_at, revoke_reason
FROM   identity.refresh_token_families
WHERE  id = $1
`

func (q *Queries) GetRefreshTokenFamilyByID(ctx context.Context, id pgtype.UUID) (IdentityRefreshTokenFamily, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenFamilyByID, id)
	var i IdentityRefreshTokenFamily
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO identity.refresh_tokens (
    id, family_id, token_hash, generation,
    issued_at, expires_at, consumed_at, replaced_by_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRefreshTokenParams struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	TokenHash    string
	Generation   int32
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.FamilyID,
		arg.TokenHash,
		arg.Generation,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.ReplacedByID,
	)
	return err
}

const insertRefreshTokenFamily = `-- name: InsertRefreshTokenFamily :exec

INSERT INTO identity.refresh_token_families (
    id, person_id, tenant_id, device_label,
    created_at, last_used_at, revoked_at, revoke_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRefreshTokenFamilyParams struct {
	ID           pgtype.UUID
	PersonID     pgtype.UUID
	TenantID     pgtype.UUID
	DeviceLabel  string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Refresh-token queries — both family and child-token tables are non-RLS
// (session-management infrastructure). Token-hash uniqueness is the
// load-bearing isolation per Auth0/Okta canon. tenant_id travels as
// data column for context, not as RLS scope.
func (q *Queries) InsertRefreshTokenFamily(ctx context.Context, arg InsertRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, insertRefreshTokenFamily,
		arg.ID,
		arg.PersonID,
		arg.TenantID,
		arg.DeviceLabel,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	return err
}

const listRefreshTokensInFamily = `-- name: ListRefreshTokensInFamily :many
SELECT id, family_id, token_hash, generation,
       issued_at, expires_at, consumed_at, replaced_by_id
FROM   identity.refresh_tokens
WHERE  family_id = $1
ORDER  BY generation
`

func (q *Queries) ListRefreshTokensInFamily(ctx context.Context, familyID pgtype.UUID) ([]IdentityRefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensInFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRefreshToken
	for rows.Next() {
		var i IdentityRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.TokenHash,
			&i.Generation,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ReplacedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRefreshTokenFamilyLastUsed = `-- name: TouchRefreshTokenFamilyLastUsed :exec
UPDATE identity.refresh_token_families
SET    last_used_at = $2
WHERE  id = $1
`

type TouchRefreshTokenFamilyLastUsedParams struct {
	ID         pgtype.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchRefreshTokenFamilyLastUsed(ctx context.Context, arg TouchRefreshTokenFamilyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchRefreshTokenFamilyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateRefreshTokenConsumed = `-- name: UpdateRefreshTokenConsumed :exec
UPDATE identity.refresh_tokens
SET    consumed_at    = $2,
       replaced_by_id = $3
WHERE  id = $1
`

type UpdateRefreshTokenConsumedParams struct {
	ID           pgtype.UUID
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

func (q *Queries) UpdateRefreshTokenConsumed(ctx context.Context, arg UpdateRefreshTokenConsumedParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenConsumed, arg.ID, arg.ConsumedAt, arg.ReplacedByID)
	return err
}

const updateRefreshTokenFamilyRevoked = `-- name: UpdateRefreshTokenFamilyRevoked :exec
UPDATE identity.refresh_token_families
SET    revoked_at    = $2,
       revoke_reason = $3
WHERE  id = $1
`

type UpdateRefreshTokenFamilyRevokedParams struct {
	ID           pgtype.UUID
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

func (q *Queries) UpdateRefreshTokenFamilyRevoked(ctx context.Context, arg UpdateRefreshTokenFamilyRevokedParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenFamilyRevoked, arg.ID, arg.RevokedAt, arg.RevokeReason)
	return err
}
