// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package adapters

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, family_id, token_hash, generation,
       issued_at, expires_at, consumed_at, replaced_by_id
FROM   identity.refresh_tokens
WHERE  token_hash = $1
`

// Single indexed lookup by token hash — the rotation flow's entry point.
// Returns the token row; caller resolves the family via family_id.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.TokenHash,
		&i.Generation,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getRefreshTokenFamilyByID = `-- name: GetRefreshTokenFamilyByID :one
SELECT id, person_id, tenant_id, device_label,
       created_at, last_used_at, revoked_at, revoke_reason
FROM   identity.refresh_token_families
WHERE  id = $1
`

func (q *Queries) GetRefreshTokenFamilyByID(ctx context.Context, id pgtype.UUID) (IdentityRefreshTokenFamily, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenFamilyByID, id)
	var i IdentityRefreshTokenFamily
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.TenantID,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const insertRefreshTokenFamily = `-- name: InsertRefreshTokenFamily :exec

INSERT INTO identity.refresh_token_families (
    id, person_id, tenant_id, device_label,
    created_at, last_used_at, revoked_at, revoke_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRefreshTokenFamilyParams struct {
	ID           pgtype.UUID
	PersonID     pgtype.UUID
	TenantID     pgtype.UUID
	DeviceLabel  string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Refresh-token queries — both family and child-token tables are non-RLS
// (session-management infrastructure). Token-hash uniqueness is the
// load-bearing isolation per Auth0/Okta canon. tenant_id travels as
// data column for context, not as RLS scope.
func (q *Queries) InsertRefreshTokenFamily(ctx context.Context, arg InsertRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, insertRefreshTokenFamily,
		arg.ID,
		arg.PersonID,
		arg.TenantID,
		arg.DeviceLabel,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	return err
}

const listActiveFamiliesForPerson = `-- name: ListActiveFamiliesForPerson :many
SELECT id, person_id, tenant_id, device_label,
       created_at, last_used_at, revoked_at, revoke_reason
FROM   identity.refresh_token_families
WHERE  person_id  = $1
  AND  revoked_at IS NULL
ORDER  BY created_at
`

// Lists every non-revoked refresh-token family for a Person across
// tenants. Used by the post-security-event revocation cascade
// (RevokeFamiliesOnSecurityChange) and the user "manage sessions" UI.
// Cross-tenant query; non-RLS table per refresh_token canon.
func (q *Queries) ListActiveFamiliesForPerson(ctx context.Context, personID pgtype.UUID) ([]IdentityRefreshTokenFamily, error) {
	rows, err := q.db.Query(ctx, listActiveFamiliesForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRefreshTokenFamily
	for rows.Next() {
		var i IdentityRefreshTokenFamily
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.TenantID,
			&i.DeviceLabel,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefreshTokensInFamily = `-- name: ListRefreshTokensInFamily :many
SELECT id, family_id, token_hash, generation,
       issued_at, expires_at, consumed_at, replaced_by_id
FROM   identity.refresh_tokens
WHERE  family_id = $1
ORDER  BY generation
`

func (q *Queries) ListRefreshTokensInFamily(ctx context.Context, familyID pgtype.UUID) ([]IdentityRefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensInFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRefreshToken
	for rows.Next() {
		var i IdentityRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.TokenHash,
			&i.Generation,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ReplacedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefreshTokenFamily = `-- name: UpdateRefreshTokenFamily :exec
UPDATE identity.refresh_token_families
SET    last_used_at  = $2,
       revoked_at    = $3,
       revoke_reason = $4
WHERE  id = $1
`

type UpdateRefreshTokenFamilyParams struct {
	ID           pgtype.UUID
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokeReason *string
}

// Persists family-level mutable state: last_used_at on every rotate;
// revoked_at + revoke_reason on Revoke or reuse-detected.
func (q *Queries) UpdateRefreshTokenFamily(ctx context.Context, arg UpdateRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenFamily,
		arg.ID,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	return err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :exec
INSERT INTO identity.refresh_tokens (
    id, family_id, token_hash, generation,
    issued_at, expires_at, consumed_at, replaced_by_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    consumed_at    = EXCLUDED.consumed_at,
    replaced_by_id = EXCLUDED.replaced_by_id
`

type UpsertRefreshTokenParams struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	TokenHash    string
	Generation   int32
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	ReplacedByID pgtype.UUID
}

// INSERT-then-UPDATE-on-conflict by token id. The family aggregate
// emits the FULL token list on persist; rows whose (consumed_at,
// replaced_by_id) changed are updated, fresh tokens are inserted.
// Token id, hash, generation, issued_at, expires_at, family_id are
// immutable post-issuance; only the consumed columns rotate.
func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, upsertRefreshToken,
		arg.ID,
		arg.FamilyID,
		arg.TokenHash,
		arg.Generation,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.ReplacedByID,
	)
	return err
}
