// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package adapters

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, legal_name, display_name, admin_email, status,
       created_at, activated_at, suspended_at
FROM   identity.tenants
WHERE  id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (IdentityTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i IdentityTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.LegalName,
		&i.DisplayName,
		&i.AdminEmail,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, legal_name, display_name, admin_email, status,
       created_at, activated_at, suspended_at
FROM   identity.tenants
WHERE  slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (IdentityTenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i IdentityTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.LegalName,
		&i.DisplayName,
		&i.AdminEmail,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :exec

INSERT INTO identity.tenants (
    id, slug, legal_name, display_name, admin_email, status, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTenantParams struct {
	ID          pgtype.UUID
	Slug        string
	LegalName   string
	DisplayName string
	AdminEmail  string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

// Tenant queries — identity.tenants is non-RLS (each row IS a tenant).
// Lookups are unscoped; tenant resolution is the load-bearing isolation
// elsewhere (membership lookup binds the tenant_id GUC for RLS).
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Slug,
		arg.LegalName,
		arg.DisplayName,
		arg.AdminEmail,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE identity.tenants
SET    status       = $2,
       activated_at = $3,
       suspended_at = $4
WHERE  id = $1
`

type UpdateTenantStatusParams struct {
	ID          pgtype.UUID
	Status      string
	ActivatedAt pgtype.Timestamptz
	SuspendedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus,
		arg.ID,
		arg.Status,
		arg.ActivatedAt,
		arg.SuspendedAt,
	)
	return err
}
