// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardCounts = `-- name: DashboardCounts :one
WITH scoped AS (
    SELECT state, due_at, completed_at, assigned_to_membership_id
    FROM   tasks.work_items
    WHERE  tenant_id = $2::uuid
      AND  NOT is_deleted
      AND  ($3::uuid[] IS NULL
            OR assigned_to_membership_id = ANY($3::uuid[]))
)
SELECT
    COUNT(*) FILTER (
        WHERE state IN ('pending', 'in_progress')
          AND date_trunc('day', due_at AT TIME ZONE 'UTC')
              = date_trunc('day', $1::timestamptz AT TIME ZONE 'UTC')
    ) AS today,
    COUNT(*) FILTER (
        WHERE state IN ('pending', 'in_progress')
          AND date_trunc('day', due_at AT TIME ZONE 'UTC')
              > date_trunc('day', $1::timestamptz AT TIME ZONE 'UTC')
    ) AS upcoming,
    COUNT(*) FILTER (WHERE state = 'overdue') AS overdue,
    COUNT(*) FILTER (
        WHERE state = 'completed'
          AND completed_at IS NOT NULL
          AND date_trunc('day', completed_at AT TIME ZONE 'UTC')
              = date_trunc('day', $1::timestamptz AT TIME ZONE 'UTC')
    ) AS completed_today,
    COUNT(*) FILTER (WHERE state = 'pending') AS total_pending
FROM scoped
`

type DashboardCountsParams struct {
	AsOf                 pgtype.Timestamptz
	TenantID             pgtype.UUID
	VisibleMembershipIds []pgtype.UUID
}

type DashboardCountsRow struct {
	Today          int64
	Upcoming       int64
	Overdue        int64
	CompletedToday int64
	TotalPending   int64
}

// Single-query CTE produces the BRD §6.8 dashboard counts:
//
//	today           — open tasks due on the same UTC day as as_of
//	upcoming        — open tasks due after as_of's UTC day
//	overdue         — tasks in StateOverdue
//	completed_today — tasks completed on the same UTC day as as_of
//	total_pending   — tasks in StatePending
//
// visible_membership_ids is an optional uuid[] — when non-NULL the
// counts span only those memberships (team view); when NULL the counts
// span every membership in the tenant.
func (q *Queries) DashboardCounts(ctx context.Context, arg DashboardCountsParams) (DashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardCounts, arg.AsOf, arg.TenantID, arg.VisibleMembershipIds)
	var i DashboardCountsRow
	err := row.Scan(
		&i.Today,
		&i.Upcoming,
		&i.Overdue,
		&i.CompletedToday,
		&i.TotalPending,
	)
	return i, err
}

const getOpenWorkItemBySource = `-- name: GetOpenWorkItemBySource :one
SELECT id, tenant_id, type, priority, state,
       title, description,
       assigned_to_membership_id, assigned_by_membership_id,
       due_at, completed_at, cancelled_at, cancellation_reason,
       batch_id, source_module, source_entity_type, source_entity_id,
       created_at, created_by_membership_id
FROM   tasks.work_items
WHERE  source_entity_type = $1
  AND  source_entity_id   = $2
  AND  state IN ('pending', 'in_progress')
  AND  NOT is_deleted
LIMIT  1
`

type GetOpenWorkItemBySourceParams struct {
	SourceEntityType *string
	SourceEntityID   *string
}

type GetOpenWorkItemBySourceRow struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

func (q *Queries) GetOpenWorkItemBySource(ctx context.Context, arg GetOpenWorkItemBySourceParams) (GetOpenWorkItemBySourceRow, error) {
	row := q.db.QueryRow(ctx, getOpenWorkItemBySource, arg.SourceEntityType, arg.SourceEntityID)
	var i GetOpenWorkItemBySourceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Priority,
		&i.State,
		&i.Title,
		&i.Description,
		&i.AssignedToMembershipID,
		&i.AssignedByMembershipID,
		&i.DueAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.BatchID,
		&i.SourceModule,
		&i.SourceEntityType,
		&i.SourceEntityID,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getWorkItemByID = `-- name: GetWorkItemByID :one
SELECT id, tenant_id, type, priority, state,
       title, description,
       assigned_to_membership_id, assigned_by_membership_id,
       due_at, completed_at, cancelled_at, cancellation_reason,
       batch_id, source_module, source_entity_type, source_entity_id,
       created_at, created_by_membership_id
FROM   tasks.work_items
WHERE  id = $1
  AND  NOT is_deleted
`

type GetWorkItemByIDRow struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

func (q *Queries) GetWorkItemByID(ctx context.Context, id pgtype.UUID) (GetWorkItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkItemByID, id)
	var i GetWorkItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Priority,
		&i.State,
		&i.Title,
		&i.Description,
		&i.AssignedToMembershipID,
		&i.AssignedByMembershipID,
		&i.DueAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.BatchID,
		&i.SourceModule,
		&i.SourceEntityType,
		&i.SourceEntityID,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertWorkItem = `-- name: InsertWorkItem :exec

INSERT INTO tasks.work_items (
    id, tenant_id, type, priority, state,
    title, description,
    assigned_to_membership_id, assigned_by_membership_id,
    due_at, completed_at, cancelled_at, cancellation_reason,
    batch_id, source_module, source_entity_type, source_entity_id,
    created_at, created_by_membership_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19
)
`

type InsertWorkItemParams struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

// WorkItem queries — tasks.work_items is RLS+FORCE per ADR 0006 +
// migration 20260604000001. Reads/writes flow through RLS: only the
// current tenant's rows are visible unless app.is_platform=true.
//
// Slice 1 surfaces:
//
//	InsertWorkItem            → repo Add path
//	GetWorkItemByID           → repo GetByID + UpdateByID load path
//	GetOpenWorkItemBySource   → auto-complete-by-source lookup
//	UpdateWorkItem            → repo UpdateByID persist path
//	ListWorkItemsPage         → cursor-paginated list per ADR 0038
//	ListOverdueCandidates     → periodic overdue-scan job
//	ListPurgeCandidates       → daily purge job
//	SoftDeleteWorkItem        → purge job's tombstone flip
//	DashboardCounts           → per-membership / per-team tallies
func (q *Queries) InsertWorkItem(ctx context.Context, arg InsertWorkItemParams) error {
	_, err := q.db.Exec(ctx, insertWorkItem,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Priority,
		arg.State,
		arg.Title,
		arg.Description,
		arg.AssignedToMembershipID,
		arg.AssignedByMembershipID,
		arg.DueAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancellationReason,
		arg.BatchID,
		arg.SourceModule,
		arg.SourceEntityType,
		arg.SourceEntityID,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const listOverdueCandidates = `-- name: ListOverdueCandidates :many
SELECT id, tenant_id, type, priority, state,
       title, description,
       assigned_to_membership_id, assigned_by_membership_id,
       due_at, completed_at, cancelled_at, cancellation_reason,
       batch_id, source_module, source_entity_type, source_entity_id,
       created_at, created_by_membership_id
FROM   tasks.work_items
WHERE  NOT is_deleted
  AND  state IN ('pending', 'in_progress')
  AND  due_at < $1::timestamptz
  AND  ($2::uuid IS NULL OR tenant_id = $2::uuid)
ORDER  BY due_at ASC
LIMIT  $3::int
`

type ListOverdueCandidatesParams struct {
	AsOf     pgtype.Timestamptz
	TenantID pgtype.UUID
	RowLimit int32
}

type ListOverdueCandidatesRow struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

// Cross-tenant scan for the periodic overdue-scan job. The forwarder /
// job runs under TxScopePlatform so RLS sees all tenants; the optional
// tenant_id narg constrains to one tenant for testing.
func (q *Queries) ListOverdueCandidates(ctx context.Context, arg ListOverdueCandidatesParams) ([]ListOverdueCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listOverdueCandidates, arg.AsOf, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueCandidatesRow
	for rows.Next() {
		var i ListOverdueCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Priority,
			&i.State,
			&i.Title,
			&i.Description,
			&i.AssignedToMembershipID,
			&i.AssignedByMembershipID,
			&i.DueAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.BatchID,
			&i.SourceModule,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.CreatedAt,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeCandidates = `-- name: ListPurgeCandidates :many
SELECT id, tenant_id, type, priority, state,
       title, description,
       assigned_to_membership_id, assigned_by_membership_id,
       due_at, completed_at, cancelled_at, cancellation_reason,
       batch_id, source_module, source_entity_type, source_entity_id,
       created_at, created_by_membership_id
FROM   tasks.work_items
WHERE  NOT is_deleted
  AND  state IN ('completed', 'cancelled')
  AND  COALESCE(completed_at, cancelled_at) < $1::timestamptz
  AND  ($2::uuid IS NULL OR tenant_id = $2::uuid)
LIMIT  $3::int
`

type ListPurgeCandidatesParams struct {
	Before   pgtype.Timestamptz
	TenantID pgtype.UUID
	RowLimit int32
}

type ListPurgeCandidatesRow struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

// Cross-tenant scan for the daily purge job. Terminal rows whose
// terminal timestamp predates `before` are returned.
func (q *Queries) ListPurgeCandidates(ctx context.Context, arg ListPurgeCandidatesParams) ([]ListPurgeCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPurgeCandidates, arg.Before, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurgeCandidatesRow
	for rows.Next() {
		var i ListPurgeCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Priority,
			&i.State,
			&i.Title,
			&i.Description,
			&i.AssignedToMembershipID,
			&i.AssignedByMembershipID,
			&i.DueAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.BatchID,
			&i.SourceModule,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.CreatedAt,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsPage = `-- name: ListWorkItemsPage :many
SELECT id, tenant_id, type, priority, state,
       title, description,
       assigned_to_membership_id, assigned_by_membership_id,
       due_at, completed_at, cancelled_at, cancellation_reason,
       batch_id, source_module, source_entity_type, source_entity_id,
       created_at, created_by_membership_id
FROM   tasks.work_items
WHERE  tenant_id = $1
  AND  NOT is_deleted
  AND  ($2::text    IS NULL OR state    = $2::text)
  AND  ($3::text     IS NULL OR type     = $3::text)
  AND  ($4::text IS NULL OR priority = $4::text)
  AND  ($5::uuid IS NULL OR assigned_to_membership_id = $5::uuid)
  AND  ($6::uuid IS NULL OR assigned_to_membership_id = $6::uuid)
  AND  ($7::uuid IS NULL OR batch_id = $7::uuid)
  AND  ($8::timestamptz IS NULL OR due_at <  $8::timestamptz)
  AND  ($9::timestamptz  IS NULL OR due_at >  $9::timestamptz)
  AND  ($10::timestamptz IS NULL OR
        (due_at, id) < ($10::timestamptz, $11::uuid))
ORDER  BY due_at DESC, id DESC
LIMIT  $12::int
`

type ListWorkItemsPageParams struct {
	TenantID     pgtype.UUID
	State        *string
	Type         *string
	Priority     *string
	Assignee     pgtype.UUID
	SelfAssignee pgtype.UUID
	BatchID      pgtype.UUID
	DueBefore    pgtype.Timestamptz
	DueAfter     pgtype.Timestamptz
	CursorDueAt  pgtype.Timestamptz
	CursorID     pgtype.UUID
	PageSize     int32
}

type ListWorkItemsPageRow struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Type                   string
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	AssignedByMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	BatchID                pgtype.UUID
	SourceModule           string
	SourceEntityType       *string
	SourceEntityID         *string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

// Cursor (keyset) pagination on (due_at, id) DESC per ADR 0038.
// Composite filter columns supplied as nullable params.
func (q *Queries) ListWorkItemsPage(ctx context.Context, arg ListWorkItemsPageParams) ([]ListWorkItemsPageRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemsPage,
		arg.TenantID,
		arg.State,
		arg.Type,
		arg.Priority,
		arg.Assignee,
		arg.SelfAssignee,
		arg.BatchID,
		arg.DueBefore,
		arg.DueAfter,
		arg.CursorDueAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkItemsPageRow
	for rows.Next() {
		var i ListWorkItemsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Priority,
			&i.State,
			&i.Title,
			&i.Description,
			&i.AssignedToMembershipID,
			&i.AssignedByMembershipID,
			&i.DueAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.BatchID,
			&i.SourceModule,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.CreatedAt,
			&i.CreatedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkItem = `-- name: SoftDeleteWorkItem :exec
UPDATE tasks.work_items
SET    is_deleted = true
WHERE  id = $1
  AND  NOT is_deleted
`

func (q *Queries) SoftDeleteWorkItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWorkItem, id)
	return err
}

const updateWorkItem = `-- name: UpdateWorkItem :exec
UPDATE tasks.work_items
SET    priority                  = $2,
       state                     = $3,
       title                     = $4,
       description               = $5,
       assigned_to_membership_id = $6,
       due_at                    = $7,
       completed_at              = $8,
       cancelled_at              = $9,
       cancellation_reason       = $10
WHERE  id = $1
  AND  NOT is_deleted
`

type UpdateWorkItemParams struct {
	ID                     pgtype.UUID
	Priority               string
	State                  string
	Title                  string
	Description            string
	AssignedToMembershipID pgtype.UUID
	DueAt                  pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
}

// Persists the mutable WorkItem state. tenant_id + type + source_* +
// created_at + created_by_membership_id are aggregate-immutable.
func (q *Queries) UpdateWorkItem(ctx context.Context, arg UpdateWorkItemParams) error {
	_, err := q.db.Exec(ctx, updateWorkItem,
		arg.ID,
		arg.Priority,
		arg.State,
		arg.Title,
		arg.Description,
		arg.AssignedToMembershipID,
		arg.DueAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancellationReason,
	)
	return err
}
