// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credit_notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCreditNoteByID = `-- name: GetCreditNoteByID :one
SELECT id, tenant_id, invoice_id,
       number_kind, number_financial_year, number_seq, number_display,
       reason, amount_paise,
       issued_at, issued_by_membership_id
FROM   orders.credit_notes
WHERE  id = $1
`

func (q *Queries) GetCreditNoteByID(ctx context.Context, id pgtype.UUID) (OrdersCreditNote, error) {
	row := q.db.QueryRow(ctx, getCreditNoteByID, id)
	var i OrdersCreditNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.NumberKind,
		&i.NumberFinancialYear,
		&i.NumberSeq,
		&i.NumberDisplay,
		&i.Reason,
		&i.AmountPaise,
		&i.IssuedAt,
		&i.IssuedByMembershipID,
	)
	return i, err
}

const insertCreditNote = `-- name: InsertCreditNote :exec

INSERT INTO orders.credit_notes (
    id, tenant_id, invoice_id,
    number_kind, number_financial_year, number_seq, number_display,
    reason, amount_paise,
    issued_at, issued_by_membership_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9,
    $10, $11
)
`

type InsertCreditNoteParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	InvoiceID            pgtype.UUID
	NumberKind           string
	NumberFinancialYear  string
	NumberSeq            int64
	NumberDisplay        string
	Reason               string
	AmountPaise          int64
	IssuedAt             pgtype.Timestamptz
	IssuedByMembershipID pgtype.UUID
}

// Orders module — CreditNote queries (BRD §A-014). Append-only. Tenant
// scoping via RLS.
func (q *Queries) InsertCreditNote(ctx context.Context, arg InsertCreditNoteParams) error {
	_, err := q.db.Exec(ctx, insertCreditNote,
		arg.ID,
		arg.TenantID,
		arg.InvoiceID,
		arg.NumberKind,
		arg.NumberFinancialYear,
		arg.NumberSeq,
		arg.NumberDisplay,
		arg.Reason,
		arg.AmountPaise,
		arg.IssuedAt,
		arg.IssuedByMembershipID,
	)
	return err
}

const listCreditNotesByInvoice = `-- name: ListCreditNotesByInvoice :many
SELECT id, tenant_id, invoice_id,
       number_kind, number_financial_year, number_seq, number_display,
       reason, amount_paise,
       issued_at, issued_by_membership_id
FROM   orders.credit_notes
WHERE  invoice_id = $1
ORDER  BY issued_at, id
`

func (q *Queries) ListCreditNotesByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]OrdersCreditNote, error) {
	rows, err := q.db.Query(ctx, listCreditNotesByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersCreditNote
	for rows.Next() {
		var i OrdersCreditNote
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.NumberKind,
			&i.NumberFinancialYear,
			&i.NumberSeq,
			&i.NumberDisplay,
			&i.Reason,
			&i.AmountPaise,
			&i.IssuedAt,
			&i.IssuedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
