// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_number_sequences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateInvoiceNumber = `-- name: AllocateInvoiceNumber :one
UPDATE orders.invoice_number_sequences
SET    last_used = last_used + 1
WHERE  tenant_id = $1
  AND  financial_year = $2
  AND  kind = $3
RETURNING last_used
`

type AllocateInvoiceNumberParams struct {
	TenantID      pgtype.UUID
	FinancialYear string
	Kind          string
}

func (q *Queries) AllocateInvoiceNumber(ctx context.Context, arg AllocateInvoiceNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateInvoiceNumber, arg.TenantID, arg.FinancialYear, arg.Kind)
	var last_used int64
	err := row.Scan(&last_used)
	return last_used, err
}

const ensureInvoiceNumberSequence = `-- name: EnsureInvoiceNumberSequence :exec

INSERT INTO orders.invoice_number_sequences (tenant_id, financial_year, kind, last_used)
VALUES ($1, $2, $3, 0)
ON CONFLICT (tenant_id, financial_year, kind) DO NOTHING
`

type EnsureInvoiceNumberSequenceParams struct {
	TenantID      pgtype.UUID
	FinancialYear string
	Kind          string
}

// Gapless invoice-number allocation (ADR 0063 §3). The allocator runs both
// statements inside the order's UoW tx: a rollback rolls back the increment,
// so the per-(tenant, FY, kind) sequence never gaps.
func (q *Queries) EnsureInvoiceNumberSequence(ctx context.Context, arg EnsureInvoiceNumberSequenceParams) error {
	_, err := q.db.Exec(ctx, ensureInvoiceNumberSequence, arg.TenantID, arg.FinancialYear, arg.Kind)
	return err
}
