// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, tenant_id, order_id,
       number_kind, number_financial_year, number_seq, number_display,
       line_items, tax_lines, subtotal_paise, tax_paise, grand_total_paise,
       issued_at, issued_by_membership_id
FROM   orders.invoices
WHERE  id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (OrdersInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i OrdersInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.NumberKind,
		&i.NumberFinancialYear,
		&i.NumberSeq,
		&i.NumberDisplay,
		&i.LineItems,
		&i.TaxLines,
		&i.SubtotalPaise,
		&i.TaxPaise,
		&i.GrandTotalPaise,
		&i.IssuedAt,
		&i.IssuedByMembershipID,
	)
	return i, err
}

const getInvoiceByOrderID = `-- name: GetInvoiceByOrderID :one
SELECT id, tenant_id, order_id,
       number_kind, number_financial_year, number_seq, number_display,
       line_items, tax_lines, subtotal_paise, tax_paise, grand_total_paise,
       issued_at, issued_by_membership_id
FROM   orders.invoices
WHERE  order_id = $1
`

func (q *Queries) GetInvoiceByOrderID(ctx context.Context, orderID pgtype.UUID) (OrdersInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByOrderID, orderID)
	var i OrdersInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.NumberKind,
		&i.NumberFinancialYear,
		&i.NumberSeq,
		&i.NumberDisplay,
		&i.LineItems,
		&i.TaxLines,
		&i.SubtotalPaise,
		&i.TaxPaise,
		&i.GrandTotalPaise,
		&i.IssuedAt,
		&i.IssuedByMembershipID,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :exec

INSERT INTO orders.invoices (
    id, tenant_id, order_id,
    number_kind, number_financial_year, number_seq, number_display,
    line_items, tax_lines, subtotal_paise, tax_paise, grand_total_paise,
    issued_at, issued_by_membership_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
`

type InsertInvoiceParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	OrderID              pgtype.UUID
	NumberKind           string
	NumberFinancialYear  string
	NumberSeq            int64
	NumberDisplay        string
	LineItems            []byte
	TaxLines             []byte
	SubtotalPaise        int64
	TaxPaise             int64
	GrandTotalPaise      int64
	IssuedAt             pgtype.Timestamptz
	IssuedByMembershipID pgtype.UUID
}

// Orders module — Invoice queries (BRD §A-014). Append-only. Tenant scoping
// via RLS.
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.NumberKind,
		arg.NumberFinancialYear,
		arg.NumberSeq,
		arg.NumberDisplay,
		arg.LineItems,
		arg.TaxLines,
		arg.SubtotalPaise,
		arg.TaxPaise,
		arg.GrandTotalPaise,
		arg.IssuedAt,
		arg.IssuedByMembershipID,
	)
	return err
}
