// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, tenant_id, approved_quotation_id, customer_lead_id, state,
       confirmed_items, subtotal_paise, tax_paise, grand_total_paise,
       invoice_id, consignment_note_id,
       confirmed_at, packed_at, invoiced_at, dispatched_at, delivered_at,
       completed_at, cancelled_at, cancellation_reason,
       created_at, created_by_membership_id
FROM   orders.orders
WHERE  id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i OrdersOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApprovedQuotationID,
		&i.CustomerLeadID,
		&i.State,
		&i.ConfirmedItems,
		&i.SubtotalPaise,
		&i.TaxPaise,
		&i.GrandTotalPaise,
		&i.InvoiceID,
		&i.ConsignmentNoteID,
		&i.ConfirmedAt,
		&i.PackedAt,
		&i.InvoicedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, tenant_id, approved_quotation_id, customer_lead_id, state,
       confirmed_items, subtotal_paise, tax_paise, grand_total_paise,
       invoice_id, consignment_note_id,
       confirmed_at, packed_at, invoiced_at, dispatched_at, delivered_at,
       completed_at, cancelled_at, cancellation_reason,
       created_at, created_by_membership_id
FROM   orders.orders
WHERE  id = $1
FOR UPDATE
`

// Row-locks the order for the UpdateFn transaction so concurrent lifecycle
// transitions serialise.
func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i OrdersOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApprovedQuotationID,
		&i.CustomerLeadID,
		&i.State,
		&i.ConfirmedItems,
		&i.SubtotalPaise,
		&i.TaxPaise,
		&i.GrandTotalPaise,
		&i.InvoiceID,
		&i.ConsignmentNoteID,
		&i.ConfirmedAt,
		&i.PackedAt,
		&i.InvoicedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :exec

INSERT INTO orders.orders (
    id, tenant_id, approved_quotation_id, customer_lead_id, state,
    confirmed_items, subtotal_paise, tax_paise, grand_total_paise,
    invoice_id, consignment_note_id,
    confirmed_at, packed_at, invoiced_at, dispatched_at, delivered_at,
    completed_at, cancelled_at, cancellation_reason,
    created_at, created_by_membership_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21
)
`

type InsertOrderParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	ApprovedQuotationID   pgtype.UUID
	CustomerLeadID        pgtype.UUID
	State                 string
	ConfirmedItems        []byte
	SubtotalPaise         int64
	TaxPaise              int64
	GrandTotalPaise       int64
	InvoiceID             pgtype.UUID
	ConsignmentNoteID     pgtype.UUID
	ConfirmedAt           pgtype.Timestamptz
	PackedAt              pgtype.Timestamptz
	InvoicedAt            pgtype.Timestamptz
	DispatchedAt          pgtype.Timestamptz
	DeliveredAt           pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
	CancellationReason    string
	CreatedAt             pgtype.Timestamptz
	CreatedByMembershipID pgtype.UUID
}

// Orders module — Order queries (ADR 0063). Tenant scoping via RLS.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.TenantID,
		arg.ApprovedQuotationID,
		arg.CustomerLeadID,
		arg.State,
		arg.ConfirmedItems,
		arg.SubtotalPaise,
		arg.TaxPaise,
		arg.GrandTotalPaise,
		arg.InvoiceID,
		arg.ConsignmentNoteID,
		arg.ConfirmedAt,
		arg.PackedAt,
		arg.InvoicedAt,
		arg.DispatchedAt,
		arg.DeliveredAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancellationReason,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders.orders SET
    state               = $2,
    invoice_id          = $3,
    consignment_note_id = $4,
    confirmed_at        = $5,
    packed_at           = $6,
    invoiced_at         = $7,
    dispatched_at       = $8,
    delivered_at        = $9,
    completed_at        = $10,
    cancelled_at        = $11,
    cancellation_reason = $12
WHERE id = $1
`

type UpdateOrderParams struct {
	ID                 pgtype.UUID
	State              string
	InvoiceID          pgtype.UUID
	ConsignmentNoteID  pgtype.UUID
	ConfirmedAt        pgtype.Timestamptz
	PackedAt           pgtype.Timestamptz
	InvoicedAt         pgtype.Timestamptz
	DispatchedAt       pgtype.Timestamptz
	DeliveredAt        pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
}

// Persists the mutable lifecycle columns. Confirmed items + money totals +
// creation facts are snapshotted at creation and never change.
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder,
		arg.ID,
		arg.State,
		arg.InvoiceID,
		arg.ConsignmentNoteID,
		arg.ConfirmedAt,
		arg.PackedAt,
		arg.InvoicedAt,
		arg.DispatchedAt,
		arg.DeliveredAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancellationReason,
	)
	return err
}
