// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, tenant_id, order_id, kind, method, amount_paise,
       external_reference, notes, received_at, recorded_at, recorded_by_membership_id
FROM   orders.payments
WHERE  id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (OrdersPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i OrdersPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Kind,
		&i.Method,
		&i.AmountPaise,
		&i.ExternalReference,
		&i.Notes,
		&i.ReceivedAt,
		&i.RecordedAt,
		&i.RecordedByMembershipID,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec

INSERT INTO orders.payments (
    id, tenant_id, order_id, kind, method, amount_paise,
    external_reference, notes, received_at, recorded_at, recorded_by_membership_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertPaymentParams struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	OrderID                pgtype.UUID
	Kind                   string
	Method                 string
	AmountPaise            int64
	ExternalReference      string
	Notes                  string
	ReceivedAt             pgtype.Timestamptz
	RecordedAt             pgtype.Timestamptz
	RecordedByMembershipID pgtype.UUID
}

// Orders module — Payment queries (BRD §6.4). Append-only. Tenant scoping
// via RLS.
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.Kind,
		arg.Method,
		arg.AmountPaise,
		arg.ExternalReference,
		arg.Notes,
		arg.ReceivedAt,
		arg.RecordedAt,
		arg.RecordedByMembershipID,
	)
	return err
}

const listPaymentsByOrder = `-- name: ListPaymentsByOrder :many
SELECT id, tenant_id, order_id, kind, method, amount_paise,
       external_reference, notes, received_at, recorded_at, recorded_by_membership_id
FROM   orders.payments
WHERE  order_id = $1
ORDER  BY received_at, id
`

func (q *Queries) ListPaymentsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrdersPayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersPayment
	for rows.Next() {
		var i OrdersPayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.Kind,
			&i.Method,
			&i.AmountPaise,
			&i.ExternalReference,
			&i.Notes,
			&i.ReceivedAt,
			&i.RecordedAt,
			&i.RecordedByMembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
