// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuotationByID = `-- name: GetQuotationByID :one
SELECT id, tenant_id, customer_lead_id, state, revisions,
       approved_at, approved_by_membership_id,
       rejected_at, rejected_by_membership_id, rejection_reason,
       created_at, created_by_membership_id
FROM   orders.quotations
WHERE  id = $1
`

func (q *Queries) GetQuotationByID(ctx context.Context, id pgtype.UUID) (OrdersQuotation, error) {
	row := q.db.QueryRow(ctx, getQuotationByID, id)
	var i OrdersQuotation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerLeadID,
		&i.State,
		&i.Revisions,
		&i.ApprovedAt,
		&i.ApprovedByMembershipID,
		&i.RejectedAt,
		&i.RejectedByMembershipID,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const getQuotationByIDForUpdate = `-- name: GetQuotationByIDForUpdate :one
SELECT id, tenant_id, customer_lead_id, state, revisions,
       approved_at, approved_by_membership_id,
       rejected_at, rejected_by_membership_id, rejection_reason,
       created_at, created_by_membership_id
FROM   orders.quotations
WHERE  id = $1
FOR UPDATE
`

// Row-locks the quotation for the UpdateFn transaction so concurrent revise /
// approve / reject calls serialise.
func (q *Queries) GetQuotationByIDForUpdate(ctx context.Context, id pgtype.UUID) (OrdersQuotation, error) {
	row := q.db.QueryRow(ctx, getQuotationByIDForUpdate, id)
	var i OrdersQuotation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerLeadID,
		&i.State,
		&i.Revisions,
		&i.ApprovedAt,
		&i.ApprovedByMembershipID,
		&i.RejectedAt,
		&i.RejectedByMembershipID,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CreatedByMembershipID,
	)
	return i, err
}

const insertQuotation = `-- name: InsertQuotation :exec

INSERT INTO orders.quotations (
    id, tenant_id, customer_lead_id, state, revisions,
    approved_at, approved_by_membership_id,
    rejected_at, rejected_by_membership_id, rejection_reason,
    created_at, created_by_membership_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10,
    $11, $12
)
`

type InsertQuotationParams struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	CustomerLeadID         pgtype.UUID
	State                  string
	Revisions              []byte
	ApprovedAt             pgtype.Timestamptz
	ApprovedByMembershipID pgtype.UUID
	RejectedAt             pgtype.Timestamptz
	RejectedByMembershipID pgtype.UUID
	RejectionReason        string
	CreatedAt              pgtype.Timestamptz
	CreatedByMembershipID  pgtype.UUID
}

// Orders module — Quotation queries (ADR 0063). Tenant scoping via RLS (the
// adapter binds app.tenant_id); WHERE clauses key on id only.
func (q *Queries) InsertQuotation(ctx context.Context, arg InsertQuotationParams) error {
	_, err := q.db.Exec(ctx, insertQuotation,
		arg.ID,
		arg.TenantID,
		arg.CustomerLeadID,
		arg.State,
		arg.Revisions,
		arg.ApprovedAt,
		arg.ApprovedByMembershipID,
		arg.RejectedAt,
		arg.RejectedByMembershipID,
		arg.RejectionReason,
		arg.CreatedAt,
		arg.CreatedByMembershipID,
	)
	return err
}

const updateQuotation = `-- name: UpdateQuotation :exec
UPDATE orders.quotations SET
    state                     = $2,
    revisions                 = $3,
    approved_at               = $4,
    approved_by_membership_id = $5,
    rejected_at               = $6,
    rejected_by_membership_id = $7,
    rejection_reason          = $8
WHERE id = $1
`

type UpdateQuotationParams struct {
	ID                     pgtype.UUID
	State                  string
	Revisions              []byte
	ApprovedAt             pgtype.Timestamptz
	ApprovedByMembershipID pgtype.UUID
	RejectedAt             pgtype.Timestamptz
	RejectedByMembershipID pgtype.UUID
	RejectionReason        string
}

// Persists the mutable columns. Identity + creation facts never change.
func (q *Queries) UpdateQuotation(ctx context.Context, arg UpdateQuotationParams) error {
	_, err := q.db.Exec(ctx, updateQuotation,
		arg.ID,
		arg.State,
		arg.Revisions,
		arg.ApprovedAt,
		arg.ApprovedByMembershipID,
		arg.RejectedAt,
		arg.RejectedByMembershipID,
		arg.RejectionReason,
	)
	return err
}
